In [8]:
import pandas as pd
import re

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
location_df_normalized = pd.read_csv('../data/location_df_normalized.csv')

In [3]:
# Store original column names
original_columns = location_df_normalized.columns.tolist()

# Function to normalize column names
def normalize_column_name(column):
    
    # Convert to lowercase
    column = column.lower()
    
    # Remove leading and trailing spaces
    column = column.strip()
    
    # Replace punctuation with spaces
    column = re.sub(r'[-_.,]', ' ', column)
    
    # Replace multiple spaces with a single space
    column = re.sub(r'\s+', ' ', column)
    
    # Standardize common abbreviations
    replacements = {
        r'\brd\b': 'road',
        r'\bst\b': 'street',
        r'\bexpy\b': 'expressway',
        r'\bhwy\b': 'highway',
        r'\bintl\b': 'international'
    }
    
    for pattern, replacement in replacements.items():
        column = re.sub(pattern, replacement, column)
    
    return column.strip()


# Create normalized column names
normalized_columns = [
    normalize_column_name(col)
    for col in original_columns
]


# Create a mapping DataFrame
column_mapping_df = pd.DataFrame({
    'original_column': original_columns,
    'normalized_column': normalized_columns
})


# Display total number of columns
print("Total original columns:", len(original_columns))


# Display first 50 mappings
print("\nFirst 50 column mappings:")
print(column_mapping_df.head(50))


# Find duplicate normalized column names
duplicate_groups = (
    column_mapping_df
    .groupby('normalized_column')['original_column']
    .apply(list)
)


# Keep only groups with more than one original column
duplicate_groups = duplicate_groups[
    duplicate_groups.apply(len) > 1
]


# Print duplicate groups
print("\nDuplicate groups after normalization:\n")

for normalized_name, original_names in duplicate_groups.items():
    
    print(f"Normalized Name: {normalized_name}")
    print("Original columns:")
    
    for name in original_names:
        print(f"- {name}")
    
    print("-" * 50)

Total original columns: 1071

First 50 column mappings:
                           original_column  \
0                             PropertyName
1                            Bajghera Road
2                         Palam Vihar Halt
3                         DPSG Palam Vihar
4                            Park Hospital
5                  Gurgaon Railway Station
6                  The NorthCap University
7                              Dwarka Expy
8          Hyatt Place Gurgaon Udyog Vihar
9          Dwarka Sector 21, Metro Station
10                        Pacific D21 Mall
11     Indira Gandhi International Airport
12                        Hamoni Golf Camp
13                    Fun N Food Waterpark
14                          Accenture DDC5
15               DPSG Palam Vihar Gurugram
16              Park Hospital, Palam Vihar
17        Palam Vihar Halt Railway Station
18          Dwarka Sector 21 Metro Station
19                       Dwarka Expressway
20                   Fun N Food Water Park
21              Tau DeviLal Sports Complex
22                             Hyatt Place
23                 Altrade Business Centre
24            AIPL Business Club Sector 62
25    Heritage Xperiential Learning School
26                       CK Birla Hospital
27            Paras Trinity Mall Sector 63
28           Rapid Metro Station Sector 56
29                       De Adventure Park
30                      Golf Course Ext Rd
31      DoubleTree by Hilton Hotel Gurgaon
32  KIIT College of Engineering Sohna Road
33                   Mehrauli-Gurgaon Road
34                              Nirvana Rd
35                        TERI Golf Course
36                   The Shikshiyan School
37                               WTC Plaza
38                    Luxus Haritma Resort
39                         BSF Golf Course
40                          Rions Hospital
41                                 Gurgaon
42                        Dwarka Sector 21
43                           Nehru Stadium
44                    Fun N Food WaterPark
45                             IGI Airport
46                             Vasant Kunj
47                Pranavananda Int. School
48                 DLF Site central office
49          Holiday Inn Gurugram Sector 90

                         normalized_column
0                             propertyname
1                            bajghera road
2                         palam vihar halt
3                         dpsg palam vihar
4                            park hospital
5                  gurgaon railway station
6                  the northcap university
7                        dwarka expressway
8          hyatt place gurgaon udyog vihar
9           dwarka sector 21 metro station
10                        pacific d21 mall
11     indira gandhi international airport
12                        hamoni golf camp
13                    fun n food waterpark
14                          accenture ddc5
15               dpsg palam vihar gurugram
16               park hospital palam vihar
17        palam vihar halt railway station
18          dwarka sector 21 metro station
19                       dwarka expressway
20                   fun n food water park
21              tau devilal sports complex
22                             hyatt place
23                 altrade business centre
24            aipl business club sector 62
25    heritage xperiential learning school
26                       ck birla hospital
27            paras trinity mall sector 63
28           rapid metro station sector 56
29                       de adventure park
30                    golf course ext road
31      doubletree by hilton hotel gurgaon
32  kiit college of engineering sohna road
33                   mehrauli gurgaon road
34                            nirvana road
35                        teri golf course
36                   the shikshiyan school
37                               wtc plaza
38                    luxus haritma resort
39                         bsf golf course
40                          rions hospital
41                                 gurgaon
42                        dwarka sector 21
43                           nehru stadium
44                    fun n food waterpark
45                             igi airport
46                             vasant kunj
47                 pranavananda int school
48                 dlf site central office
49          holiday inn gurugram sector 90

Duplicate groups after normalization:

Normalized Name: canara bank
Original columns:
- Canara Bank
- CANARA BANK
--------------------------------------------------
Normalized Name: country inn & suites by radisson
Original columns:
- Country Inn & Suites by Radisson
- Country Inn & Suites By Radisson
--------------------------------------------------
Normalized Name: delhi jaipur expressway
Original columns:
- Delhi - Jaipur Expressway
- Delhi Jaipur Expressway
--------------------------------------------------
Normalized Name: delhi public school sector 84
Original columns:
- Delhi Public School, Sector 84
- Delhi Public School Sector 84
--------------------------------------------------
Normalized Name: dwarka expressway
Original columns:
- Dwarka Expy
- Dwarka Expressway
- Dwarka expressway
--------------------------------------------------
Normalized Name: dwarka sector 21 metro station
Original columns:
- Dwarka Sector 21, Metro Station
- Dwarka Sector 21 Metro Station
- Dwarka Sector 21 Metro station
- Dwarka sector 21 metro station
--------------------------------------------------
Normalized Name: esic hospital
Original columns:
- ESIC Hospital
- ESIC HOSPITAL
--------------------------------------------------
Normalized Name: euro international school sector 109
Original columns:
- Euro International School, Sector- 109
- Euro International School, Sector- 109.
- Euro Intl School, Sector- 109
--------------------------------------------------
Normalized Name: faridabad gurgaon road
Original columns:
- Faridabad Gurgaon Road
- Faridabad - Gurgaon Road
- Faridabad - Gurgaon Rd
--------------------------------------------------
Normalized Name: fun n food waterpark
Original columns:
- Fun N Food Waterpark
- Fun N Food WaterPark
--------------------------------------------------
Normalized Name: gd goenka university
Original columns:
- Gd goenka university
- GD Goenka University
--------------------------------------------------
Normalized Name: gems international school
Original columns:
- GEMS International School
- Gems International School
--------------------------------------------------
Normalized Name: global city centre
Original columns:
- Global city centre
- Global City Centre
--------------------------------------------------
Normalized Name: golf course ext road
Original columns:
- Golf Course Ext Rd
- Golf Course Ext Road
--------------------------------------------------
Normalized Name: golf course extension road
Original columns:
- Golf Course Extension Road
- Golf Course Extension Rd
- Golf course extension road
--------------------------------------------------
Normalized Name: golf course road
Original columns:
- Golf Course Road
- Golf Course Rd
--------------------------------------------------
Normalized Name: gurgaon railway station
Original columns:
- Gurgaon Railway Station
- Gurgaon railway station
--------------------------------------------------
Normalized Name: gurugram road
Original columns:
- Gurugram Road
- Gurugram Rd
--------------------------------------------------
Normalized Name: hdfc bank atm
Original columns:
- HDFC Bank ATM
- HDFC bank ATM
--------------------------------------------------
Normalized Name: health care pharmacy
Original columns:
- Health Care Pharmacy
- Health care pharmacy
--------------------------------------------------
Normalized Name: heritage badminton academy
Original columns:
- Heritage badminton academy
- Heritage Badminton Academy
--------------------------------------------------
Normalized Name: hub 66
Original columns:
- HUB 66
- Hub 66
--------------------------------------------------
Normalized Name: huda metro station
Original columns:
- Huda Metro Station
- Huda metro station
- HUDA Metro Station
- Huda Metro station
--------------------------------------------------
Normalized Name: iffco chowk
Original columns:
- IFFCO Chowk
- Iffco Chowk
--------------------------------------------------
Normalized Name: iffco chowk metro station
Original columns:
- IFFCO Chowk Metro Station
- Iffco Chowk Metro Station
--------------------------------------------------
Normalized Name: imt manesar
Original columns:
- IMT Manesar
- Imt Manesar
--------------------------------------------------
Normalized Name: indira gandhi international airport
Original columns:
- Indira Gandhi International Airport
- Indira Gandhi Intl Airport
--------------------------------------------------
Normalized Name: infinity business park
Original columns:
- Infinity Business Park
- infinity Business Park
--------------------------------------------------
Normalized Name: infinitys badminton academy
Original columns:
- InfinityS Badminton Academy
- Infinitys Badminton Academy
--------------------------------------------------
Normalized Name: international tech park gurgaon
Original columns:
- International Tech Park Gurgaon,
- International Tech Park Gurgaon
--------------------------------------------------
Normalized Name: iris broadway mall
Original columns:
- Iris Broadway Mall
- IRIS Broadway Mall
--------------------------------------------------
Normalized Name: k r mangalam university
Original columns:
- K. R. Mangalam University
- K.R. Mangalam University
--------------------------------------------------
Normalized Name: kmp corridor
Original columns:
- KMP Corridor
- KMP corridor
--------------------------------------------------
Normalized Name: lemon tree hotel
Original columns:
- Lemon Tree Hotel
- Lemon Tree Hotel,
--------------------------------------------------
Normalized Name: matrikiran high school
Original columns:
- Matrikiran High School
- MatriKiran High School
--------------------------------------------------
Normalized Name: medanta the medicity
Original columns:
- Medanta -The Medicity
- Medanta-The Medicity
- Medanta The Medicity
- Medanta - The Medicity
--------------------------------------------------
Normalized Name: mehrauli gurgaon road
Original columns:
- Mehrauli-Gurgaon Road
- Mehrauli-Gurgaon Rd
--------------------------------------------------
Normalized Name: national highway 48
Original columns:
- National Highway  48
- National Highway 48
- National Highway-48
--------------------------------------------------
Normalized Name: nh 48
Original columns:
- NH 48
- NH-48
--------------------------------------------------
Normalized Name: nh 8
Original columns:
- NH -8
- NH-8
- NH 8
--------------------------------------------------
Normalized Name: nh 8 imt manesar
Original columns:
- NH-8, IMT Manesar
- NH-8, Imt Manesar
- NH-8 IMT Manesar
--------------------------------------------------
Normalized Name: omaxe gurgaon mall
Original columns:
- Omaxe Gurgaon Mall
- OMAXE Gurgaon Mall
--------------------------------------------------
Normalized Name: park inn
Original columns:
- Park Inn
- Park inn
--------------------------------------------------
Normalized Name: pataudi road
Original columns:
- Pataudi Road
- Pataudi road
- Pataudi Rd
--------------------------------------------------
Normalized Name: pvr drive in theatre
Original columns:
- PVR Drive In Theatre
- PVR Drive in Theatre
--------------------------------------------------
Normalized Name: reliance trends newtown square mall
Original columns:
- Reliance Trends Newtown Square Mall
- RELIANCE TRENDS Newtown Square Mall
--------------------------------------------------
Normalized Name: sector 42 43 metro station
Original columns:
- Sector 42-43 Metro Station
- Sector 42-43 Metro station
--------------------------------------------------
Normalized Name: sector 55 56 metro
Original columns:
- Sector 55-56 metro
- Sector 55-56 Metro
--------------------------------------------------
Normalized Name: sector 55 56 metro station
Original columns:
- Sector 55-56 Metro Station
- Sector 55-56 Metro station
- Sector 55-56 metro station
--------------------------------------------------
Normalized Name: sector 55 56 rapid metro station
Original columns:
- Sector 55-56 Rapid Metro Station
- Sector 55-56 rapid metro station
--------------------------------------------------
Normalized Name: sgt university
Original columns:
- SGT University
- SGT UNIVERSITY
--------------------------------------------------
Normalized Name: shiv mandir
Original columns:
- Shiv Mandir
- shiv Mandir
--------------------------------------------------
Normalized Name: sohna road
Original columns:
- Sohna Road
- Sohna Rd
--------------------------------------------------
Normalized Name: southern peripheral road
Original columns:
- Southern Peripheral Rd
- Southern Peripheral Road
--------------------------------------------------
Normalized Name: teri golf course
Original columns:
- TERI Golf Course
- Teri Golf Course
--------------------------------------------------
Normalized Name: the oberoi gurgaon
Original columns:
- The Oberoi Gurgaon
- The Oberoi, Gurgaon
--------------------------------------------------
Normalized Name: vardaan hospital and trauma centre
Original columns:
- Vardaan hospital and trauma centre
- Vardaan Hospital and Trauma Centre
--------------------------------------------------
Normalized Name: yes bank
Original columns:
- Yes Bank
- YES Bank
--------------------------------------------------
Normalized Name: yes bank atm
Original columns:
- YES Bank ATM
- YES bank ATM
--------------------------------------------------

In [6]:
from rapidfuzz import fuzz, process

# Get the unique normalized column names
unique_normalized_columns = column_mapping_df[
    'normalized_column'
].unique().tolist()

# Minimum similarity score
threshold = 85

# Store similar pairs
similar_pairs = []

# Compare every column with every other column
for i, col1 in enumerate(unique_normalized_columns):
    
    for col2 in unique_normalized_columns[i + 1:]:
        
        similarity = fuzz.token_sort_ratio(col1, col2)
        
        # Keep only highly similar pairs
        if similarity >= threshold:
            
            similar_pairs.append({
                'column_1': col1,
                'column_2': col2,
                'similarity': round(similarity, 2)
            })


# Convert results to DataFrame
similar_columns_df = pd.DataFrame(similar_pairs)

# Sort by similarity score
similar_columns_df = similar_columns_df.sort_values(
    by='similarity',
    ascending=False
).reset_index(drop=True)


# Display results
print("Number of similar column pairs:", len(similar_columns_df))

print("\nTop similar column pairs:\n")

print(similar_columns_df.head(100))

Number of similar column pairs: 206

Top similar column pairs:

                                     column_1  \
0                    vivanta dwarka new delhi
1                    gurgaon delhi expressway
2            sector 55 56 rapid metro station
3                    rapid metro sector 55 56
4                  tau devilal sports complex
..                                        ...
95                 golf course extension road
96                 golf course extension road
97                    gurgaon railway station
98  lotus valley international school gurgaon
99               holiday inn express gurugram

                               column_2  similarity
0              vivanta new delhi dwarka      100.00
1              delhi gurgaon expressway      100.00
2      rapid metro station sector 55 56      100.00
3              sector 55 56 rapid metro      100.00
4           tau devi lal sports complex       98.11
..                                  ...         ...
95                golf course extension       89.36
96                golf course extn road       89.36
97             gurugram railway station       89.36
98    lotus valley international school       89.19
99  holiday inn express gurugram sec 50       88.89

[100 rows x 3 columns]

In [9]:
print(similar_columns_df)

                                      column_1  \
0                     vivanta dwarka new delhi
1                     gurgaon delhi expressway
2             sector 55 56 rapid metro station
3                     rapid metro sector 55 56
4                   tau devilal sports complex
5                     badshahpur sohna highway
6                       delhi ajmer expressway
7                       proposed metro station
8                         the millenium school
9                         golf course ext road
10     badshahpur sohna road highway sector 48
11                        golf course ext road
12                         national highway 48
13                           dwarka expressway
14                              paras hospital
15                             ektaa hospitals
16                              rions hospital
17                              aarvy hospital
18                 street xavier's high school
19                  sector 55 56 metro station
20                  sector 53 54 metro station
21      holiday inn express gurugram sector 50
22        euro international school sector 109
23                                 igi airport
24                     sector 55 metro station
25            euro international school sec 51
26            euro international school sec 84
27               rapid metro station sector 56
28               rapid metro station sector 56
29                         golf corse ext road
30                        pvr drive in theatre
31                                   aapnoghar
32     the signature super speciality hospital
33         euro international school sector 84
34            country inn & suites by radisson
35          vardaan hospital and trauma centre
36                  sector 55/56 metro station
37                     sector 53 metro station
38                  sector 55 56 metro station
39                  sector 53 54 metro station
40                     sector 55 metro station
41                  sector 53 54 metro station
42                            artimis hospital
43                            huda city centre
44            euro international school sec 84
45                            sapphire 83 mall
46                     cd international school
47                    southern peripheral road
48                    rapid metro sector 55 56
49                                     nh 248a
50                    sector 55 56 rapid metro
51                      gd goenka world school
52                      kr mangalam university
53               basai dhankot railway station
54                       international airport
55                      omaxe city centre mall
56        euro international school sector 37d
57        euro international school sector 109
58        euro international school sector 37d
59                              sector 86 road
60                       g d goenka university
61                                     nh 248a
62                  sector 55/56 metro station
63                               amma hospital
64                  sector 55 56 metro station
65          scottish high international school
66                     gurgaon railway station
67                  kings international school
68                          sanjivani hospital
69                    sector 53 54 rapid metro
70                    rps international school
71                    sector 53 54 rapid metro
72        euro international school sector 109
73               delhi public school sector 84
74                          rbsm public school
75                   indira gandhi int airport
76        euro international school sector 109
77                dwarka expressway sector 109
78                                       nh 48
79                    badshahpur sohna highway
80                 delhi international airport
81                     vatika town square inxt
82                        gaytri public school
83                     sector 53 metro station
84                 street xavier's high school
85                  sector 55 56 metro station
86                   gems international school
87                  sector 55/56 metro station
88                               sapphire mall
89                            sapphire 83 mall
90                  sector 55 56 metro station
91                  sector 42 43 metro station
92                  sector 55 56 metro station
93            euro international school sec 84
94         euro international school sector 84
95                  golf course extension road
96                  golf course extension road
97                     gurgaon railway station
98   lotus valley international school gurgaon
99                holiday inn express gurugram
100       euro international school sector 37d
101                              sneh hospital
102                   sector 53 54 rapid metro
103                              park hospital
104                                       nh 8
105                                      nh 48
106                  nh 8 delhi jaipur highway
107                   southern peripheral road
108                             aryan hospital
109                             aryan hospital
110                       golf course ext road
111            miracles apollo cradle hospital
112            miracles apollo cradle hospital
113              rapid metro station sector 56
114             adarsh senior secondary school
115              badshahpur sohna road highway
116                   rps international school
117                 sector 55/56 metro station
118                 sector 53 54 metro station
119                 sector 55 56 metro station
120               lancers international school
121                        gurugram university
122                     hyatt regency gurugram
123       euro international school sector 37d
124       euro international school sector 37d
125                        dlf world tech park
126       euro international school sector 109
127              arc multi speciality hospital
128                   rps international school
129                   rps international school
130                     kr mangalam university
131                              arvy hospital
132                  euro international school
133              badshahpur sohna road highway
134                         global city centre
135                    vatika town square inxt
136                         vatika city centre
137                  euro international school
138                  euro international school
139                   sector 42 43 rapid metro
140           sector 55 56 rapid metro station
141       golden greens golf & resorts limited
142                         the esplanade mall
143                  gems international school
144                             bank of baroda
145           sector 42 43 rapid metro station
146                      holiday inn sector 90
147        euro int school sector 37d gurugram
148                delhi international airport
149                  euro international school
150            miracles apollo cradle hospital
151            bm college of technology & mgmt
152            miracles apollo cradle hospital
153                        dharampur main road
154                          matrikiran school
155                          omaxe city centre
156                     jms marine square mall
157                       golf course ext road
158             silver streak multi speciality
159         doubletree by hilton hotel gurgaon
160                             paras hospital
161                           polaris hospital
162                           medanta hospital
163                          ambience mall new
164                          indusind bank atm
165                 royal institute of science
166              western peripheral expressway
167                           m3m cosmopolitan
168                           golf course road
169                           gd goenka school
170                  amity university gurugram
171                    k r mangalam university
172                ashoka international school
173                  skyjumper trampoline park
174                 sector 55/56 metro station
175                 sector 55/56 metro station
176                    sector 55 metro station
177                         sector 55 56 metro
178                   sector 42 43 rapid metro
179                  euro international school
180                           golf course road
181       heritage xperiential learning school
182                             mamta hospital
183                                       nh48
184                         sector 55 56 metro
185           narayana e techno school manesar
186           sector 55 56 rapid metro station
187           sector 55 56 rapid metro station
188                              park hospital
189                                   nh 248 a
190                   sector 55 56 rapid metro
191                             umkal hospital
192                   rapid metro sector 55 56
193                            ananta hospital
194                             aryan hospital
195                                    nh 248a
196             holiday inn gurugram sector 90
197              badshahpur sohna road highway
198    badshahpur sohna road highway sector 48
199                   dps international school
200                 kings international school
201                     street xavier's school
202                    cd international school
203                   rps international school
204                         cbr cricket ground
205                        lions public school

                                          column_2  similarity
0                         vivanta new delhi dwarka      100.00
1                         delhi gurgaon expressway      100.00
2                 rapid metro station sector 55 56      100.00
3                         sector 55 56 rapid metro      100.00
4                      tau devi lal sports complex       98.11
5                          badshapur sohna highway       97.87
6                            delh ajmer expressway       97.67
7                            propose metro station       97.67
8                            the millennium school       97.56
9                            golf course extn road       97.56
10         badshahpur sohna road highway sector 68       97.44
11                             golf corse ext road       97.44
12                              national highway 8       97.30
13                              dwaraka expressway       97.14
14                                 paras hospitals       96.55
15                                  ektaa hospital       96.55
16                                 rion's hospital       96.55
17                                   arvy hospital       96.30
18                       street xavier high school       96.15
19                      sector 55/56 metro station       96.15
20                      sector 53/54 metro station       96.15
21             holiday inn express gurugram sec 50       95.89
22             euro international school sector 51       95.77
23                                    igia airport       95.65
24                         sector 53 metro station       95.65
25             euro international school sector 51       95.52
26             euro international school sector 84       95.52
27                rapid metro station sector 55 56       95.08
28                sector 55 56 rapid metro station       95.08
29                           golf course extn road       95.00
30                            pvr drive in theater       95.00
31                                      aapno ghar       94.74
32             signature super speciality hospital       94.59
33             euro international school sector 51       94.29
34              country inn and suites by radisson       93.94
35                vardaan hospital & trauma centre       93.94
36                         sector 55 metro station       93.88
37                      sector 53/54 metro station       93.88
38                         sector 55 metro station       93.88
39                         sector 55 metro station       93.88
40                      sector 53/54 metro station       93.88
41                         sector 53 metro station       93.88
42                                artemis hospital       93.75
43                                huda city center       93.75
44                euro international school sec 51       93.75
45                                sapphire 93 mall       93.75
46                        dps international school       93.62
47                         southern periphery road       93.62
48                           rapid metro sector 56       93.33
49                                        nh 248 a       93.33
50                           rapid metro sector 56       93.33
51                         g d goenka world school       93.33
52                         k r mangalam university       93.33
53                 basai dhancourt railway station       93.33
54                        ig international airport       93.33
55                           omex city centre mall       93.02
56             euro international school sector 84       92.96
57             euro international school sector 84       92.96
58             euro international school sector 51       92.96
59                                  sector 84 road       92.86
60                            gd goenka university       92.68
61                                          nh 248       92.31
62                      sector 53/54 metro station       92.31
63                                   aman hospital       92.31
64                      sector 53 54 metro station       92.31
65                   scottish international school       92.06
66                     gurgaon old railway station       92.00
67                        s n international school       92.00
68                             sanjeevani hospital       91.89
69                        sector 55 56 rapid metro       91.67
70                        s n international school       91.67
71                        rapid metro sector 55 56       91.67
72            euro international school sector 37d       91.67
73                  delhi public school sector 103       91.53
74                               rhm public school       91.43
75                           indira gandhi airport       91.30
76                euro international school sec 51       91.18
77                     dwarka expressway sector 88       90.91
78                                          nh 248       90.91
79                   badshahpur sohna road highway       90.57
80                        ig international airport       90.20
81                    vatika town square inxt mall       90.20
82                            garima public school       90.00
83                      sector 42 43 metro station       89.80
84                          street xavier's school       89.80
85                         sector 53 metro station       89.80
86                        dps international school       89.80
87                         sector 53 metro station       89.80
88                                sapphire 93 mall       89.66
89                                   sapphire mall       89.66
90                rapid metro station sector 55 56       89.66
91                sector 42 43 rapid metro station       89.66
92                sector 55 56 rapid metro station       89.66
93             euro international school sector 51       89.55
94                euro international school sec 51       89.55
95                           golf course extension       89.36
96                           golf course extn road       89.36
97                        gurugram railway station       89.36
98               lotus valley international school       89.19
99             holiday inn express gurugram sec 50       88.89
100  euro international school sector 37d gurugram       88.89
101                                 sethi hospital       88.89
102                          rapid metro sector 56       88.89
103                                 paras hospital       88.89
104                                          nh 08       88.89
105                                           nh 8       88.89
106                           delhi jaipur highway       88.89
107                 southern peripheral road dhani       88.89
108                                  aman hospital       88.89
109                                  arvy hospital       88.89
110                               golf course road       88.89
111        miracles apollo cradle/spectra hospital       88.57
112        miracles apollo cradle spectra hospital       88.57
113               sector 42 43 rapid metro station       88.52
114                jhankar senior secondary school       88.52
115                        badshapur sohna highway       88.46
116                   lancers international school       88.46
117                     sector 53 54 metro station       88.46
118                     sector 42 43 metro station       88.46
119                     sector 53/54 metro station       88.46
120                       s n international school       88.46
121                       iilm university gurugram       88.37
122                          hyatt regency gurgaon       88.37
123               euro international school sec 84       88.24
124               euro international school sec 51       88.24
125                                world tech park       88.24
126               euro international school sec 84       88.24
127                 anand multispeciality hospital       88.14
128                     ompee international school       88.00
129                     kings international school       88.00
130                   kr mangalam university sohna       88.00
131                                   arc hospital       88.00
132                      gems international school       88.00
133          badshahpur sohna road highway haryana       87.88
134                        global city centre mall       87.80
135                             vatika town square       87.80
136                        vatika city centre mall       87.80
137               euro international school sec 84       87.72
138               euro international school sec 51       87.72
139                       sector 53 54 rapid metro       87.50
140               sector 42 43 rapid metro station       87.50
141                   golden greens golf & resorts       87.50
142                                 esplanade mall       87.50
143                        cd international school       87.50
144                             bank of baroda atm       87.50
145               rapid metro station sector 55 56       87.50
146                    holiday inn hotel sector 90       87.50
147  euro international school sector 37d gurugram       87.50
148                          international airport       87.50
149                        cd international school       87.50
150       miracles apollo cradle /spectra hospital       87.32
151                       bm college of technology       87.27
152                       miracles apollo hospital       87.27
153                           dharampeth main road       87.18
154                         matrikiran high school       87.18
155                         omaxe city centre mall       87.18
156                              jms marine square       87.18
157                     golf course extension road       86.96
158        silver streak multi speciality hospital       86.96
159                     doubletree by hilton hotel       86.67
160                               prakash hospital       86.67

In [10]:
display(similar_columns_df)

,column_1,column_2,similarity
0,vivanta dwarka new delhi,vivanta new delhi dwarka,100.00
1,gurgaon delhi expressway,delhi gurgaon expressway,100.00
2,sector 55 56 rapid metro station,rapid metro station sector 55 56,100.00
3,rapid metro sector 55 56,sector 55 56 rapid metro,100.00
4,tau devilal sports complex,tau devi lal sports complex,98.11
5,badshahpur sohna highway,badshapur sohna highway,97.87
6,delhi ajmer expressway,delh ajmer expressway,97.67
7,proposed metro station,propose metro station,97.67
8,the millenium school,the millennium school,97.56
9,golf course ext road,golf course extn road,97.56
10,badshahpur sohna road highway sector 48,badshahpur sohna road highway sector 68,97.44
11,golf course ext road,golf corse ext road,97.44
12,national highway 48,national highway 8,97.30
13,dwarka expressway,dwaraka expressway,97.14
14,paras hospital,paras hospitals,96.55
15,ektaa hospitals,ektaa hospital,96.55
16,rions hospital,rion's hospital,96.55
17,aarvy hospital,arvy hospital,96.30
18,street xavier's high school,street xavier high school,96.15
19,sector 55 56 metro station,sector 55/56 metro station,96.15
20,sector 53 54 metro station,sector 53/54 metro station,96.15
21,holiday inn express gurugram sector 50,holiday inn express gurugram sec 50,95.89
22,euro international school sector 109,euro international school sector 51,95.77
23,igi airport,igia airport,95.65
24,sector 55 metro station,sector 53 metro station,95.65
25,euro international school sec 51,euro international school sector 51,95.52
26,euro international school sec 84,euro international school sector 84,95.52
27,rapid metro station sector 56,rapid metro station sector 55 56,95.08
28,rapid metro station sector 56,sector 55 56 rapid metro station,95.08
29,golf corse ext road,golf course extn road,95.00
30,pvr drive in theatre,pvr drive in theater,95.00
31,aapnoghar,aapno ghar,94.74
32,the signature super speciality hospital,signature super speciality hospital,94.59
33,euro international school sector 84,euro international school sector 51,94.29
34,country inn & suites by radisson,country inn and suites by radisson,93.94
35,vardaan hospital and trauma centre,vardaan hospital & trauma centre,93.94
36,sector 55/56 metro station,sector 55 metro station,93.88
37,sector 53 metro station,sector 53/54 metro station,93.88
38,sector 55 56 metro station,sector 55 metro station,93.88
39,sector 53 54 metro station,sector 55 metro station,93.88
40,sector 55 metro station,sector 53/54 metro station,93.88
41,sector 53 54 metro station,sector 53 metro station,93.88
42,artimis hospital,artemis hospital,93.75
43,huda city centre,huda city center,93.75
44,euro international school sec 84,euro international school sec 51,93.75
45,sapphire 83 mall,sapphire 93 mall,93.75
46,cd international school,dps international school,93.62
47,southern peripheral road,southern periphery road,93.62
48,rapid metro sector 55 56,rapid metro sector 56,93.33
49,nh 248a,nh 248 a,93.33
50,sector 55 56 rapid metro,rapid metro sector 56,93.33
51,gd goenka world school,g d goenka world school,93.33
52,kr mangalam university,k r mangalam university,93.33
53,basai dhankot railway station,basai dhancourt railway station,93.33
54,international airport,ig international airport,93.33
55,omaxe city centre mall,omex city centre mall,93.02
56,euro international school sector 37d,euro international school sector 84,92.96
57,euro international school sector 109,euro international school sector 84,92.96
58,euro international school sector 37d,euro international school sector 51,92.96
59,sector 86 road,sector 84 road,92.86
60,g d goenka university,gd goenka university,92.68
61,nh 248a,nh 248,92.31
62,sector 55/56 metro station,sector 53/54 metro station,92.31
63,amma hospital,aman hospital,92.31
64,sector 55 56 metro station,sector 53 54 metro station,92.31
65,scottish high international school,scottish international school,92.06
66,gurgaon railway station,gurgaon old railway station,92.00
67,kings international school,s n international school,92.00
68,sanjivani hospital,sanjeevani hospital,91.89
69,sector 53 54 rapid metro,sector 55 56 rapid metro,91.67
70,rps international school,s n international school,91.67
71,sector 53 54 rapid metro,rapid metro sector 55 56,91.67
72,euro international school sector 109,euro international school sector 37d,91.67
73,delhi public school sector 84,delhi public school sector 103,91.53
74,rbsm public school,rhm public school,91.43
75,indira gandhi int airport,indira gandhi airport,91.30
76,euro international school sector 109,euro international school sec 51,91.18
77,dwarka expressway sector 109,dwarka expressway sector 88,90.91
78,nh 48,nh 248,90.91
79,badshahpur sohna highway,badshahpur sohna road highway,90.57
80,delhi international airport,ig international airport,90.20
81,vatika town square inxt,vatika town square inxt mall,90.20
82,gaytri public school,garima public school,90.00
83,sector 53 metro station,sector 42 43 metro station,89.80
84,street xavier's high school,street xavier's school,89.80
85,sector 55 56 metro station,sector 53 metro station,89.80
86,gems international school,dps international school,89.80
87,sector 55/56 metro station,sector 53 metro station,89.80
88,sapphire mall,sapphire 93 mall,89.66
89,sapphire 83 mall,sapphire mall,89.66
90,sector 55 56 metro station,rapid metro station sector 55 56,89.66
91,sector 42 43 metro station,sector 42 43 rapid metro station,89.66
92,sector 55 56 metro station,sector 55 56 rapid metro station,89.66
93,euro international school sec 84,euro international school sector 51,89.55
94,euro international school sector 84,euro international school sec 51,89.55
95,golf course extension road,golf course extension,89.36
96,golf course extension road,golf course extn road,89.36
97,gurgaon railway station,gurugram railway station,89.36
98,lotus valley international school gurgaon,lotus valley international school,89.19
99,holiday inn express gurugram,holiday inn express gurugram sec 50,88.89
100,euro international school sector 37d,euro international school sector 37d gurugram,88.89
101,sneh hospital,sethi hospital,88.89
102,sector 53 54 rapid metro,rapid metro sector 56,88.89
103,park hospital,paras hospital,88.89
104,nh 8,nh 08,88.89
105,nh 48,nh 8,88.89
106,nh 8 delhi jaipur highway,delhi jaipur highway,88.89
107,southern peripheral road,southern peripheral road dhani,88.89
108,aryan hospital,aman hospital,88.89
109,aryan hospital,arvy hospital,88.89
110,golf course ext road,golf course road,88.89
111,miracles apollo cradle hospital,miracles apollo cradle/spectra hospital,88.57
112,miracles apollo cradle hospital,miracles apollo cradle spectra hospital,88.57
113,rapid metro station sector 56,sector 42 43 rapid metro station,88.52
114,adarsh senior secondary school,jhankar senior secondary school,88.52
115,badshahpur sohna road highway,badshapur sohna highway,88.46
116,rps international school,lancers international school,88.46
117,sector 55/56 metro station,sector 53 54 metro station,88.46
118,sector 53 54 metro station,sector 42 43 metro station,88.46
119,sector 55 56 metro station,sector 53/54 metro station,88.46
120,lancers international school,s n international school,88.46
121,gurugram university,iilm university gurugram,88.37
122,hyatt regency gurugram,hyatt regency gurgaon,88.37
123,euro international school sector 37d,euro international school sec 84,88.24
124,euro international school sector 37d,euro international school sec 51,88.24
125,dlf world tech park,world tech park,88.24
126,euro international school sector 109,euro international school sec 84,88.24
127,arc multi speciality hospital,anand multispeciality hospital,88.14
128,rps international school,ompee international school,88.00
129,rps international school,kings international school,88.00
130,kr mangalam university,kr mangalam university sohna,88.00
131,arvy hospital,arc hospital,88.00
132,euro international school,gems international school,88.00
133,badshahpur sohna road highway,badshahpur sohna road highway haryana,87.88
134,global city centre,global city centre mall,87.80
135,vatika town square inxt,vatika town square,87.80
136,vatika city centre,vatika city centre mall,87.80
137,euro international school,euro international school sec 84,87.72
138,euro international school,euro international school sec 51,87.72
139,sector 42 43 rapid metro,sector 53 54 rapid metro,87.50
140,sector 55 56 rapid metro station,sector 42 43 rapid metro station,87.50
141,golden greens golf & resorts limited,golden greens golf & resorts,87.50
142,the esplanade mall,esplanade mall,87.50
143,gems international school,cd international school,87.50
144,bank of baroda,bank of baroda atm,87.50
145,sector 42 43 rapid metro station,rapid metro station sector 55 56,87.50
146,holiday inn sector 90,holiday inn hotel sector 90,87.50
147,euro int school sector 37d gurugram,euro international school sector 37d gurugram,87.50
148,delhi international airport,international airport,87.50
149,euro international school,cd international school,87.50
150,miracles apollo cradle hospital,miracles apollo cradle /spectra hospital,87.32
151,bm college of technology & mgmt,bm college of technology,87.27
152,miracles apollo cradle hospital,miracles apollo hospital,87.27
153,dharampur main road,dharampeth main road,87.18
154,matrikiran school,matrikiran high school,87.18
155,omaxe city centre,omaxe city centre mall,87.18
156,jms marine square mall,jms marine square,87.18
157,golf course ext road,golf course extension road,86.96
158,silver streak multi speciality,silver streak multi speciality hospital,86.96
159,doubletree by hilton hotel gurgaon,doubletree by hilton hotel,86.67
160,paras hospital,prakash hospital,86.67
161,polaris hospital,paras hospital,86.67
162,medanta hospital,mamta hospital,86.67
163,ambience mall new,ambience mall,86.67
164,indusind bank atm,indusind bank,86.67
165,royal institute of science,royal institute of science and mgt,86.67
166,western peripheral expressway,western peripheral expressway gurugram,86.57
167,m3m cosmopolitan,m3m cosmopolitan mall,86.49
168,golf course road,golf course extn road,86.49
169,gd goenka school,gd goenka high school,86.49
170,amity university gurugram,gurugram university,86.36
171,k r mangalam university,kr mangalam university sohna,86.27
172,ashoka international school,dps international school,86.27
173,skyjumper trampoline park,skyjumper trampoline park gurgaon,86.21
174,sector 55/56 metro station,sector 55 56 rapid metro station,86.21
175,sector 55/56 metro station,rapid metro station sector 55 56,86.21
176,sector 55 metro station,sector 42 43 metro station,85.71
177,sector 55 56 metro,rapid metro sector 55 56,85.71
178,sector 42 43 rapid metro,sector 42 43 rapid metro station,85.71
179,euro international school,dps international school,85.71
180,golf course road,golf corse ext road,85.71
181,heritage xperiential learning school,heritage international xperiential school,85.71
182,mamta hospital,kamal hospital,85.71
183,nh48,nh8,85.71
184,sector 55 56 metro,sector 55 56 rapid metro,85.71
185,narayana e techno school manesar,narayana e techno school,85.71
186,sector 55 56 rapid metro station,rapid metro sector 55 56,85.71
187,sector 55 56 rapid metro station,sector 55 56 rapid metro,85.71
188,park hospital,paras hospitals,85.71
189,nh 248 a,nh 248,85.71
190,sector 55 56 rapid metro,rapid metro station sector 55 56,85.71
191,umkal hospital,kamal hospital,85.71
192,rapid metro sector 55 56,rapid metro station sector 55 56,85.71
193,ananta hospital,aman hospital,85.71
194,aryan hospital,aarvy hospital,85.71
195,nh 248a,nh 148a,85.71
196,holiday inn gurugram sector 90,holiday inn express gurugram sector 50,85.29
197,badshahpur sohna road highway,badshahpur sohna road highway sector 68,85.29
198,badshahpur sohna road highway sector 48,badshahpur sohna road highway,85.29
199,dps international school,broadways international school,85.19
200,kings international school,lancers international school,85.19
201,street xavier's school,street xavier high school,85.11
202,cd international school,s n international school,85.11
203,rps international school,cd international school,85.11
204,cbr cricket ground,bamroli cricket ground,85.00
205,lions public school,diamond public school,85.00

In [11]:
import re
import pandas as pd


# Function to extract numbers from a location name
def extract_numbers(text):
    return re.findall(r'\d+', text)


# Function to classify similar pairs
def classify_pair(row):
    
    col1 = row['column_1']
    col2 = row['column_2']
    similarity = row['similarity']
    
    # Extract numbers
    numbers_1 = extract_numbers(col1)
    numbers_2 = extract_numbers(col2)
    
    
    # RULE 1:
    # If both names contain numbers and the numbers are different,
    # they should NOT be automatically merged
    if numbers_1 and numbers_2:
        if set(numbers_1) != set(numbers_2):
            return "REJECT - Different numbers"
    
    
    # RULE 2:
    # Very high similarity
    if similarity >= 95:
        return "LIKELY SAME"
    
    
    # RULE 3:
    # High similarity but requires checking
    elif similarity >= 88:
        return "MANUAL REVIEW"
    
    
    # RULE 4:
    # Lower similarity
    else:
        return "LOW CONFIDENCE"


# Create a copy so original dataframe remains unchanged
review_df = similar_columns_df.copy()


# Apply classification
review_df['classification'] = review_df.apply(
    classify_pair,
    axis=1
)


# Show number of pairs in each category
print("Classification summary:\n")

print(
    review_df['classification']
    .value_counts()
)


# Display likely same locations
likely_same_df = review_df[
    review_df['classification'] == 'LIKELY SAME'
]

print("\n\nLIKELY SAME LOCATIONS:\n")

display(likely_same_df)


# Display manual review pairs
manual_review_df = review_df[
    review_df['classification'] == 'MANUAL REVIEW'
]

print("\n\nMANUAL REVIEW:\n")

display(manual_review_df)

Classification summary:

classification
LOW CONFIDENCE                66
MANUAL REVIEW                 63
REJECT - Different numbers    52
LIKELY SAME                   25
Name: count, dtype: int64


LIKELY SAME LOCATIONS:

,column_1,column_2,similarity,classification
0,vivanta dwarka new delhi,vivanta new delhi dwarka,100.00,LIKELY SAME
1,gurgaon delhi expressway,delhi gurgaon expressway,100.00,LIKELY SAME
2,sector 55 56 rapid metro station,rapid metro station sector 55 56,100.00,LIKELY SAME
3,rapid metro sector 55 56,sector 55 56 rapid metro,100.00,LIKELY SAME
4,tau devilal sports complex,tau devi lal sports complex,98.11,LIKELY SAME
5,badshahpur sohna highway,badshapur sohna highway,97.87,LIKELY SAME
6,delhi ajmer expressway,delh ajmer expressway,97.67,LIKELY SAME
7,proposed metro station,propose metro station,97.67,LIKELY SAME
8,the millenium school,the millennium school,97.56,LIKELY SAME
9,golf course ext road,golf course extn road,97.56,LIKELY SAME
11,golf course ext road,golf corse ext road,97.44,LIKELY SAME
13,dwarka expressway,dwaraka expressway,97.14,LIKELY SAME
14,paras hospital,paras hospitals,96.55,LIKELY SAME
15,ektaa hospitals,ektaa hospital,96.55,LIKELY SAME
16,rions hospital,rion's hospital,96.55,LIKELY SAME
17,aarvy hospital,arvy hospital,96.30,LIKELY SAME
18,street xavier's high school,street xavier high school,96.15,LIKELY SAME
19,sector 55 56 metro station,sector 55/56 metro station,96.15,LIKELY SAME
20,sector 53 54 metro station,sector 53/54 metro station,96.15,LIKELY SAME
21,holiday inn express gurugram sector 50,holiday inn express gurugram sec 50,95.89,LIKELY SAME
23,igi airport,igia airport,95.65,LIKELY SAME
25,euro international school sec 51,euro international school sector 51,95.52,LIKELY SAME
26,euro international school sec 84,euro international school sector 84,95.52,LIKELY SAME
29,golf corse ext road,golf course extn road,95.00,LIKELY SAME
30,pvr drive in theatre,pvr drive in theater,95.00,LIKELY SAME

MANUAL REVIEW:

,column_1,column_2,similarity,classification
31,aapnoghar,aapno ghar,94.74,MANUAL REVIEW
32,the signature super speciality hospital,signature super speciality hospital,94.59,MANUAL REVIEW
34,country inn & suites by radisson,country inn and suites by radisson,93.94,MANUAL REVIEW
35,vardaan hospital and trauma centre,vardaan hospital & trauma centre,93.94,MANUAL REVIEW
42,artimis hospital,artemis hospital,93.75,MANUAL REVIEW
43,huda city centre,huda city center,93.75,MANUAL REVIEW
46,cd international school,dps international school,93.62,MANUAL REVIEW
47,southern peripheral road,southern periphery road,93.62,MANUAL REVIEW
49,nh 248a,nh 248 a,93.33,MANUAL REVIEW
51,gd goenka world school,g d goenka world school,93.33,MANUAL REVIEW
52,kr mangalam university,k r mangalam university,93.33,MANUAL REVIEW
53,basai dhankot railway station,basai dhancourt railway station,93.33,MANUAL REVIEW
54,international airport,ig international airport,93.33,MANUAL REVIEW
55,omaxe city centre mall,omex city centre mall,93.02,MANUAL REVIEW
60,g d goenka university,gd goenka university,92.68,MANUAL REVIEW
61,nh 248a,nh 248,92.31,MANUAL REVIEW
63,amma hospital,aman hospital,92.31,MANUAL REVIEW
65,scottish high international school,scottish international school,92.06,MANUAL REVIEW
66,gurgaon railway station,gurgaon old railway station,92.00,MANUAL REVIEW
67,kings international school,s n international school,92.00,MANUAL REVIEW
68,sanjivani hospital,sanjeevani hospital,91.89,MANUAL REVIEW
70,rps international school,s n international school,91.67,MANUAL REVIEW
74,rbsm public school,rhm public school,91.43,MANUAL REVIEW
75,indira gandhi int airport,indira gandhi airport,91.30,MANUAL REVIEW
79,badshahpur sohna highway,badshahpur sohna road highway,90.57,MANUAL REVIEW
80,delhi international airport,ig international airport,90.20,MANUAL REVIEW
81,vatika town square inxt,vatika town square inxt mall,90.20,MANUAL REVIEW
82,gaytri public school,garima public school,90.00,MANUAL REVIEW
84,street xavier's high school,street xavier's school,89.80,MANUAL REVIEW
86,gems international school,dps international school,89.80,MANUAL REVIEW
88,sapphire mall,sapphire 93 mall,89.66,MANUAL REVIEW
89,sapphire 83 mall,sapphire mall,89.66,MANUAL REVIEW
90,sector 55 56 metro station,rapid metro station sector 55 56,89.66,MANUAL REVIEW
91,sector 42 43 metro station,sector 42 43 rapid metro station,89.66,MANUAL REVIEW
92,sector 55 56 metro station,sector 55 56 rapid metro station,89.66,MANUAL REVIEW
95,golf course extension road,golf course extension,89.36,MANUAL REVIEW
96,golf course extension road,golf course extn road,89.36,MANUAL REVIEW
97,gurgaon railway station,gurugram railway station,89.36,MANUAL REVIEW
98,lotus valley international school gurgaon,lotus valley international school,89.19,MANUAL REVIEW
99,holiday inn express gurugram,holiday inn express gurugram sec 50,88.89,MANUAL REVIEW
100,euro international school sector 37d,euro international school sector 37d gurugram,88.89,MANUAL REVIEW
101,sneh hospital,sethi hospital,88.89,MANUAL REVIEW
103,park hospital,paras hospital,88.89,MANUAL REVIEW
106,nh 8 delhi jaipur highway,delhi jaipur highway,88.89,MANUAL REVIEW
107,southern peripheral road,southern peripheral road dhani,88.89,MANUAL REVIEW
108,aryan hospital,aman hospital,88.89,MANUAL REVIEW
109,aryan hospital,arvy hospital,88.89,MANUAL REVIEW
110,golf course ext road,golf course road,88.89,MANUAL REVIEW
111,miracles apollo cradle hospital,miracles apollo cradle/spectra hospital,88.57,MANUAL REVIEW
112,miracles apollo cradle hospital,miracles apollo cradle spectra hospital,88.57,MANUAL REVIEW
114,adarsh senior secondary school,jhankar senior secondary school,88.52,MANUAL REVIEW
115,badshahpur sohna road highway,badshapur sohna highway,88.46,MANUAL REVIEW
116,rps international school,lancers international school,88.46,MANUAL REVIEW
120,lancers international school,s n international school,88.46,MANUAL REVIEW
121,gurugram university,iilm university gurugram,88.37,MANUAL REVIEW
122,hyatt regency gurugram,hyatt regency gurgaon,88.37,MANUAL REVIEW
125,dlf world tech park,world tech park,88.24,MANUAL REVIEW
127,arc multi speciality hospital,anand multispeciality hospital,88.14,MANUAL REVIEW
128,rps international school,ompee international school,88.00,MANUAL REVIEW
129,rps international school,kings international school,88.00,MANUAL REVIEW
130,kr mangalam university,kr mangalam university sohna,88.00,MANUAL REVIEW
131,arvy hospital,arc hospital,88.00,MANUAL REVIEW
132,euro international school,gems international school,88.00,MANUAL REVIEW

In [12]:
from collections import defaultdict

# --------------------------------------------------
# STEP 4: CREATE CONFIRMED DUPLICATE PAIRS
# --------------------------------------------------

# Take all LIKELY SAME pairs
confirmed_pairs = []

likely_same = review_df[
    review_df['classification'] == 'LIKELY SAME'
]

for _, row in likely_same.iterrows():
    confirmed_pairs.append(
        (row['column_1'], row['column_2'])
    )


# --------------------------------------------------
# ADD MANUALLY APPROVED PAIRS
# --------------------------------------------------

manual_confirmed_pairs = [

    ('aapnoghar', 'aapno ghar'),

    ('the signature super speciality hospital',
     'signature super speciality hospital'),

    ('country inn & suites by radisson',
     'country inn and suites by radisson'),

    ('vardaan hospital and trauma centre',
     'vardaan hospital & trauma centre'),

    ('artimis hospital', 'artemis hospital'),

    ('huda city centre', 'huda city center'),

    ('nh 248a', 'nh 248 a'),

    ('gd goenka world school',
     'g d goenka world school'),

    ('kr mangalam university',
     'k r mangalam university'),

    ('sanjivani hospital', 'sanjeevani hospital'),

    ('indira gandhi int airport',
     'indira gandhi airport'),

    ('hyatt regency gurugram',
     'hyatt regency gurgaon'),

    ('gurgaon railway station',
     'gurugram railway station'),

    ('golf course extension road',
     'golf course extn road'),

    ('golf course extension road',
     'golf course extension'),

    ('lotus valley international school gurgaon',
     'lotus valley international school'),

    ('holiday inn express gurugram',
     'holiday inn express gurugram sec 50'),

    ('euro international school sector 37d',
     'euro international school sector 37d gurugram'),

    ('badshahpur sohna highway',
     'badshahpur sohna road highway'),

    ('miracles apollo cradle hospital',
     'miracles apollo cradle spectra hospital'),

    ('miracles apollo cradle hospital',
     'miracles apollo cradle/spectra hospital'),

    ('nh 8 delhi jaipur highway',
     'delhi jaipur highway'),

    ('g d goenka university',
     'gd goenka university')
]


# Add manual pairs
confirmed_pairs.extend(manual_confirmed_pairs)


# --------------------------------------------------
# CREATE CONNECTED DUPLICATE GROUPS
# --------------------------------------------------

graph = defaultdict(set)

for col1, col2 in confirmed_pairs:
    graph[col1].add(col2)
    graph[col2].add(col1)


# Find connected components
visited = set()
duplicate_groups = []

for node in graph:

    if node not in visited:

        stack = [node]
        group = []

        while stack:

            current = stack.pop()

            if current not in visited:

                visited.add(current)
                group.append(current)

                for neighbor in graph[current]:

                    if neighbor not in visited:
                        stack.append(neighbor)

        duplicate_groups.append(sorted(group))


# --------------------------------------------------
# PRINT DUPLICATE GROUPS
# --------------------------------------------------

print("Total duplicate groups:", len(duplicate_groups))

for i, group in enumerate(duplicate_groups, start=1):

    print(f"\nGROUP {i}")

    for column in group:
        print(f"- {column}")

    print("-" * 50)

Total duplicate groups: 41

GROUP 1
- vivanta dwarka new delhi
- vivanta new delhi dwarka
--------------------------------------------------

GROUP 2
- delhi gurgaon expressway
- gurgaon delhi expressway
--------------------------------------------------

GROUP 3
- rapid metro station sector 55 56
- sector 55 56 rapid metro station
--------------------------------------------------

GROUP 4
- rapid metro sector 55 56
- sector 55 56 rapid metro
--------------------------------------------------

GROUP 5
- tau devi lal sports complex
- tau devilal sports complex
--------------------------------------------------

GROUP 6
- badshahpur sohna highway
- badshahpur sohna road highway
- badshapur sohna highway
--------------------------------------------------

GROUP 7
- delh ajmer expressway
- delhi ajmer expressway
--------------------------------------------------

GROUP 8
- propose metro station
- proposed metro station
--------------------------------------------------

GROUP 9
- the millenium school
- the millennium school
--------------------------------------------------

GROUP 10
- golf corse ext road
- golf course ext road
- golf course extension
- golf course extension road
- golf course extn road
--------------------------------------------------

GROUP 11
- dwaraka expressway
- dwarka expressway
--------------------------------------------------

GROUP 12
- paras hospital
- paras hospitals
--------------------------------------------------

GROUP 13
- ektaa hospital
- ektaa hospitals
--------------------------------------------------

GROUP 14
- rion's hospital
- rions hospital
--------------------------------------------------

GROUP 15
- aarvy hospital
- arvy hospital
--------------------------------------------------

GROUP 16
- street xavier high school
- street xavier's high school
--------------------------------------------------

GROUP 17
- sector 55 56 metro station
- sector 55/56 metro station
--------------------------------------------------

GROUP 18
- sector 53 54 metro station
- sector 53/54 metro station
--------------------------------------------------

GROUP 19
- holiday inn express gurugram
- holiday inn express gurugram sec 50
- holiday inn express gurugram sector 50
--------------------------------------------------

GROUP 20
- igi airport
- igia airport
--------------------------------------------------

GROUP 21
- euro international school sec 51
- euro international school sector 51
--------------------------------------------------

GROUP 22
- euro international school sec 84
- euro international school sector 84
--------------------------------------------------

GROUP 23
- pvr drive in theater
- pvr drive in theatre
--------------------------------------------------

GROUP 24
- aapno ghar
- aapnoghar
--------------------------------------------------

GROUP 25
- signature super speciality hospital
- the signature super speciality hospital
--------------------------------------------------

GROUP 26
- country inn & suites by radisson
- country inn and suites by radisson
--------------------------------------------------

GROUP 27
- vardaan hospital & trauma centre
- vardaan hospital and trauma centre
--------------------------------------------------

GROUP 28
- artemis hospital
- artimis hospital
--------------------------------------------------

GROUP 29
- huda city center
- huda city centre
--------------------------------------------------

GROUP 30
- nh 248 a
- nh 248a
--------------------------------------------------

GROUP 31
- g d goenka world school
- gd goenka world school
--------------------------------------------------

GROUP 32
- k r mangalam university
- kr mangalam university
--------------------------------------------------

GROUP 33
- sanjeevani hospital
- sanjivani hospital
--------------------------------------------------

GROUP 34
- indira gandhi airport
- indira gandhi int airport
--------------------------------------------------

GROUP 35
- hyatt regency gurgaon
- hyatt regency gurugram
--------------------------------------------------

GROUP 36
- gurgaon railway station
- gurugram railway station
--------------------------------------------------

GROUP 37
- lotus valley international school
- lotus valley international school gurgaon
--------------------------------------------------

GROUP 38
- euro international school sector 37d
- euro international school sector 37d gurugram
--------------------------------------------------

GROUP 39
- miracles apollo cradle hospital
- miracles apollo cradle spectra hospital
- miracles apollo cradle/spectra hospital
--------------------------------------------------

GROUP 40
- delhi jaipur highway
- nh 8 delhi jaipur highway
--------------------------------------------------

GROUP 41
- g d goenka university
- gd goenka university
--------------------------------------------------

In [13]:
# --------------------------------------------------
# STEP 5: MAP DUPLICATE GROUPS TO ORIGINAL COLUMNS
# AND MERGE THEM
# --------------------------------------------------

# Create a copy so the original dataframe is safe
location_df_cleaned = location_df_normalized.copy()


# --------------------------------------------------
# Function to get all original columns
# belonging to a normalized column name
# --------------------------------------------------

def get_original_columns(normalized_name):
    
    return column_mapping_df[
        column_mapping_df['normalized_column'] == normalized_name
    ]['original_column'].tolist()


# --------------------------------------------------
# Store merge information
# --------------------------------------------------

merge_summary = []


# --------------------------------------------------
# Process each duplicate group
# --------------------------------------------------

for group_number, group in enumerate(duplicate_groups, start=1):
    
    # Get all actual/original column names
    columns_to_merge = []
    
    for normalized_name in group:
        
        original_cols = get_original_columns(normalized_name)
        
        columns_to_merge.extend(original_cols)
    
    
    # Remove duplicates
    columns_to_merge = list(set(columns_to_merge))
    
    
    # Keep only columns that actually exist
    columns_to_merge = [
        col for col in columns_to_merge
        if col in location_df_cleaned.columns
    ]
    
    
    # Skip if fewer than 2 columns exist
    if len(columns_to_merge) < 2:
        continue
    
    
    # --------------------------------------------------
    # Choose a canonical column name
    # Here we use the first normalized name
    # --------------------------------------------------
    
    canonical_name = group[0]
    
    
    # --------------------------------------------------
    # Merge distances
    # Take the minimum available distance
    # --------------------------------------------------
    
    location_df_cleaned[canonical_name] = (
        location_df_cleaned[columns_to_merge]
        .min(axis=1, skipna=True)
    )
    
    
    # --------------------------------------------------
    # Drop old duplicate columns
    # BUT don't drop canonical_name if it already exists
    # --------------------------------------------------
    
    columns_to_drop = [
        col for col in columns_to_merge
        if col != canonical_name
    ]
    
    location_df_cleaned.drop(
        columns=columns_to_drop,
        inplace=True,
        errors='ignore'
    )
    
    
    # Store summary
    merge_summary.append({
        'group': group_number,
        'canonical_name': canonical_name,
        'merged_columns': columns_to_merge,
        'number_of_columns_merged': len(columns_to_merge)
    })


# --------------------------------------------------
# CREATE MERGE SUMMARY DATAFRAME
# --------------------------------------------------

merge_summary_df = pd.DataFrame(merge_summary)


# --------------------------------------------------
# RESULTS
# --------------------------------------------------

print("Original number of columns:",
      location_df_normalized.shape[1])

print("Cleaned number of columns:",
      location_df_cleaned.shape[1])

print("Columns reduced by:",
      location_df_normalized.shape[1]
      - location_df_cleaned.shape[1])


print("\nMerge Summary:\n")

display(
    merge_summary_df[
        ['group',
         'canonical_name',
         'number_of_columns_merged',
         'merged_columns']
    ]
)

Original number of columns: 1071
Cleaned number of columns: 1010
Columns reduced by: 61

Merge Summary:

,group,canonical_name,number_of_columns_merged,merged_columns
0,1,vivanta dwarka new delhi,2,"[Vivanta Dwarka New Delhi, Vivanta New Delhi, ..."
1,2,delhi gurgaon expressway,2,"[Delhi Gurgaon Expressway, Gurgaon - Delhi Expy]"
2,3,rapid metro station sector 55 56,3,"[Rapid Metro Station Sector 55 56, Sector 55-5..."
3,4,rapid metro sector 55 56,2,"[Sector 55-56 Rapid Metro, Rapid Metro Sector ..."
4,5,tau devi lal sports complex,2,"[Tau Devi Lal Sports Complex, Tau DeviLal Spor..."
5,6,badshahpur sohna highway,3,"[Badshahpur Sohna Hwy, Badshapur Sohna Highway..."
6,7,delh ajmer expressway,2,"[Delh-Ajmer Expy, Delhi Ajmer Expressway]"
7,8,propose metro station,2,"[Proposed Metro Station, Propose Metro Station]"
8,9,the millenium school,2,"[The Millennium School, The Millenium School]"
9,10,golf corse ext road,8,"[Golf course extension road, Golf Course Exten..."
10,11,dwaraka expressway,4,"[Dwarka Expressway, Dwarka Expy, Dwarka expres..."
11,12,paras hospital,2,"[Paras Hospitals, Paras Hospital]"
12,13,ektaa hospital,2,"[Ektaa Hospitals, Ektaa Hospital]"
13,14,rion's hospital,2,"[Rion's Hospital, Rions Hospital]"
14,15,aarvy hospital,2,"[Aarvy Hospital, Arvy Hospital]"
15,16,street xavier high school,2,"[St. Xavier's High School, St Xavier High School]"
16,17,sector 55 56 metro station,4,"[Sector 55-56 Metro station, Sector 55-56 Metr..."
17,18,sector 53 54 metro station,2,"[Sector 53-54 Metro Station, Sector 53/54 Metr..."
18,19,holiday inn express gurugram,3,"[Holiday Inn Express Gurugram, Holiday Inn Exp..."
19,20,igi airport,2,"[IGIA Airport, IGI Airport]"
20,21,euro international school sec 51,2,"[Euro Intl School Sec-51, Euro International S..."
21,22,euro international school sec 84,2,"[Euro International School, Sector 84, Euro In..."
22,23,pvr drive in theater,3,"[PVR Drive In Theatre, PVR Drive in Theatre, P..."
23,24,aapno ghar,2,"[AapnoGhar, Aapno Ghar]"
24,25,signature super speciality hospital,2,"[The Signature Super Speciality Hospital, Sign..."
25,26,country inn & suites by radisson,3,"[Country Inn and Suites by Radisson, Country I..."
26,27,vardaan hospital & trauma centre,3,"[Vardaan hospital and trauma centre, Vardaan H..."
27,28,artemis hospital,2,"[Artemis Hospital, Artimis hospital]"
28,29,huda city center,2,"[Huda city center, Huda City Centre]"
29,30,nh 248 a,2,"[NH 248A, NH 248 A]"
30,31,g d goenka world school,2,"[G D Goenka World School, GD Goenka World School]"
31,32,k r mangalam university,3,"[K. R. Mangalam University, KR Mangalam Univer..."
32,33,sanjeevani hospital,2,"[Sanjeevani Hospital, Sanjivani Hospital]"
33,34,indira gandhi airport,2,"[Indira Gandhi Int. Airport, Indira Gandhi Air..."
34,35,hyatt regency gurgaon,2,"[Hyatt Regency Gurgaon, Hyatt Regency Gurugram]"
35,36,gurgaon railway station,3,"[Gurugram Railway Station, Gurgaon railway sta..."
36,37,lotus valley international school,2,"[Lotus Valley International School, Lotus Vall..."
37,38,euro international school sector 37d,2,"[Euro Intl School, Sector 37D, Gurugram, Euro ..."
38,39,miracles apollo cradle hospital,3,"[Miracles Apollo Cradle Hospital, Miracles Apo..."
39,40,delhi jaipur highway,2,"[Delhi Jaipur Highway, NH-8 Delhi Jaipur Highway]"
40,41,g d goenka university,3,"[Gd goenka university, G D Goenka University, ..."

In [17]:
location_df_cleaned.columns.tolist()

['PropertyName',
 'Bajghera Road',
 'Palam Vihar Halt',
 'DPSG Palam Vihar',
 'Park Hospital',
 'The NorthCap University',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Dwarka Sector 21, Metro Station',
 'Pacific D21 Mall',
 'Indira Gandhi International Airport',
 'Hamoni Golf Camp',
 'Fun N Food Waterpark',
 'Accenture DDC5',
 'DPSG Palam Vihar Gurugram',
 'Park Hospital, Palam Vihar',
 'Palam Vihar Halt Railway Station',
 'Dwarka Sector 21 Metro Station',
 'Fun N Food Water Park',
 'Hyatt Place',
 'Altrade Business Centre',
 'AIPL Business Club Sector 62',
 'Heritage Xperiential Learning School',
 'CK Birla Hospital',
 'Paras Trinity Mall Sector 63',
 'Rapid Metro Station Sector 56',
 'De Adventure Park',
 'DoubleTree by Hilton Hotel Gurgaon',
 'KIIT College of Engineering Sohna Road',
 'Mehrauli-Gurgaon Road',
 'Nirvana Rd',
 'TERI Golf Course',
 'The Shikshiyan School',
 'WTC Plaza',
 'Luxus Haritma Resort',
 'BSF Golf Course',
 'Gurgaon',
 'Dwarka Sector 21',
 'Nehru Stadium',
 'Fun N Food WaterPark',
 'Vasant Kunj',
 'Pranavananda Int. School',
 'DLF Site central office',
 'Holiday Inn Gurugram Sector 90',
 'Krishna Hospital',
 'Royal Institute Of Science',
 'Sapphire 83 Mall',
 'NH48',
 'Garhi Harsaru Junction',
 'Manesar Golf Course',
 'Vega Schools NH-8',
 'DLF Corporate Greens',
 'NH 48',
 'Golden Greens Golf & Resorts Limited',
 'Mount Olympus Junior School',
 'Miracles Apollo Hospital',
 'NH -8',
 'Savoy Suites, Manesar',
 'Golden Greens Golf & Resorts',
 'IMT Manesar',
 'Amity University Gurugram',
 'Dwarka Expy, Sector 109',
 'Euro International School, Sector- 109',
 'Jai Sai Ram Hospital',
 'Aryan Hospital',
 'Idea Cosmic Plaza',
 'Indira Gandhi Intl Airport',
 'Royal Institute Of Science & Management',
 'Pataudi Road',
 'Holiday Inn Sector 90',
 'RPS International School',
 'Aarvy Healthcare Hospital',
 'Iris Broadway Mall',
 'Imperia Mindspace',
 'AIPL Business Tower',
 'Heritage School',
 'Gurugram University',
 'Omaxe Gurgaon Mall',
 'Sushant University',
 'Badshahpur Sohna Rd Hwy,Sector 48',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'National Highway  48',
 'Vatika Town Square-INXT',
 'Ompee International School',
 'Manesar Bus Stand',
 'Yashlok Medical Centre',
 'Euro International School',
 'WorldMark Gurgaon',
 'Capital Cyberscape',
 'The Shriram Millennium School',
 'DoubleTree by Hilton Hotel',
 'Nakhrola Stadium',
 'Delhi - Jaipur Expressway',
 'Vatika Town Square-INXT Mall',
 'Savoy Suites',
 'Bal Bharati Public School',
 'Vatika Business Centre',
 'Miracles Apollo Cradle',
 'Ambience Mall New',
 'NH8',
 'Delhi Public School',
 'Elan Miracle Mall',
 'Agri Business Management Collage',
 'Delhi Jaipur Expressway',
 'Grand Hyatt Gurgaon',
 'Duke Horse Riding Club',
 'PVR Drive In Cinema',
 'W Pratiksha Hospital',
 'Metro World Mall',
 'Unicosmos School',
 'Faridabad Gurgaon Road',
 'Sohna Road',
 'Bestech Business Tower',
 'Appu Ghar',
 'SkyJumper Trampoline Park',
 'Axis Bank',
 'KMP Expressway',
 'Karma Lakelands',
 'Jungle Safari & Trails',
 'DPS Manesar',
 'Medanta Hospital',
 'Faridabad - Gurgaon Road',
 "Lingaya's Lalita Devi Institute",
 'ASF Insignia SEZ',
 'Banjara Market Gurugram',
 'Central Plaza Mall',
 'Paras Hospitals, Gurgaon',
 'Vega School',
 'Indian School of Hospitality',
 'Vatika City Centre',
 'Aatish Hospital',
 'Info Technology Park Phase 2',
 'Huda Metro Station',
 'Southern Peripheral Rd',
 'Global Ways School',
 'Radisson Hotel',
 'Mavens Inn',
 'Sanar International Hospital',
 'IILM University, Gurugram',
 'The Banyan Tree World School',
 'The Big Tree Cafe',
 'DLF Golf and Country Club',
 'Delhi Public School, Sector 84',
 'DPG Degree College',
 'Shivani public school',
 'Baghera University',
 'Kutumbh Hospital',
 'Bijwasan Railway Station',
 'Global Foyer Mall',
 'Phase 2 Metro Station',
 'Gurgaon Dreamz Mall',
 'Metro Hospital, Palam Vihar',
 'Infinity Business Park',
 'Huda metro station',
 'Euro International School, Sector- 109.',
 'Heritage Xperiential Learning, CRPF Rd',
 'Sector 54 Chowk Metro Station',
 'Genesis Hospital Sector 84',
 'DPGITM Engineering College Sector 34',
 'Sapphire 83 Mall Sector 83',
 'Holiday Inn Hotel Sector 90',
 'SkyJumper Trampoline Park Gurgaon',
 'National Tennis Academy Sector 98',
 'Nouveau Medics Multispeciality OPD',
 'Heritage Village Resort & Spa',
 'Sector 86 Road',
 'Genesis Hospital',
 'DPG Institute of Technology',
 'Medanta -The Medicity',
 'Airia Mall',
 'Amma Hospital',
 'DPS International Edge',
 'Eros City Square',
 'Splendor Trade Tower',
 'Narayana Junior College',
 'Sector 55 Metro Station',
 'Dharampur Main Road',
 "Oyster's Water Park",
 'DLF Corporate Park',
 'Smart View Hotel and Resort',
 'Central Park Flower Valley',
 'Shopping complex',
 'Delhi Public School Sector 84',
 'Central Peripheral Road',
 'Nakhrola Stadium Sector 81A',
 'NH 08',
 'Imt Manesar',
 'Fly India Adventure Resort',
 'Vardaan Hospital',
 'IMT Office Sohna',
 'JMS Marine Square Mall',
 'Vibrant Hospital',
 'Prime Scholars Int. School',
 'Ramgarh Farms & Resort',
 'Basai Road',
 'Shree Krishna Hospital',
 'The Esplanade Mall',
 'GEMS International School',
 'Pranavananda International School',
 'Greenway Hospital',
 'National Tennis Academy',
 'NH-8',
 'Paras Trinity Mall',
 'Rajesh Pilot Road',
 'Scottish High International School',
 'KIIT College of Engineering',
 'The Vivekananda School',
 'Southern Peripheral Road',
 'Early Basket Grocery shop',
 'Aradhya Cricket Club Gurgaon',
 'Imperial Heritage School',
 'Daultabad Village Park',
 'Skylark Cricket Academy',
 'Yashroop Hospital',
 'Gurgaon Old Railway Station',
 "Domino's Pizza",
 'Conscient One Mall',
 'Emerald Plaza Shopping Mall',
 'Pawlywoof - Dog Park',
 'SCC Drive-In Cinema',
 'Lemon Tree Hotel, Sohna Road',
 'Shiksha Bharti Public School',
 'Sahara Mall',
 'Dhanwapur Road',
 'Govt. PG College',
 'Basai Dhankot',
 'Park Inn',
 'IFFCO Chowk Metro Station',
 'The Executive Centre',
 'Dwarka Expy, Sector 88',
 'Euro Int School, Sector 37D, Gurugram',
 'Reliance Trends Newtown Square Mall',
 'SGT University',
 'Medanta-The Medicity',
 'SGT Hospital 1',
 'Suncity School',
 'Green Field School',
 'Narayana E Techno',
 'Alpine Convent School',
 'Little E Step –Pre School',
 'Sheetla Mata Mandir',
 'Captain Chandan Lal Marg',
 'CD International School',
 'Raheja Mall',
 'Basai Dhankot Railway Station',
 'First Step Play School',
 'Sri Ma Montessori International',
 'Ansal Plaza',
 'Delhi International Airport',
 'KMP Corridor',
 'Vega Schools Sector 48',
 'Cloudnine Hospital Sector 47',
 'City Hospital',
 'NH 352W, Pataudi',
 'Pathfinder Global School, Pataudi',
 'Vistar Complex',
 'BML Munjal University (BMU)',
 'Bestech Central Square Mall',
 'ORCHIDS The International School',
 'Marengo Asia Hospitals',
 'Sector 42-43 Rapid Metro',
 'Sector 53-54 Rapid Metro',
 'Bank Of Baroda',
 'HDFC Bank ATM',
 'Muincipal Corporation of Gurugram',
 'One Horizon Center Bus Stop',
 'Shalom Hills International School',
 'Satyam Medicare Hospital',
 'Anand Preschool',
 'Choice pharmacy',
 'Qutub Plaza',
 'Sunset point',
 'EPF Regional Office',
 'IFFCO Chowk',
 'Kingdom of Dreams',
 'Gaytri Public School',
 'KIIT College',
 'SPM Hospital',
 'Sealdah Railway Station',
 'International Airport',
 'Lemon Tree Hotel',
 'CK Birla Hospital, Gurgaon',
 'Golf Pavilion',
 'Golf Course Road',
 'Ardee Mall',
 'Shiv Nadar School',
 'NH 148A',
 'Ambience Public School',
 'Heritage Intl Xperiential School',
 'Summer Fields School',
 'Primamed Super Speciality Hospital',
 'Uma Sanjeevani Health Centre',
 'Anya Gurgaon',
 'Hotel Golf View Suites',
 'Apollo Pharmacy',
 'Rx Pharmacy',
 'Sector 42/43 Bus Stand',
 'Genpact Chowk Bus Stop',
 'Huda City Centre Metro Station',
 'Sector 53 Metro Station',
 'ICICI Bank ATM',
 'Bharat Petroleum Retail Outlet',
 'DLF Linear Park',
 'Le Meridien Gurgaon',
 'Sector 42-43 Metro Station',
 'Faridabad - Gurgaon Rd',
 'Ambience Mall',
 'Fun N Food Village',
 'F9 Go Karting Gurgaon',
 'Proposed Metro corridor',
 'N.H-8',
 'Shiskshantar',
 'DPS',
 'Amity',
 'Pathways',
 'GD Goenka',
 'Medicity',
 'Artemis',
 'Max, Fortis',
 'Apollo',
 'Paras Trinity Shopping Mall',
 'Swastik Multispeciality Hospital',
 'AIPL Business Co Working Space',
 'Lemon Tree Hotel Sector 60',
 'MKD Hospital',
 'Sant Soordas Sihi Metro Station',
 'De Adventure Amusement Park',
 'Vatika Business Park Sector 49',
 'Suncity School, Sector 37D',
 'The Signature Advanced Super Speciality',
 'Gurugram University Kankrola',
 'Candor TechSpace, Sector 48',
 'IndusInd Bank ATM',
 "Cherub's Cradle",
 'Mavens Orange - Hotel',
 'Learning Stars School',
 'State Bank of India',
 'Deerika HyperMart',
 'Triangular Park',
 'Sector 45 SO Post Office',
 'FUEL NATION',
 'HSBC',
 'Women Police Station',
 'Best IVF Centre',
 'Gurugram Public School',
 'Shikshantar - Primary School',
 'Mamta Hospital',
 'IG International Airport',
 'Omaxe City Centre',
 'DLF Grand Mall',
 'Matrikiran School',
 'DLF Cyber City',
 'Vatika Town Square',
 'Global city centre',
 'Sohna road dhunela',
 'Maharana pratap school',
 'Sector 55-56 metro',
 'Garhi harsaru railway station Gurgaon',
 'HUB 66',
 'Sealdah',
 'Hasanpur',
 'The Oberoi',
 'Euro Intl School, Sector- 109',
 'Najafgarh Kapashera Road',
 'Dwarka Sector 21 Metro station',
 'Hong Kong Bazaar',
 'Bharti International Convent School',
 'Badshahpur Sohna Rd Hwy, Sector 68',
 'Ashoka International School',
 'The Oberoi Gurgaon',
 'GD Goenka Public School',
 'Chauma Road',
 'Chirag Hospital',
 'Sector-21 Metro Dwarka',
 'AIPL Joy Street Mall',
 'Radisson Hotel Sohna Road',
 'iON Digital Zone (Gurugram)',
 'HUDA Mini Golf Course',
 'IMT Road',
 'National Highway 48',
 'Sohna Gurgaon Road',
 'Spaze Itech Park',
 'Pallavan PreSchool, Sohna Road',
 'Radisson Hotel Gurugram Sohna Road',
 'Polaris Hospital',
 'RBSM Public school',
 'Health Care Pharmacy',
 'Sector 54 Chowk',
 'EuroKids Preschool Suncity',
 'YES Bank ATM',
 'Suncity School Gurgaon',
 'Suncity Shopping Complex',
 'Vallores Pre School',
 'Umkal Hospital',
 'Haryana City Gas',
 'Marigold Secondary School',
 'Alpine Hospital',
 'Pushpanjali Hospital',
 'Country Inn',
 'Westin',
 'Rajiv Chowk - Sohna Highway',
 'KMP corridor',
 'Central Park Resorts',
 'Swastik Hospital Sec 66',
 'Adarsh Senior Secondary School',
 'International Tech Park Gurgaon,',
 'Sector 55-56 Metro',
 'Surajgarh Gurgaon, Golf Course Ext Rd',
 'Ananta Hospital',
 'Indus World School',
 'National Highway-48',
 'Prime Scholars International School',
 'Dwarka Expy, Dhanwapur Village',
 'Shri Balaji’s Multispeciality Hospital',
 'Delhi Public School, Sector 103',
 'Park Inn, Gurgaon',
 'DLF World Tech Park',
 'Star Mall',
 'The Hive Shopping Mall',
 'NH-8, IMT Manesar',
 'Yaduvanshi Shiksha Niketan',
 'Royal Institute Of Science and Mgt',
 'Newtown Square Mall',
 'NH 352W',
 'Eros Corporate Park',
 'Manesar Road',
 'Huda Metro Station (Gurugram)',
 'InfinityS Badminton Academy',
 'Sanskar Bharti Public School',
 'Manipal Hospital, Gurugram',
 'HUDA Market, Sector 14',
 'SCC Rooftop Drive-In',
 'The Oberoi, Gurgaon',
 'Kings International School',
 'HUDA Market',
 'Basai Metro Station',
 'CBR Cricket Ground',
 'Kunskapsskolan School',
 'Omaxe Celebration Mall',
 'Gurgaon - Delhi Expy, Sector 75A',
 'International Tech Park Gurgaon',
 'Shalom Presidency School',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Pataudi Rd, Sector 95B',
 'RELIANCE TRENDS Newtown Square Mall',
 'Aarvy Healthcare Super Speciality',
 'Approved Sector 37 Mero Station',
 'Signature Hospital',
 'Xavier’s International',
 'Alpine School',
 'Esplanade Mall',
 'Sector 10 Market',
 'Blue Bells Public School',
 'infinity Business Park',
 'Medanta The Medicity',
 'Galleria 108 Mall',
 'Manipal Hospital',
 'Bharat Ram Global School',
 'Canara Bank ATM',
 'Yes Bank',
 'Arc Hospital',
 'Canara Bank',
 'Axis Bank ATM',
 'City Square',
 'Shishu Kalyan School',
 'Rathore IMT Hospital',
 'DSD College',
 'Patil Station',
 'Amity University',
 'ICFAI University',
 'Sapphire 83',
 'Cambridge Montessori',
 'Hyatt Regency',
 'Rao Bharat Singh International School',
 'Aarvy Healthcare',
 'NH-8, Imt Manesar',
 'Cambridge College Of Education',
 'Iffco Chowk',
 'Dharampeth Main Road',
 'Dwarka sector 21 metro station',
 'Old Delhi Gurgaon Road',
 'Rotary Public School',
 'Candor Techspace',
 'Manipal Hospital, Palam Vihar',
 'Moulsari Avenue',
 'Adarsh public school,Garhi Harsaru',
 'PHC Garhi Harsaru',
 'Excellere World School',
 'Aman Hospital & Surgical Centre',
 'Neemrana Palace',
 'Global City Centre',
 'Vishwas Hospital',
 'Ibis Hotel',
 'Horizon 1 Mall',
 'Sector 42-43 Metro station',
 'Ernst & Young',
 'Gurgaon Faridabad Highway',
 'Mount Olympus School, Sec 79',
 'Singhania University, Manesar',
 'Capital Business Park',
 'Old Sohna Dhani Road',
 'GD Goenka Signature School',
 'Public Bazar',
 'GD Goenka School',
 'Vatika Business Park',
 'Bharat Petrol Pump',
 'IndusInd Bank',
 'Children Park',
 'Medanta Dialysis Center',
 'Central Park, Sohna Rd',
 'HDFC Bank ATM, Dhunela Ghamroj',
 'Ashiana Anmol  Kid Centric Homes',
 'Indianoil, Sohna - Gurgaon Rd',
 'Taj Hotel & Family Restaurant',
 'V-Square Sohna New Residential',
 'The Phoenix Project, Sohna - Gurgaon Rd',
 'Signature Global Park',
 'Signum 36',
 'Kotak Mahindra Bank, MBS Tower',
 'Pasco Automobiles, Alipur, Sohna',
 'Sohna Bus Stand',
 'Imperio School',
 'Vipul Trade Business Centre',
 'Radisson Hotel Gurugram',
 'Airia Mall Sector 68',
 'Damdama More',
 'Civil Hospital',
 'Western Peripheral Expressway',
 'Bhondsi Nature Park',
 'Enkays Hospital',
 'Lemon Tree Hotel,',
 'Ram Krishna Public School',
 'Aravalli Hill View Point',
 'Gurugram Global Heights School',
 'Satya The Hive Mall',
 'Gurugram Road',
 'Sunrise University',
 'Yonex Badminton Stadium',
 'Grand Hyatt',
 'Au Grand Air',
 'Indira Gandhi Eye Hospital',
 'Double Tree by Hilton',
 'Swastik Hospital',
 'Jinaglala Theme Park',
 'Scottish International School',
 'Ap Sports cricket ground',
 'Nischay Cricket Academy',
 'DLC Cricket Ground',
 'Drona Sports Village',
 'Ramada by Wyndham Gurgaon',
 'Mehrauli-Gurgaon Rd',
 'Surajgarh Gurgaon',
 'Apex Plus Hospital',
 'ZEN Golf Range & Academy',
 'The Banyan Tree Hiking Area',
 'MG Road',
 'Plaza Mall',
 'MGF Metropolitan Mall',
 'Lancers International School',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Signature Global Infinity Mall Sohna',
 'Vidya Niketan Sr Sec School',
 'Spectra Hospital',
 'Tulip Violet Society, Sector 69',
 'Spaze Palazo, Golf Course Ext Rd',
 'Federal Bank Sector 71',
 'Kunskapsskolan International',
 'Southern Peripheral Rd, Gurugram',
 'Ektaa Hospitals  Main Sohna Rd',
 'Central Bank Of India Sohna Rd',
 'Sanjeevani Hospital - Child Specialist',
 'VATIKA BUSINESS PARK Sohna Rd',
 'IndianOil, Hasanpur',
 'The Medicity, Spaze iTech Park',
 'Axis Bank, Sohna Rd',
 'Shambhu Dayal High School',
 'Global City Centre Mall',
 'Ascendas OneHub Gurgaon',
 'IRIS Broadway Mall',
 'Flying Wings Badminton Academy',
 'Saraswati Model School',
 'Orchid Business Park',
 'Farrukh Nagar Railway Station',
 'Medanta - The Medicity',
 'M3m 65th Avenue Mall',
 'DPS International School',
 'Rapid Metro Sector 56',
 'Sneh Hospital',
 'Gems International School',
 'National Highway 8',
 'Appu Ghar Water Park',
 'Tennis Vidyalaya (Tennis Academy)',
 'Zooper India Trampoline Park',
 'Teri Golf Course',
 'Park Dr, DLF Phase 5',
 'Heritage badminton academy',
 'Green Field Public School',
 'Kadipur Industrial Area',
 'Spazedge IT Park',
 'JMD Megapolis',
 'Sapphire Mall',
 'More Hypermart , Vipul business park',
 'Basant Valley Global School',
 'The Paras World School',
 'Vipul Trade Centre',
 'WorldMark Gurgaon, Maidawas Rd',
 'Artemis Hospital Gurgaon',
 'Western Peripheral Expy, Gurugram',
 'Raghunath Bal Vidya Mandir School',
 'ESIC Hospital',
 'S N International School',
 'Infinitys Badminton Academy',
 'Sector 29 Gurgaon Pubs and Bars',
 'Emaar Business Park',
 'Southern Peripheral Rd, Dhani',
 'Omaxe City Centre Mall',
 'Badshahpur Sohna Rd Hwy, Malibu Town',
 "St. Xavier's School",
 'American Express',
 'IDFC FIRST Bank',
 'Sector 42-43',
 'Sector 53-54',
 'MGF Megacity Mall',
 'Fortis hospital',
 'Pataudi road',
 'Double Infinity market',
 'Bamroli Cricket Ground',
 'Aman Hospital',
 'Kidzee',
 'Paras Trinity',
 'AIPL Business Club',
 'Narayana e-Techno School - Manesar',
 'HDFC Bank, Pataudi Rd',
 'SS Omnia, Sector 86',
 'Canara Bank - Nawada Fatehpur',
 'ICICI Bank ATM, Sector 86',
 'Silver Streak Multi Speciality',
 'RHM Public School',
 'Minda Industries Nawada Fatehpur',
 'Numberdar market, IMT Manesar',
 "Sodhi's Supermarket, Sector 82",
 'M3M SCO Shop cum Office',
 'Sector 42-43 Rapid Metro Station',
 'Quality Inn Gurgaon',
 'Minda Industries Limited',
 'Central Park II Road',
 'Omex City Centre Mall',
 'Damdama Lake Rd',
 'Sohna Hill Viewpoint',
 'KR Mangalam University Sohna',
 'Hero Honda Chowk',
 'Jagdish Super Market',
 'Gyaananda School',
 'Bharat Petroleum Shree Shyam Filling',
 'The Club, International City',
 'Conscient One',
 'ICICI BANK ATM, Annapurna MKT',
 'ESIC Dispensary',
 'Canara Bank New Palam Vihar',
 'Dwarka',
 'Radha Krishan Mandir',
 'Daultabad Stadium',
 'Gurgaon Gramin Bank',
 'SCR Model School',
 'Golden Tulip Suites Gurgaon',
 'South point Mall',
 'Pathways School Gurgaon',
 'Kidzee Sec-93',
 'Jhankar Group of Institutions',
 'Heritage Badminton Academy',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka expressway Basai crossing',
 'Sethi Hospital',
 'HDFC Bank',
 'The Sixth Element School',
 'K.R.Mangalam World School',
 'Sushil Park',
 'Peer Baba Ki Mazar',
 'Punjab National Bank',
 'CoNexus.Life B35',
 'Medhaam Pre School & Daycare',
 'Moksh Wellness Pvt Ltd.',
 'Marriott Courtyard',
 'World Tech Park',
 'Athena',
 'Bharat Petroleum Petrol Pump',
 'Sanskar Jyoti School',
 'Arc Multi Speciality Hospital',
 'NH-48',
 'Narayana e Techno School',
 'Medeor Hospital, Manesar',
 "Guls' Kitchen",
 'The Nook',
 'Open Tap',
 'Frescos',
 'Subway',
 'BOB ATM',
 'PNB ATM',
 'HDFC bank ATM',
 'YES bank ATM',
 'Citibank ATM',
 'Gurugram Hospital',
 'Govind Hospital',
 'Manish Gallexie 91',
 'Silver Streak Multi Speciality Hospital',
 'Holiday Inn Gurugram',
 'NH-8 IMT Manesar',
 'Airport',
 'Vatika Sector Road',
 'Gurugram University Sector 87',
 'CNG Petrol Pump',
 'Vivek Model School',
 'Dwarka Expressway Link Road',
 "McDonald's India 24 Hours",
 'Garhi Budhera Road',
 'Iris Broadway Gurugram',
 'iGrow Montessori Play School',
 'Matrikiran High School',
 'Badsa AMS Hospital',
 'GlobalHealthcare Multispeciality',
 'Cricket Academy',
 "V'Lante Mall",
 'NH 48 Gurugram',
 'Patli Railway Station',
 'V Club',
 'Fitso Sector 48 Spuddy, Badminton',
 'Golf Course Rd',
 'Bharat Singh fuel company',
 'Basai Enclave Park',
 'CANARA BANK',
 'Bank Of Baroda ATM',
 'The Holy Kingdom Public School',
 'Shiv Mandir',
 'Open gym garden',
 'KFG sports club Parking',
 'ESIC HOSPITAL',
 'Sector 37 Police Station',
 'Alfaa Health Care Hospital',
 'Mall Fifty One',
 'NH 8, Sector 15 Part 2',
 'K.D. Hospital',
 'Gurgaon Road',
 "Saint Paul's School",
 'Indus valley Public School',
 'MDS Public School',
 'Harsaru Village Bus Stop',
 'Health care pharmacy',
 'Jadon Pharmacy',
 'JMS Crosswalk',
 'Essar Petrol Pump',
 'The Heritage Pride Modern School',
 'SS Omnia Mall',
 'Miracles Apollo Cradle / Spectra',
 'Gurgaon Toll',
 'Rajiv Chowk',
 'Lions Public School',
 'M3M Cosmopolitan',
 'M3M International Financial Center (IFC)',
 'Badshahpur Sohna Rd Hwy, Haryana',
 'NH 48, Sector 78',
 'ICICI ATM',
 'Sai Sports Club cricket ground',
 'Silver Streak Hospital',
 'Gurukul Preschool',
 'HP PETROL PUMP Unnamed Rd',
 'INOX Cinema',
 'Nawada Cricket Accadmy',
 'Arc Multi Speciality',
 'Baba Kanala Chowk',
 'Pataudi Rd',
 'Dronacharya College of Engineering',
 'Netaji Subhash Marg',
 'NH 248',
 'Faridabad',
 'Delhi-Mumbai Expressway',
 'IMT Sohna',
 'Kundli Manesar Palwal Expressway',
 'KR Mangalam',
 'SCJ Academy',
 'Taj',
 'Damdama Lake',

In [18]:
from rapidfuzz import fuzz
import pandas as pd
import re

# --------------------------------------------------
# FINAL CHECK FOR POSSIBLE DUPLICATE COLUMNS
# --------------------------------------------------

# Get all remaining column names
columns = location_df_cleaned.columns.tolist()


# --------------------------------------------------
# Function to normalize names again for comparison
# --------------------------------------------------

def normalize_for_check(name):
    
    name = name.lower().strip()
    
    # Replace punctuation with spaces
    name = re.sub(r'[-_.,/&]', ' ', name)
    
    # Remove multiple spaces
    name = re.sub(r'\s+', ' ', name)
    
    return name.strip()


# Normalize remaining column names
normalized_remaining = {
    col: normalize_for_check(col)
    for col in columns
}


# --------------------------------------------------
# Find similar pairs
# --------------------------------------------------

threshold = 75

remaining_similar_pairs = []

for i, col1 in enumerate(columns):
    
    for col2 in columns[i + 1:]:
        
        name1 = normalized_remaining[col1]
        name2 = normalized_remaining[col2]
        
        similarity = fuzz.token_sort_ratio(name1, name2)
        
        if similarity >= threshold:
            
            remaining_similar_pairs.append({
                'column_1': col1,
                'column_2': col2,
                'normalized_1': name1,
                'normalized_2': name2,
                'similarity': round(similarity, 2)
            })


# --------------------------------------------------
# Create results DataFrame
# --------------------------------------------------

final_check_df = pd.DataFrame(remaining_similar_pairs)

# Sort highest similarity first
final_check_df = final_check_df.sort_values(
    by='similarity',
    ascending=False
).reset_index(drop=True)


# --------------------------------------------------
# DISPLAY RESULTS
# --------------------------------------------------

print("Total remaining columns:", len(columns))

print("\nPossible similar pairs found:", len(final_check_df))

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

display(final_check_df)

Total remaining columns: 1010

Possible similar pairs found: 915

,column_1,column_2,normalized_1,normalized_2,similarity
0,Matrikiran High School,MatriKiran High School,matrikiran high school,matrikiran high school,100.00
1,Dwarka Sector 21 Metro station,Dwarka sector 21 metro station,dwarka sector 21 metro station,dwarka sector 21 metro station,100.00
2,Sector 42-43 Metro Station,Sector 42-43 Metro station,sector 42 43 metro station,sector 42 43 metro station,100.00
3,"Delhi Public School, Sector 84",Delhi Public School Sector 84,delhi public school sector 84,delhi public school sector 84,100.00
4,NH 48,NH-48,nh 48,nh 48,100.00
5,Global city centre,Global City Centre,global city centre,global city centre,100.00
6,Sector 55-56 metro,Sector 55-56 Metro,sector 55 56 metro,sector 55 56 metro,100.00
7,HUB 66,Hub 66,hub 66,hub 66,100.00
8,The Oberoi Gurgaon,"The Oberoi, Gurgaon",the oberoi gurgaon,the oberoi gurgaon,100.00
9,"International Tech Park Gurgaon,",International Tech Park Gurgaon,international tech park gurgaon,international tech park gurgaon,100.00
10,Dwarka Sector 21 Metro Station,Dwarka sector 21 metro station,dwarka sector 21 metro station,dwarka sector 21 metro station,100.00
11,National Highway 48,National Highway-48,national highway 48,national highway 48,100.00
12,Dwarka Sector 21 Metro Station,Dwarka Sector 21 Metro station,dwarka sector 21 metro station,dwarka sector 21 metro station,100.00
13,Huda Metro Station,Huda Metro station,huda metro station,huda metro station,100.00
14,Health Care Pharmacy,Health care pharmacy,health care pharmacy,health care pharmacy,100.00
15,Medanta-The Medicity,Medanta The Medicity,medanta the medicity,medanta the medicity,100.00
16,Infinity Business Park,infinity Business Park,infinity business park,infinity business park,100.00
17,Huda metro station,HUDA Metro Station,huda metro station,huda metro station,100.00
18,Huda metro station,Huda Metro station,huda metro station,huda metro station,100.00
19,Medanta -The Medicity,Medanta-The Medicity,medanta the medicity,medanta the medicity,100.00
20,Medanta -The Medicity,Medanta The Medicity,medanta the medicity,medanta the medicity,100.00
21,Lemon Tree Hotel,"Lemon Tree Hotel,",lemon tree hotel,lemon tree hotel,100.00
22,Medanta -The Medicity,Medanta - The Medicity,medanta the medicity,medanta the medicity,100.00
23,GEMS International School,Gems International School,gems international school,gems international school,100.00
24,IFFCO Chowk,Iffco Chowk,iffco chowk,iffco chowk,100.00
25,HDFC Bank ATM,HDFC bank ATM,hdfc bank atm,hdfc bank atm,100.00
26,NH-8,NH 8,nh 8,nh 8,100.00
27,Park Inn,Park inn,park inn,park inn,100.00
28,IFFCO Chowk Metro Station,Iffco Chowk Metro Station,iffco chowk metro station,iffco chowk metro station,100.00
29,KMP Corridor,KMP corridor,kmp corridor,kmp corridor,100.00
30,TERI Golf Course,Teri Golf Course,teri golf course,teri golf course,100.00
31,Reliance Trends Newtown Square Mall,RELIANCE TRENDS Newtown Square Mall,reliance trends newtown square mall,reliance trends newtown square mall,100.00
32,SGT University,SGT UNIVERSITY,sgt university,sgt university,100.00
33,Huda Metro Station,HUDA Metro Station,huda metro station,huda metro station,100.00
34,YES Bank ATM,YES bank ATM,yes bank atm,yes bank atm,100.00
35,NH -8,NH 8,nh 8,nh 8,100.00
36,Faridabad Gurgaon Road,Faridabad - Gurgaon Road,faridabad gurgaon road,faridabad gurgaon road,100.00
37,Pataudi Road,Pataudi road,pataudi road,pataudi road,100.00
38,"Euro International School, Sector- 109","Euro International School, Sector- 109.",euro international school sector 109,euro international school sector 109,100.00
39,Iris Broadway Mall,IRIS Broadway Mall,iris broadway mall,iris broadway mall,100.00
40,Omaxe Gurgaon Mall,OMAXE Gurgaon Mall,omaxe gurgaon mall,omaxe gurgaon mall,100.00
41,Shiv Mandir,shiv Mandir,shiv mandir,shiv mandir,100.00
42,ESIC Hospital,ESIC HOSPITAL,esic hospital,esic hospital,100.00
43,National Highway 48,National Highway 48,national highway 48,national highway 48,100.00
44,Heritage badminton academy,Heritage Badminton Academy,heritage badminton academy,heritage badminton academy,100.00
45,National Highway 48,National Highway-48,national highway 48,national highway 48,100.00
46,HUDA Metro Station,Huda Metro station,huda metro station,huda metro station,100.00
47,"Dwarka Sector 21, Metro Station",Dwarka Sector 21 Metro Station,dwarka sector 21 metro station,dwarka sector 21 metro station,100.00
48,IMT Manesar,Imt Manesar,imt manesar,imt manesar,100.00
49,Delhi - Jaipur Expressway,Delhi Jaipur Expressway,delhi jaipur expressway,delhi jaipur expressway,100.00
50,Fun N Food Waterpark,Fun N Food WaterPark,fun n food waterpark,fun n food waterpark,100.00
51,Medanta-The Medicity,Medanta - The Medicity,medanta the medicity,medanta the medicity,100.00
52,"Dwarka Sector 21, Metro Station",Dwarka Sector 21 Metro station,dwarka sector 21 metro station,dwarka sector 21 metro station,100.00
53,"NH-8, IMT Manesar",NH-8 IMT Manesar,nh 8 imt manesar,nh 8 imt manesar,100.00
54,Huda Metro Station,Huda metro station,huda metro station,huda metro station,100.00
55,"NH-8, Imt Manesar",NH-8 IMT Manesar,nh 8 imt manesar,nh 8 imt manesar,100.00
56,"Dwarka Sector 21, Metro Station",Dwarka sector 21 metro station,dwarka sector 21 metro station,dwarka sector 21 metro station,100.00
57,Canara Bank,CANARA BANK,canara bank,canara bank,100.00
58,"NH-8, IMT Manesar","NH-8, Imt Manesar",nh 8 imt manesar,nh 8 imt manesar,100.00
59,Yes Bank,YES Bank,yes bank,yes bank,100.00
60,Medanta The Medicity,Medanta - The Medicity,medanta the medicity,medanta the medicity,100.00
61,NH -8,NH-8,nh 8,nh 8,100.00
62,InfinityS Badminton Academy,Infinitys Badminton Academy,infinitys badminton academy,infinitys badminton academy,100.00
63,National Highway 48,National Highway 8,national highway 48,national highway 8,97.30
64,National Highway-48,National Highway 8,national highway 48,national highway 8,97.30
65,National Highway 48,National Highway 8,national highway 48,national highway 8,97.30
66,"Badshahpur Sohna Rd Hwy,Sector 48","Badshahpur Sohna Rd Hwy, Sector 68",badshahpur sohna rd hwy sector 48,badshahpur sohna rd hwy sector 68,96.97
67,Sector 55 Metro Station,Sector 53 Metro Station,sector 55 metro station,sector 53 metro station,95.65
68,Southern Peripheral Rd,Southern Peripheral Road,southern peripheral rd,southern peripheral road,95.65
69,Faridabad - Gurgaon Road,Faridabad - Gurgaon Rd,faridabad gurgaon road,faridabad gurgaon rd,95.24
70,Faridabad Gurgaon Road,Faridabad - Gurgaon Rd,faridabad gurgaon road,faridabad gurgaon rd,95.24
71,Rapid Metro Station Sector 56,rapid metro station sector 55 56,rapid metro station sector 56,rapid metro station sector 55 56,95.08
72,Mehrauli-Gurgaon Road,Mehrauli-Gurgaon Rd,mehrauli gurgaon road,mehrauli gurgaon rd,95.00
73,Sector 55 Metro Station,sector 55 56 metro station,sector 55 metro station,sector 55 56 metro station,93.88
74,Sector 55 Metro Station,sector 53 54 metro station,sector 55 metro station,sector 53 54 metro station,93.88
75,Sector 53 Metro Station,sector 53 54 metro station,sector 53 metro station,sector 53 54 metro station,93.88
76,euro international school sec 51,euro international school sec 84,euro international school sec 51,euro international school sec 84,93.75
77,Sapphire 83 Mall,Sapphire 93 Mall,sapphire 83 mall,sapphire 93 mall,93.75
78,CD International School,DPS International School,cd international school,dps international school,93.62
79,Southern Peripheral Road,Southern Periphery Road,southern peripheral road,southern periphery road,93.62
80,International Airport,IG International Airport,international airport,ig international airport,93.33
81,Golf Course Road,Golf Course Rd,golf course road,golf course rd,93.33
82,Rapid Metro Sector 56,rapid metro sector 55 56,rapid metro sector 56,rapid metro sector 55 56,93.33
83,Basai Dhankot Railway Station,Basai Dhancourt Railway Station,basai dhankot railway station,basai dhancourt railway station,93.33
84,Omaxe City Centre Mall,Omex City Centre Mall,omaxe city centre mall,omex city centre mall,93.02
85,Sector 86 Road,Sector 84 Road,sector 86 road,sector 84 road,92.86
86,sector 55 56 metro station,sector 53 54 metro station,sector 55 56 metro station,sector 53 54 metro station,92.31
87,Amma Hospital,Aman Hospital,amma hospital,aman hospital,92.31
88,Scottish High International School,Scottish International School,scottish high international school,scottish international school,92.06
89,Gurgaon Old Railway Station,gurgaon railway station,gurgaon old railway station,gurgaon railway station,92.00
90,Kings International School,S N International School,kings international school,s n international school,92.00
91,Gurugram Road,Gurugram Rd,gurugram road,gurugram rd,91.67
92,"Euro International School, Sector- 109.",euro international school sector 37d,euro international school sector 109,euro international school sector 37d,91.67
93,"Euro International School, Sector- 109",euro international school sector 37d,euro international school sector 109,euro international school sector 37d,91.67
94,RPS International School,S N International School,rps international school,s n international school,91.67
95,Sector 53-54 Rapid Metro,rapid metro sector 55 56,sector 53 54 rapid metro,rapid metro sector 55 56,91.67
96,Delhi Public School Sector 84,"Delhi Public School, Sector 103",delhi public school sector 84,delhi public school sector 103,91.53
97,"Delhi Public School, Sector 84","Delhi Public School, Sector 103",delhi public school sector 84,delhi public school sector 103,91.53
98,RBSM Public school,RHM Public School,rbsm public school,rhm public school,91.43
99,"Euro International School, Sector- 109.",euro international school sec 51,euro international school sector 109,euro international school sec 51,91.18
100,"Euro International School, Sector- 109",euro international school sec 51,euro international school sector 109,euro international school sec 51,91.18
101,Pataudi road,Pataudi Rd,pataudi road,pataudi rd,90.91
102,NH 48,NH 248,nh 48,nh 248,90.91
103,NH-48,NH 248,nh 48,nh 248,90.91
104,Pataudi Road,Pataudi Rd,pataudi road,pataudi rd,90.91
105,BM College of Technology & Mgmt,BM College of Technology,bm college of technology mgmt,bm college of technology,90.57
106,Delhi International Airport,IG International Airport,delhi international airport,ig international airport,90.20
107,Vatika Town Square-INXT,Vatika Town Square-INXT Mall,vatika town square inxt,vatika town square inxt mall,90.20
108,Gaytri Public School,Garima Public School,gaytri public school,garima public school,90.00
109,Sector 53 Metro Station,Sector 42-43 Metro station,sector 53 metro station,sector 42 43 metro station,89.80
110,Sector 53 Metro Station,sector 55 56 metro station,sector 53 metro station,sector 55 56 metro station,89.80
111,GEMS International School,DPS International School,gems international school,dps international school,89.80
112,DPS International School,Gems International School,dps international school,gems international school,89.80
113,Sector 53 Metro Station,Sector 42-43 Metro Station,sector 53 metro station,sector 42 43 metro station,89.80
114,Sector 42-43 Metro station,Sector 42-43 Rapid Metro Station,sector 42 43 metro station,sector 42 43 rapid metro station,89.66
115,Sapphire Mall,Sapphire 93 Mall,sapphire mall,sapphire 93 mall,89.66
116,Sector 42-43 Metro Station,Sector 42-43 Rapid Metro Station,sector 42 43 metro station,sector 42 43 rapid metro station,89.66
117,Sapphire 83 Mall,Sapphire Mall,sapphire 83 mall,sapphire mall,89.66
118,rapid metro station sector 55 56,sector 55 56 metro station,rapid metro station sector 55 56,sector 55 56 metro station,89.66
119,Indira Gandhi Intl Airport,indira gandhi airport,indira gandhi intl airport,indira gandhi airport,89.36
120,Sneh Hospital,Sethi Hospital,sneh hospital,sethi hospital,88.89
121,Damdama Lake Rd,Damdama Lake,damdama lake rd,damdama lake,88.89
122,Park Hospital,paras hospital,park hospital,paras hospital,88.89
123,NH-48,NH 8,nh 48,nh 8,88.89
124,Aryan Hospital,Aman Hospital,aryan hospital,aman hospital,88.89
125,Southern Peripheral Rd,Southern Periphery Road,southern peripheral rd,southern periphery road,88.89
126,NH 08,NH-8,nh 08,nh 8,88.89
127,NH -8,NH 08,nh 8,nh 08,88.89
128,Sohna Road,Sohna Rd,sohna road,sohna rd,88.89
129,Sector 53-54 Rapid Metro,Rapid Metro Sector 56,sector 53 54 rapid metro,rapid metro sector 56,88.89
130,NH 48,NH 8,nh 48,nh 8,88.89
131,NH-8,NH-48,nh 8,nh 48,88.89
132,NH 48,NH-8,nh 48,nh 8,88.89
133,NH 48,NH -8,nh 48,nh 8,88.89
134,NH -8,NH-48,nh 8,nh 48,88.89
135,NH 08,NH 8,nh 08,nh 8,88.89
136,Miracles Apollo Cradle /Spectra Hospital,miracles apollo cradle hospital,miracles apollo cradle spectra hospital,miracles apollo cradle hospital,88.57
137,Rapid Metro Station Sector 56,Sector 42-43 Rapid Metro Station,rapid metro station sector 56,sector 42 43 rapid metro station,88.52
138,Adarsh Senior Secondary School,Jhankar Senior Secondary School,adarsh senior secondary school,jhankar senior secondary school,88.52
139,RPS International School,Lancers International School,rps international school,lancers international school,88.46
140,Sector 42-43 Metro station,sector 53 54 metro station,sector 42 43 metro station,sector 53 54 metro station,88.46
141,Sector 42-43 Metro Station,sector 53 54 metro station,sector 42 43 metro station,sector 53 54 metro station,88.46
142,Lancers International School,S N International School,lancers international school,s n international school,88.46
143,Gurugram University,"IILM University, Gurugram",gurugram university,iilm university gurugram,88.37
144,"Dwarka Expy, Sector 109","Dwarka Expy, Sector 88",dwarka expy sector 109,dwarka expy sector 88,88.37
145,"Euro International School, Sector- 109.",euro international school sec 84,euro international school sector 109,euro international school sec 84,88.24
146,DLF World Tech Park,World Tech Park,dlf world tech park,world tech park,88.24
147,euro international school sec 84,euro international school sector 37d,euro international school sec 84,euro international school sector 37d,88.24
148,euro international school sec 51,euro international school sector 37d,euro international school sec 51,euro international school sector 37d,88.24
149,"Euro International School, Sector- 109",euro international school sec 84,euro international school sector 109,euro international school sec 84,88.24
150,Heritage Xperiential Learning School,Heritage Intl Xperiential School,heritage xperiential learning school,heritage intl xperiential school,88.24
151,Arc Multi Speciality Hospital,Anand Multispeciality Hospital,arc multi speciality hospital,anand multispeciality hospital,88.14
152,Euro International School,Gems International School,euro international school,gems international school,88.00
153,Southern Peripheral Rd,"Southern Peripheral Rd, Dhani",southern peripheral rd,southern peripheral rd dhani,88.00
154,RPS International School,Ompee International School,rps international school,ompee international school,88.00
155,Euro International School,GEMS International School,euro international school,gems international school,88.00
156,RPS International School,Kings International School,rps international school,kings international school,88.00
157,Global city centre,Global City Centre Mall,global city centre,global city centre mall,87.80
158,Global City Centre,Global City Centre Mall,global city centre,global city centre mall,87.80
159,Vatika City Centre,Vatika City Centre Mall,vatika city centre,vatika city centre mall,87.80
160,Vatika Town Square-INXT,Vatika Town Square,vatika town square inxt,vatika town square,87.80
161,Euro International School,euro international school sec 51,euro international school,euro international school sec 51,87.72
162,Euro International School,euro international school sec 84,euro international school,euro international school sec 84,87.72
163,Sector 42-43 Rapid Metro Station,rapid metro station sector 55 56,sector 42 43 rapid metro station,rapid metro station sector 55 56,87.50
164,Bank Of Baroda,Bank Of Baroda ATM,bank of baroda,bank of baroda atm,87.50
165,Euro International School,CD International School,euro international school,cd international school,87.50
166,Holiday Inn Sector 90,Holiday Inn Hotel Sector 90,holiday inn sector 90,holiday inn hotel sector 90,87.50
167,CD International School,Gems International School,cd international school,gems international school,87.50
168,Delhi International Airport,International Airport,delhi international airport,international airport,87.50
169,GEMS International School,CD International School,gems international school,cd international school,87.50
170,The Esplanade Mall,Esplanade Mall,the esplanade mall,esplanade mall,87.50
171,Sector 42-43 Rapid Metro,Sector 53-54 Rapid Metro,sector 42 43 rapid metro,sector 53 54 rapid metro,87.50
172,Miracles Apollo Hospital,miracles apollo cradle hospital,miracles apollo hospital,miracles apollo cradle hospital,87.27
173,Dharampur Main Road,Dharampeth Main Road,dharampur main road,dharampeth main road,87.18
174,JMS Marine Square Mall,JMS Marine Square,jms marine square mall,jms marine square,87.18
175,Omaxe City Centre,Omaxe City Centre Mall,omaxe city centre,omaxe city centre mall,87.18
176,Matrikiran School,Matrikiran High School,matrikiran school,matrikiran high school,87.18
177,Matrikiran School,MatriKiran High School,matrikiran school,matrikiran high school,87.18
178,Silver Streak Multi Speciality,Silver Streak Multi Speciality Hospital,silver streak multi speciality,silver streak multi speciality hospital,86.96
179,Miracles Apollo Cradle / Spectra,Miracles Apollo Cradle /Spectra Hospital,miracles apollo cradle spectra,miracles apollo cradle spectra hospital,86.96
180,IndusInd Bank ATM,IndusInd Bank,indusind bank atm,indusind bank,86.67
181,TERI Golf Course,Golf Course Rd,teri golf course,golf course rd,86.67
182,Ambience Mall New,Ambience Mall,ambience mall new,ambience mall,86.67
183,DoubleTree by Hilton Hotel Gurgaon,DoubleTree by Hilton Hotel,doubletree by hilton hotel gurgaon,doubletree by hilton hotel,86.67
184,Teri Golf Course,Golf Course Rd,teri golf course,golf course rd,86.67
185,Prakash Hospital,paras hospital,prakash hospital,paras hospital,86.67
186,Royal Institute Of Science,Royal Institute Of Science and Mgt,royal institute of science,royal institute of science and mgt,86.67
187,Golden Greens Golf & Resorts Limited,Golden Greens Golf & Resorts,golden greens golf resorts limited,golden greens golf resorts,86.67
188,Polaris Hospital,paras hospital,polaris hospital,paras hospital,86.67
189,Medanta Hospital,Mamta Hospital,medanta hospital,mamta hospital,86.67
190,GD Goenka School,GD Goenka High School,gd goenka school,gd goenka high school,86.49
191,M3M Cosmopolitan,M3M Cosmopolitan Mall,m3m cosmopolitan,m3m cosmopolitan mall,86.49
192,Amity University Gurugram,Gurugram University,amity university gurugram,gurugram university,86.36
193,KR Mangalam University Sohna,k r mangalam university,kr mangalam university sohna,k r mangalam university,86.27
194,Ashoka International School,DPS International School,ashoka international school,dps international school,86.27
195,SkyJumper Trampoline Park,SkyJumper Trampoline Park Gurgaon,skyjumper trampoline park,skyjumper trampoline park gurgaon,86.21
196,Umkal Hospital,Kamal Hospital,umkal hospital,kamal hospital,85.71
197,Narayana e-Techno School - Manesar,Narayana e Techno School,narayana e techno school manesar,narayana e techno school,85.71
198,"Euro International School, Sector- 109.","Euro Intl School, Sector- 109",euro international school sector 109,euro intl school sector 109,85.71
199,Sector 55-56 metro,rapid metro sector 55 56,sector 55 56 metro,rapid metro sector 55 56,85.71
200,Golf Course Road,golf corse ext road,golf course road,golf corse ext road,85.71
201,Sector 55 Metro Station,Sector 42-43 Metro Station,sector 55 metro station,sector 42 43 metro station,85.71

In [25]:
final_check_df.to_csv(
    "final_duplicate_check.csv",
    index=False
)

In [26]:
# --------------------------------------------------
# STEP 6: FIND EXACT DUPLICATES AFTER NORMALIZATION
# --------------------------------------------------

from collections import defaultdict

# Get current columns
columns = location_df_cleaned.columns.tolist()


# Create groups based on normalized names
exact_duplicate_groups = defaultdict(list)

for col in columns:
    
    normalized_name = normalize_for_check(col)
    
    exact_duplicate_groups[normalized_name].append(col)


# Keep only groups having more than 1 column
exact_duplicate_groups = {
    normalized: cols
    for normalized, cols in exact_duplicate_groups.items()
    if len(cols) > 1
}


# Print results
print("Number of exact duplicate groups:",
      len(exact_duplicate_groups))


for normalized_name, cols in exact_duplicate_groups.items():
    
    print(f"\nNORMALIZED NAME: {normalized_name}")
    
    for col in cols:
        print("-", col)
    
    print("-" * 50)

Number of exact duplicate groups: 42

NORMALIZED NAME: dwarka sector 21 metro station
- Dwarka Sector 21, Metro Station
- Dwarka Sector 21 Metro Station
- Dwarka Sector 21 Metro station
- Dwarka sector 21 metro station
--------------------------------------------------

NORMALIZED NAME: fun n food waterpark
- Fun N Food Waterpark
- Fun N Food WaterPark
--------------------------------------------------

NORMALIZED NAME: teri golf course
- TERI Golf Course
- Teri Golf Course
--------------------------------------------------

NORMALIZED NAME: nh 48
- NH 48
- NH-48
--------------------------------------------------

NORMALIZED NAME: nh 8
- NH -8
- NH-8
- NH 8
--------------------------------------------------

NORMALIZED NAME: imt manesar
- IMT Manesar
- Imt Manesar
--------------------------------------------------

NORMALIZED NAME: euro international school sector 109
- Euro International School, Sector- 109
- Euro International School, Sector- 109.
--------------------------------------------------

NORMALIZED NAME: pataudi road
- Pataudi Road
- Pataudi road
--------------------------------------------------

NORMALIZED NAME: iris broadway mall
- Iris Broadway Mall
- IRIS Broadway Mall
--------------------------------------------------

NORMALIZED NAME: omaxe gurgaon mall
- Omaxe Gurgaon Mall
- OMAXE Gurgaon Mall
--------------------------------------------------

NORMALIZED NAME: national highway 48
- National Highway  48
- National Highway 48
- National Highway-48
--------------------------------------------------

NORMALIZED NAME: delhi jaipur expressway
- Delhi - Jaipur Expressway
- Delhi Jaipur Expressway
--------------------------------------------------

NORMALIZED NAME: faridabad gurgaon road
- Faridabad Gurgaon Road
- Faridabad - Gurgaon Road
--------------------------------------------------

NORMALIZED NAME: huda metro station
- Huda Metro Station
- Huda metro station
- HUDA Metro Station
- Huda Metro station
--------------------------------------------------

NORMALIZED NAME: delhi public school sector 84
- Delhi Public School, Sector 84
- Delhi Public School Sector 84
--------------------------------------------------

NORMALIZED NAME: infinity business park
- Infinity Business Park
- infinity Business Park
--------------------------------------------------

NORMALIZED NAME: medanta the medicity
- Medanta -The Medicity
- Medanta-The Medicity
- Medanta The Medicity
- Medanta - The Medicity
--------------------------------------------------

NORMALIZED NAME: gems international school
- GEMS International School
- Gems International School
--------------------------------------------------

NORMALIZED NAME: park inn
- Park Inn
- Park inn
--------------------------------------------------

NORMALIZED NAME: iffco chowk metro station
- IFFCO Chowk Metro Station
- Iffco Chowk Metro Station
--------------------------------------------------

NORMALIZED NAME: reliance trends newtown square mall
- Reliance Trends Newtown Square Mall
- RELIANCE TRENDS Newtown Square Mall
--------------------------------------------------

NORMALIZED NAME: sgt university
- SGT University
- SGT UNIVERSITY
--------------------------------------------------

NORMALIZED NAME: kmp corridor
- KMP Corridor
- KMP corridor
--------------------------------------------------

NORMALIZED NAME: hdfc bank atm
- HDFC Bank ATM
- HDFC bank ATM
--------------------------------------------------

NORMALIZED NAME: iffco chowk
- IFFCO Chowk
- Iffco Chowk
--------------------------------------------------

NORMALIZED NAME: lemon tree hotel
- Lemon Tree Hotel
- Lemon Tree Hotel,
--------------------------------------------------

NORMALIZED NAME: sector 42 43 metro station
- Sector 42-43 Metro Station
- Sector 42-43 Metro station
--------------------------------------------------

NORMALIZED NAME: global city centre
- Global city centre
- Global City Centre
--------------------------------------------------

NORMALIZED NAME: sector 55 56 metro
- Sector 55-56 metro
- Sector 55-56 Metro
--------------------------------------------------

NORMALIZED NAME: hub 66
- HUB 66
- Hub 66
--------------------------------------------------

NORMALIZED NAME: the oberoi gurgaon
- The Oberoi Gurgaon
- The Oberoi, Gurgaon
--------------------------------------------------

NORMALIZED NAME: health care pharmacy
- Health Care Pharmacy
- Health care pharmacy
--------------------------------------------------

NORMALIZED NAME: yes bank atm
- YES Bank ATM
- YES bank ATM
--------------------------------------------------

NORMALIZED NAME: international tech park gurgaon
- International Tech Park Gurgaon,
- International Tech Park Gurgaon
--------------------------------------------------

NORMALIZED NAME: nh 8 imt manesar
- NH-8, IMT Manesar
- NH-8, Imt Manesar
- NH-8 IMT Manesar
--------------------------------------------------

NORMALIZED NAME: infinitys badminton academy
- InfinityS Badminton Academy
- Infinitys Badminton Academy
--------------------------------------------------

NORMALIZED NAME: yes bank
- Yes Bank
- YES Bank
--------------------------------------------------

NORMALIZED NAME: canara bank
- Canara Bank
- CANARA BANK
--------------------------------------------------

NORMALIZED NAME: heritage badminton academy
- Heritage badminton academy
- Heritage Badminton Academy
--------------------------------------------------

NORMALIZED NAME: esic hospital
- ESIC Hospital
- ESIC HOSPITAL
--------------------------------------------------

NORMALIZED NAME: matrikiran high school
- Matrikiran High School
- MatriKiran High School
--------------------------------------------------

NORMALIZED NAME: shiv mandir
- Shiv Mandir
- shiv Mandir
--------------------------------------------------

In [27]:
from collections import defaultdict

# Create a copy of the current cleaned dataframe
location_df_final = location_df_cleaned.copy()

# Store merge details
final_merge_summary = []


# Loop through every exact duplicate group
for normalized_name, columns_to_merge in exact_duplicate_groups.items():
    
    # Keep only columns that currently exist
    existing_columns = [
        col for col in columns_to_merge
        if col in location_df_final.columns
    ]
    
    
    # Skip if fewer than 2 columns exist
    if len(existing_columns) < 2:
        continue
    
    
    # Use normalized name as the final canonical column name
    canonical_name = normalized_name
    
    
    # Merge using minimum available distance
    location_df_final[canonical_name] = (
        location_df_final[existing_columns]
        .min(axis=1, skipna=True)
    )
    
    
    # Drop all original duplicate columns
    location_df_final.drop(
        columns=existing_columns,
        inplace=True,
        errors='ignore'
    )
    
    
    # Save merge information
    final_merge_summary.append({
        'canonical_name': canonical_name,
        'number_of_columns_merged': len(existing_columns),
        'merged_columns': existing_columns
    })


# Convert summary to DataFrame
final_merge_summary_df = pd.DataFrame(final_merge_summary)


# Print results
print("Columns before final exact-duplicate merge:",
      location_df_cleaned.shape[1])

print("Columns after final exact-duplicate merge:",
      location_df_final.shape[1])

print("Total columns reduced:",
      location_df_cleaned.shape[1] - location_df_final.shape[1])


# Display merge summary
display(final_merge_summary_df)

Columns before final exact-duplicate merge: 1010
Columns after final exact-duplicate merge: 959
Total columns reduced: 51

,canonical_name,number_of_columns_merged,merged_columns
0,dwarka sector 21 metro station,4,"[Dwarka Sector 21, Metro Station, Dwarka Secto..."
1,fun n food waterpark,2,"[Fun N Food Waterpark, Fun N Food WaterPark]"
2,teri golf course,2,"[TERI Golf Course, Teri Golf Course]"
3,nh 48,2,"[NH 48, NH-48]"
4,nh 8,3,"[NH -8, NH-8, NH 8]"
5,imt manesar,2,"[IMT Manesar, Imt Manesar]"
6,euro international school sector 109,2,"[Euro International School, Sector- 109, Euro ..."
7,pataudi road,2,"[Pataudi Road, Pataudi road]"
8,iris broadway mall,2,"[Iris Broadway Mall, IRIS Broadway Mall]"
9,omaxe gurgaon mall,2,"[Omaxe Gurgaon Mall, OMAXE Gurgaon Mall]"
10,national highway 48,3,"[National Highway 48, National Highway 48, Na..."
11,delhi jaipur expressway,2,"[Delhi - Jaipur Expressway, Delhi Jaipur Expre..."
12,faridabad gurgaon road,2,"[Faridabad Gurgaon Road, Faridabad - Gurgaon R..."
13,huda metro station,4,"[Huda Metro Station, Huda metro station, HUDA ..."
14,delhi public school sector 84,2,"[Delhi Public School, Sector 84, Delhi Public ..."
15,infinity business park,2,"[Infinity Business Park, infinity Business Park]"
16,medanta the medicity,4,"[Medanta -The Medicity, Medanta-The Medicity, ..."
17,gems international school,2,"[GEMS International School, Gems International..."
18,park inn,2,"[Park Inn, Park inn]"
19,iffco chowk metro station,2,"[IFFCO Chowk Metro Station, Iffco Chowk Metro ..."
20,reliance trends newtown square mall,2,"[Reliance Trends Newtown Square Mall, RELIANCE..."
21,sgt university,2,"[SGT University, SGT UNIVERSITY]"
22,kmp corridor,2,"[KMP Corridor, KMP corridor]"
23,hdfc bank atm,2,"[HDFC Bank ATM, HDFC bank ATM]"
24,iffco chowk,2,"[IFFCO Chowk, Iffco Chowk]"
25,lemon tree hotel,2,"[Lemon Tree Hotel, Lemon Tree Hotel,]"
26,sector 42 43 metro station,2,"[Sector 42-43 Metro Station, Sector 42-43 Metr..."
27,global city centre,2,"[Global city centre, Global City Centre]"
28,sector 55 56 metro,2,"[Sector 55-56 metro, Sector 55-56 Metro]"
29,hub 66,2,"[HUB 66, Hub 66]"
30,the oberoi gurgaon,2,"[The Oberoi Gurgaon, The Oberoi, Gurgaon]"
31,health care pharmacy,2,"[Health Care Pharmacy, Health care pharmacy]"
32,yes bank atm,2,"[YES Bank ATM, YES bank ATM]"
33,international tech park gurgaon,2,"[International Tech Park Gurgaon,, Internation..."
34,nh 8 imt manesar,3,"[NH-8, IMT Manesar, NH-8, Imt Manesar, NH-8 IM..."
35,infinitys badminton academy,2,"[InfinityS Badminton Academy, Infinitys Badmin..."
36,yes bank,2,"[Yes Bank, YES Bank]"
37,canara bank,2,"[Canara Bank, CANARA BANK]"
38,heritage badminton academy,2,"[Heritage badminton academy, Heritage Badminto..."
39,esic hospital,2,"[ESIC Hospital, ESIC HOSPITAL]"
40,matrikiran high school,2,"[Matrikiran High School, MatriKiran High School]"
41,shiv mandir,2,"[Shiv Mandir, shiv Mandir]"

In [31]:
location_df_final.shape

(246, 959)