In [36]:
import numpy as np
import pandas as pd

In [37]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [38]:
df1 = pd.read_csv('flats_cleaned.csv')

In [39]:
df2 = pd.read_csv('houses_cleaned.csv')

In [40]:
df = pd.concat([df1, df2], ignore_index = True)

In [41]:
df = df.sample(df.shape[0], ignore_index =True)

In [42]:
df

                                          property_name property_type  \
0                       2 BHK Flat in Sector 79 Gurgaon          flat
1                       3 BHK Flat in Sector 70 Gurgaon          flat
2                       4 BHK Flat in Sector 53 Gurgaon          flat
3                       3 BHK Flat in Sector 92 Gurgaon          flat
4                       2 BHK Flat in Sector 71 Gurgaon          flat
5                      3 BHK Flat in Sector 37D Gurgaon          flat
6                      3 BHK Flat in Sector 106 Gurgaon          flat
7                       3 BHK Flat in Sector 83 Gurgaon          flat
8               3 Bedroom House for sale in Ashok Vihar         house
9                       3 BHK Flat in Sector 83 Gurgaon          flat
10                      3 BHK Flat in Sector 89 Gurgaon          flat
11                      4 BHK Flat in sector 58 Gurgaon          flat
12                     2 BHK Flat in Sector 102 Gurgaon          flat
13                      2 BHK Flat in Sector 85 Gurgaon          flat
14                      3 BHK Flat in Sector 70 Gurgaon          flat
15                      2 BHK Flat in Sector 66 Gurgaon          flat
16               4 Bedroom House for sale in Sohna Road         house
17                      2 BHK Flat in Sector 90 Gurgaon          flat
18                      4 BHK Flat in Sector 82 Gurgaon          flat
19                     3 BHK Flat in Sector 102 Gurgaon          flat
20                      2 BHK Flat in Sector 33 Gurgaon          flat
21                      3 BHK Flat in Sector 61 Gurgaon          flat
22                     3 BHK Flat in Sector 88A Gurgaon          flat
23                     3 BHK Flat in Sector 82A Gurgaon          flat
24                     3 BHK Flat in Sector 106 Gurgaon          flat
25                      3 BHK Flat in Sector 60 Gurgaon          flat
26                     2 BHK Flat in Sector 103 Gurgaon          flat
27                      3 BHK Flat in Sector 69 Gurgaon          flat
28        4 Bedroom House for sale in Sector 66 Gurgaon         house
29                      3 BHK Flat in Sector 69 Gurgaon          flat
30    2 Bedroom House for sale in Mahalaxmi Garden, ...         house
31                                  2 BHK Flat in Sohna          flat
32                        2 BHK Flat in New Palam Vihar          flat
33                     2 BHK Flat in Sector 37C Gurgaon          flat
34       7 Bedroom House for sale in Sector 109 Gurgaon         house
35             2 Bedroom House for sale in Baldev Nagar         house
36        4 Bedroom House for sale in Sector 82 Gurgaon         house
37                     2 BHK Flat in Sector 36A Gurgaon          flat
38        5 Bedroom House for sale in Sector 67 Gurgaon         house
39                      2 BHK Flat in Sector 68 Gurgaon          flat
40                                3 BHK Flat in Bhondsi          flat
41                      4 BHK Flat in Sector 92 Gurgaon          flat
42                      3 BHK Flat in Sector 90 Gurgaon          flat
43                      3 BHK Flat in Sector 92 Gurgaon          flat
44              5 Bedroom House for sale in DLF Phase 1         house
45                      4 BHK Flat in Sector 65 Gurgaon          flat
46                      2 BHK Flat in Sector 79 Gurgaon          flat
47                    3 BHK Flat in Ashok Vihar Phase 2          flat
48            3 Bedroom House for sale in Rajendra Park         house
49                 3 Bedroom House for sale in Rosewood         house
50                      2 BHK Flat in Sector 86 Gurgaon          flat
51                      3 BHK Flat in Sector 85 Gurgaon          flat
52                      3 BHK Flat in Sector 85 Gurgaon          flat
53       4 Bedroom House for sale in Sector 10A Gurgaon         house
54                      4 BHK Flat in Sector 90 Gurgaon          flat
55          5 Bedroom House for sale in Nirvana Country         house
56                     1 BHK Flat in Sector 111 Gurgaon          flat
57                      3 BHK Flat in Sector 76 Gurgaon          flat
58              3 Bedroom House for sale in DLF Phase 3         house
59                      3 BHK Flat in Sector 79 Gurgaon          flat
60              4 Bedroom House for sale in DLF Phase 3         house
61                       1 BHK Flat in Sector 2 Gurgaon          flat
62                                  2 BHK Flat in Sohna          flat
63                        3 BHK Flat in Nirvana Country          flat
64                      3 BHK Flat in Sector 68 Gurgaon          flat
65                      3 BHK Flat in Sector 65 Gurgaon          flat
66                      2 BHK Flat in Sector 95 Gurgaon          flat
67             8 Bedroom House for sale in South City 1         house
68                      2 BHK Flat in Sector 84 Gurgaon          flat
69                      2 BHK Flat in Sector 68 Gurgaon          flat
70                      4 BHK Flat in Sector 72 Gurgaon          flat
71                      2 BHK Flat in Sector 68 Gurgaon          flat
72        5 Bedroom House for sale in Sector 53 Gurgaon         house
73                            3 BHK Flat in DLF Phase 4          flat
74                      3 BHK Flat in Sector 53 Gurgaon          flat
75                      2 BHK Flat in Sector 76 Gurgaon          flat
76                      3 BHK Flat in Sector 22 Gurgaon          flat
77             3 Bedroom House for sale in Laxman Vihar         house
78                      5 BHK Flat in Sector 52 Gurgaon          flat
79          8 Bedroom House for sale in Mayfield Garden         house
80                      3 BHK Flat in Sector 82 Gurgaon          flat
81                      2 BHK Flat in Sector 60 Gurgaon          flat
82        5 Bedroom House for sale in Sector 11 Gurgaon         house
83                  2 BHK Flat in Sector 4 Urban Estate          flat
84                     3 BHK Flat in Sector 107 Gurgaon          flat
85                      1 BHK Flat in Sector 49 Gurgaon          flat
86                      2 BHK Flat in Sector 85 Gurgaon          flat
87                      2 BHK Flat in Sector 84 Gurgaon          flat
88                      2 BHK Flat in Sector 60 Gurgaon          flat
89                      2 BHK Flat in Sector 79 Gurgaon          flat
90                      2 BHK Flat in Sector 95 Gurgaon          flat
91                      3 BHK Flat in Sector 85 Gurgaon          flat
92                      3 BHK Flat in Sector 84 Gurgaon          flat
93    5 Bedroom House for sale in A Block Sushant Lo...         house
94                     3 BHK Flat in Sector 102 Gurgaon          flat
95                     3 BHK Flat in Sector 37C Gurgaon          flat
96                      2 BHK Flat in Sector 81 Gurgaon          flat
97                      3 BHK Flat in Sector 54 Gurgaon          flat
98                     3 BHK Flat in Sector 108 Gurgaon          flat
99                    3 Bedroom House for sale in Sohna         house
100                    3 BHK Flat in Sector 103 Gurgaon          flat
101                     3 BHK Flat in Sector 83 Gurgaon          flat
102                    2 BHK Flat in Sector 70A Gurgaon          flat
103              3 Bedroom House for sale in Hira Nagar         house
104                     2 BHK Flat in Sector 85 Gurgaon          flat
105            4 Bedroom House for sale in Pataudi Road         house
106       4 Bedroom House for sale in Sector 76 Gurgaon         house
107                     3 BHK Flat in Sector 67 Gurgaon          flat
108             4 Bedroom House for sale in DLF Phase 3         house
109       4 Bedroom House for sale in Sector 86 Gurgaon         house
110                     3 BHK Flat in Sector 81 Gurgaon          flat
111                     2 BHK Flat in Sector 65 Gurgaon          flat
112                     3 BHK Flat in Sector 63 Gurgaon          flat
113                       4 BHK Flat in Sector-33 Sohna          flat
114             5 Bedroom House for sale in DLF Phase 2         house
115                    3 BHK Flat in Sector 109 Gurgaon          flat
116                     2 BHK Flat in Sector 69 Gurgaon          flat
117           9 Bedroom House for sale in Rattan Garden         house
118      4 Bedroom House for sale in Sector 109 Gurgaon         house
119                     3 BHK Flat in Sector 63 Gurgaon          flat
120                    2 BHK Flat in Sector 107 Gurgaon          flat
121           3 Bedroom House for sale in Vishnu Garden         house
122                     4 BHK Flat in Sector 56 Gurgaon          flat
123       3 Bedroom House for sale in Sector 49 Gurgaon         house
124                     3 BHK Flat in Sector 90 Gurgaon          flat
125                   3 BHK Flat in Sushant Lok Phase 1          flat
126                    3 BHK Flat in Sector 99A Gurgaon          flat
127             4 Bedroom House for sale in Maruti Kunj         house
128         6 Bedroom House for sale in Uppals Southend         house
129       2 Bedroom House for sale in Sector 13 Gurgaon         house
130                     3 BHK Flat in Sector 70 Gurgaon          flat
131                    3 BHK Flat in Sector 37C Gurgaon          flat
132                    2 BHK Flat in Sector 37C Gurgaon          flat
133                     2 BHK Flat in Sector 85 Gurgaon          flat
134        5 Bedroom House for sale in Sector 3 Gurgaon         house
135                                 2 BHK Flat in Sohna          flat
136                    2 BHK Flat in Sector 104 Gurgaon          flat
137                     3 BHK Flat in Sector 67 Gurgaon          flat
138       4 Bedroom House for sale in Sector 92 Gurgaon         house
139            7 Bedroom House for sale in Shakti Nagar         house
140                    3 BHK Flat in Sector 109 Gurgaon          flat
141                     4 BHK Flat in Sector 60 Gurgaon          flat
142                     3 BHK Flat in Sector 48 Gurgaon          flat
143                     2 BHK Flat in Sector 69 Gurgaon          flat
144                           2 BHK Flat in Patel Nagar          flat
145                     2 BHK Flat in Sector 91 Gurgaon          flat
146                     5 BHK Flat in Sector 48 Gurgaon          flat
147                     4 BHK Flat in Sector 65 Gurgaon          flat
148                    3 BHK Flat in Sector 113 Gurgaon          flat
149                           3 BHK Flat in Palam Vihar          flat
150                     3 BHK Flat in Sector 79 Gurgaon          flat
151                    2 BHK Flat in Sector 95A Gurgaon          flat
152                    3 BHK Flat in Sector 104 Gurgaon          flat
153                     3 BHK Flat in Sector 59 Gurgaon          flat
154             4 Bedroom House for sale in Ansal Plaza         house
155                     3 BHK Flat in Sector 86 Gurgaon          flat
156                     3 BHK Flat in Sector 92 Gurgaon          flat
157                     3 BHK Flat in Sector 86 Gurgaon          flat
158       3 Bedroom House for sale in Sector 14 Gurgaon         house
159                     2 BHK Flat in Sector 71 Gurgaon          flat
160                     3 BHK Flat in Sector 79 Gurgaon          flat
161                       3 BHK Flat in Sector 36 Sohna          flat
162                     3 BHK Flat in Sector 81 Gurgaon          flat
163                    4 BHK Flat in Sector 70A Gurgaon          flat
164                     2 BHK Flat in Sector 68 Gurgaon          flat
165                    3 BHK Flat in Sector 37D Gurgaon          flat
166                    4 BHK Flat in Sector 104 Gurgaon          flat
167       4 Bedroom House for sale in Sector 48 Gurgaon         house
168                     3 BHK Flat in Sector 61 Gurgaon          flat
169                    2 BHK Flat in Sector 102 Gurgaon          flat
170                       2 BHK Flat in Sector-33 Sohna          flat
171                     2 BHK Flat in Sector 86 Gurgaon          flat
172                     3 BHK Flat in Sector 89 Gurgaon          flat
173                     3 BHK Flat in Sector 86 Gurgaon          flat
174       2 Bedroom House for sale in Sector 31 Gurgaon         house
175                   1 BHK Flat in Block A Surya Vihar          flat
176                  2 BHK Flat in Sector 1 Imt Manesar          flat
177                     4 BHK Flat in Sector 55 Gurgaon          flat
178                     5 BHK Flat in Sector 51 Gurgaon          flat
179                    3 BHK Flat in Sector 70A Gurgaon          flat
180                     2 BHK Flat in Sector 92 Gurgaon          flat
181                    4 BHK Flat in Sector 104 Gurgaon          flat
182                    3 BHK Flat in Sector 36A Gurgaon          flat
183                    2 BHK Flat in Sector 37C Gurgaon          flat
184                    2 BHK Flat in Sector 107 Gurgaon          flat
185                     2 BHK Flat in Sector 99 Gurgaon          flat
186       6 Bedroom House for sale in Sector 55 Gurgaon         house
187                    4 BHK Flat in Sector 104 Gurgaon          flat
188                    3 BHK Flat in Sector 102 Gurgaon          flat
189                       3 BHK Flat in Sector-33 Sohna          flat
190                                 2 BHK Flat in Sohna          flat
191                       3 BHK Flat in Sector-33 Sohna          flat
192                           5 BHK Flat in Gwal Pahari          flat
193                       3 BHK Flat in Sector-33 Sohna          flat
194                     3 BHK Flat in Sector 77 Gurgaon          flat
195                     3 BHK Flat in Sector 66 Gurgaon          flat
196                     4 BHK Flat in Sector 22 Gurgaon          flat
197                     4 BHK Flat in Sector 86 Gurgaon          flat
198                     3 BHK Flat in Sector 70 Gurgaon          flat
199                     3 BHK Flat in Sector 70 Gurgaon          flat
200                     3 BHK Flat in Sector 67 Gurgaon          flat
201                     3 BHK Flat in Sector 49 Gurgaon          flat
202                                 2 BHK Flat in Sohna          flat
203                     4 BHK Flat in Sector 71 Gurgaon          flat
204                     3 BHK Flat in Sector 83 Gurgaon          flat
205                     3 BHK Flat in Sector 92 Gurgaon          flat
206                     4 BHK Flat in Sector 99 Gurgaon          flat
207                     4 BHK Flat in Sector 84 Gurgaon          flat
208                     3 BHK Flat in Sector 61 Gurgaon          flat
209                    3 BHK Flat in Sector 102 Gurgaon          flat
210      4 Bedroom House for sale in Sector 109 Gurgaon         house
211                     4 BHK Flat in Sector 81 Gurgaon          flat
212       5 Bedroom House for sale in Sector 33 Gurgaon         house
213                     2 BHK Flat in Sector 95 Gurgaon          flat
214                     5 BHK Flat in Sector 14 Gurgaon          flat
215                     4 BHK Flat in Sector 92 Gurgaon          flat
216                                 2 BHK Flat in Sohna          flat
217                     3 BHK Flat in Sector 65 Gurgaon          flat
218                     2 BHK Flat in Sector 77 Gurgaon          flat
219       3 Bedroom House for sale in Sector 82 Gurgaon         house
220                     3 BHK Flat in Sector 92 Gurgaon          flat
221                     2 BHK Flat in Sector 85 Gurgaon          flat
222                    2 BHK Flat in Sector 113 Gurgaon          flat
223                   1 Bedroom House for sale in Sohna         house
224                     3 BHK Flat in Sector 65 Gurgaon          flat
225                     2 BHK Flat in Sector 81 Gurgaon          flat
226                     3 BHK Flat in Sector 92 Gurgaon          flat
227                     2 BHK Flat in Sector 86 Gurgaon          flat
228       4 Bedroom House for sale in Sector 48 Gurgaon         house
229                     5 BHK Flat in Sector 49 Gurgaon          flat
230                     3 BHK Flat in Sector 78 Gurgaon          flat
231                     2 BHK Flat in Sector 79 Gurgaon          flat
232       6 Bedroom House for sale in Sector 50 Gurgaon         house
233                           2 BHK Flat in Palam Vihar          flat
234                 3 BHK Flat in Sector 1A IMT Manesar          flat
235     3 Bedroom House for sale in Sushant Lok Phase 1         house
236      3 Bedroom House for sale in Sector 37D Gurgaon         house
237                     1 BHK Flat in Sector 71 Gurgaon          flat
238     4 Bedroom House for sale in Sushant Lok Phase 2         house
239                       2 BHK Flat in Nirvana Country          flat
240      10 Bedroom House for sale in Sector 38 Gurgaon         house
241                           2 BHK Flat in DLF Phase 4          flat
242                       3 BHK Flat in Sector-33 Sohna          flat
243      4 Bedroom House for sale in Sector 70A Gurgaon         house
244                 4 BHK Flat in Sector 1A IMT Manesar          flat
245                     4 BHK Flat in Sector 92 Gurgaon          flat
246                 3 BHK Flat in Sector 1A IMT Manesar          flat
247   1 Bedroom House for sale in laxmna vihar, phase 2         house
248                     4 BHK Flat in Sector 60 Gurgaon          flat
249       3 Bedroom House for sale in Sector 43 Gurgaon         house
250       6 Bedroom House for sale in Sector 14 Gurgaon         house
251                    4 BHK Flat in Sector 106 Gurgaon          flat
252                     3 BHK Flat in Sector 56 Gurgaon          flat
253                    3 BHK Flat in Sector 109 Gurgaon          flat
254                    3 BHK Flat in Sector 82A Gurgaon          flat
255                     3 BHK Flat in Sector 83 Gurgaon          flat
256             3 Bedroom House for sale in DLF Phase 2         house
257                    2 BHK Flat in Sector 99A Gurgaon          flat
258                     3 BHK Flat in Sector 28 Gurgaon          flat
259                     3 BHK Flat in Sector 77 Gurgaon          flat
260                    4 BHK Flat in Sector 102 Gurgaon          flat
261       4 Bedroom House for sale in Sector 82 Gurgaon         house
262       6 Bedroom House for sale in Sector 67 Gurgaon         house
263                     4 BHK Flat in Sector 59 Gurgaon          flat
264          4 Bedroom House for sale in Tekchand Nagar         house
265                 4 BHK Flat in Mehrauli Gurgaon Road          flat
266             4 Bedroom House for sale in DLF Phase 1         house
267                     2 BHK Flat in Sector 90 Gurgaon          flat
268                     3 BHK Flat in Sector 67 Gurgaon          flat
269                    3 BHK Flat in Sector 12A Gurgaon          flat
270                    2 BHK Flat in Sector 103 Gurgaon          flat
271             4 Bedroom House for sale in DLF Phase 1         house
272             4 Bedroom House for sale in DLF Phase 4         house
273        5 Bedroom House for sale in Sector 5 Gurgaon         house
274                       3 BHK Flat in Nirvana Country          flat
275                     3 BHK Flat in Sector 22 Gurgaon          flat
276                     3 BHK Flat in Sector 92 Gurgaon          flat
277                           3 BHK Flat in IMT Manesar          flat
278                     3 BHK Flat in Sector 80 Gurgaon          flat
279                     3 BHK Flat in Sector 63 Gurgaon          flat
280                     3 BHK Flat in Sector 68 Gurgaon          flat
281                     3 BHK Flat in Sector 47 Gurgaon          flat
282                     2 BHK Flat in Sector 85 Gurgaon          flat
283                                 2 BHK Flat in Sohna          flat

In [43]:
df.to_csv('gurgoan_properties.csv')

In [44]:
df.shape

(3955, 20)

In [45]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3326,7 Bedroom House for sale in Sector 23 Gurgaon,house,NaN,5.65,17706.0,3191.0,Plot area 342(285.96 sq.m.)Built Up area: 5000...,7,7,3+,"pooja room,servant room","Sector 23 Gurgaon, Gurgaon, Haryana",2.0,West,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",The property is very well located in sector 23...,"['2 Fan', '2 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
555,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,0.70,4453.0,1572.0,Built Up area: 1572 (146.04 sq.m.),3,3,0,not available,"Palam Vihar, Sector 92 Gurgaon, Gurgaon, Haryana",7.0,NaN,undefined,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",3bhk multistorey apartment for resale in rahej...,NaN,NaN,"['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
2796,3 BHK Flat in Sector 65 Gurgaon,flat,m3m golfestate,5.30,24211.0,2189.0,Super Built up area 2850(264.77 sq.m.)Carpet a...,3,3,3,servant room,"Sector 65 Gurgaon, Gurgaon, Haryana",38.0,North-East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",M3m very luxury society on road,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geys...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
284,3 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,1.20,12526.0,958.0,Carpet area: 958 (89 sq.m.),3,3,3,"pooja room,store room","N54c, Sector 89 Gurgaon, Gurgaon, Haryana",3.0,East,Oct 2023,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Corner unit near biggest green area of the pro...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1750,3 BHK Flat in Sector 65 Gurgaon,flat,emaar mgf emerald floors premier,2.25,13636.0,1650.0,Super Built up area 1650(153.29 sq.m.),3,3,3+,"study room,servant room","002, Sector 65 Gurgaon, Gurgaon, Haryana",3.0,South,1 to 5 Year Old,"['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...",Check out this 3 bhk apartment for sale in ema...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction5 out ..."

In [46]:
df.insert(loc = 4, column = 'sector', value = df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip())

In [47]:
df.head()

,property_name,property_type,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 79 Gurgaon,flat,godrej,1.30,Sector 79,8269.0,1572.0,Super Built up area 1572(146.04 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...",This 2 bhk apartment is available for sale in ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,1.63,Sector 70,8358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,5,3,servant room,"143, Sector 70 Gurgaon, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",This lovely 3 bhk apartment/flat in sector 70 ...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction5 out of..."
2,4 BHK Flat in Sector 53 Gurgaon,flat,tulip monsella,7.40,Sector 53,33198.0,2229.0,Carpet area: 2229 (207.08 sq.m.),4,4,3,not available,"Sector 53 Gurgaon, Gurgaon, Haryana",21.0,NaN,Jun 2027,"['Sector 53-54 Metro Station', 'Central Plaza ...","The platinum collection by tulip group, driven...","['1 Wardrobe', '1 Geyser', '1 Light', '1 AC', ...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
3,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,0.65,Sector 92,4744.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,2,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",This lovely 3 bhk apartment/flat in sector 92 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ..."
4,2 BHK Flat in Sector 71 Gurgaon,flat,signature andour heights,0.60,Sector 71,10000.0,600.0,Super Built up area 600(55.74 sq.m.)Carpet are...,2,2,1,pooja room,"001, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South-West,1 to 5 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",This is 2bhk semi furnished flat available on ...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [48]:
df['sector'] = df['sector'].str.lower()

In [49]:
df.head()

,property_name,property_type,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 79 Gurgaon,flat,godrej,1.30,sector 79,8269.0,1572.0,Super Built up area 1572(146.04 sq.m.),2,2,3,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...",This 2 bhk apartment is available for sale in ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,1.63,sector 70,8358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,5,3,servant room,"143, Sector 70 Gurgaon, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",This lovely 3 bhk apartment/flat in sector 70 ...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction5 out of..."
2,4 BHK Flat in Sector 53 Gurgaon,flat,tulip monsella,7.40,sector 53,33198.0,2229.0,Carpet area: 2229 (207.08 sq.m.),4,4,3,not available,"Sector 53 Gurgaon, Gurgaon, Haryana",21.0,NaN,Jun 2027,"['Sector 53-54 Metro Station', 'Central Plaza ...","The platinum collection by tulip group, driven...","['1 Wardrobe', '1 Geyser', '1 Light', '1 AC', ...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
3,3 BHK Flat in Sector 92 Gurgaon,flat,raheja sampada,0.65,sector 92,4744.0,1370.0,Super Built up area 1370(127.28 sq.m.),3,2,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",This lovely 3 bhk apartment/flat in sector 92 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ..."
4,2 BHK Flat in Sector 71 Gurgaon,flat,signature andour heights,0.60,sector 71,10000.0,600.0,Super Built up area 600(55.74 sq.m.)Carpet are...,2,2,1,pooja room,"001, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South-West,1 to 5 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",This is 2bhk semi furnished flat available on ...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [50]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     68
sector 104                                                    66
sector 107                                                    60
sector 108                                                    58
sector 48                                                     58
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 70a                                                    55
sector 37c                                                    53
sector 70                                                     53
palam vihar                                                   52
nirvana country                                               52
sector 84                                                     51
sector-33 sohna                                               51
sector 67                                                     48
sector 103                                                    45
dlf phase 1                                                   44
sector 113                                                    43
sector 82                                                     42
sector 66                                                     42
sector 61                                                     42
dlf phase 2                                                   41
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  26
dlf phase 4                                                   25
sector 112                                                    25
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
dlf phase 3                                                   21
sector 33                                                     20
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     18
sector 62                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
sector 3                                                      14
sector 53                                                     14
sector 1 imt manesar                                          14
gwal pahari                                                   14
dlf phase 5                                                   14
rajendra park                                                 14
sector 76                                                     14
sector 52                                                     14
laxman vihar phase 2                                          13
uppals southend                                               13
sector 46                                                     13
sector 36a                                                    13
sector 31                                                     12
sector 38                                                     12
sector 39                                                     12
sohna road                                                    12
sector 93                                                     12
sector 50                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 55                                                     10
c block sushant lok phase 1                                    9
sector 4                                                       9
ashok vihar phase 2                                            9
south city 1                                                   9
sector 95a                                                     9
palam vihar extension                                          8
dwarka expressway                                              8
sector 10a                                                     8
sector 40                                                      8
sector 57                                                      8
sector 59                                                      8
malibu town                                                    8
sector 43                                                      8
sector 89 a                                                    8
mehrauli  road                                                 8
sector 36 sohna                                                7
sector 58                                                      7
mianwali colony                                                7
surat nagar 1                                                  7
new colony                                                     7
sector 26                                                      7
sector 51                                                      7
greenwood city                                                 6
rajiv nagar                                                    6
jacobpura                                                      6
ashok vihar                                                    6
sector 5                                                       6
jyoti park                                                     6
sector 11                                                      6
sector 1                                                       6
saraswati vihar                                                5
sector 9                                                       5
sector 23a                                                     5
chakkarpur                                                     5
manesar                                                        5
sector 105                                                     5
arjun nagar                                                    5
subhash nagar                                                  5
sector 30                                                      5
sector 2                                                       5
sector 28                                                      5
ansal plaza                                                    5
new palam vihar                                                5
dayanand colony                                                5
sector 80                                                      5
sushant lok phase 2                                            5
shivaji nagar                                                  4
vishnu garden                                                  4
sector 36                                                      4
sector 17                                                      4
valley view estate                                             4
sector 3a                                                      4
ravi nagar                                                     4
devilal colony                                                 4
krishna colony                                                 4
sector 6                                                       4
dharam colony                                                  4
bhondsi                                                        4
shivpuri                                                       4
baldev nagar                                                   4
surya vihar                                                    4
madanpuri                                                      4
bhim nagar                                                     4
new                                                            4
garhi harsaru                                                  4
sector 12a                                                     4
imt manesar                                                    4
adarsh nagar                                                   4
suncity                                                        4
sector 12                                                      4
b block sushant lok phase 1                                    3
sector 17a                                                     3
sector 8                                                       3
sector 23                                                      3
sector 17b                                                     3
a block sushant lok phase 1                                    3
gandhi nagar                                                   3
prem nagar                                                     3
mg road                                                        3
sector 73                                                      3
sector 88b                                                     3
sector 15                                                      3
laxmi garden                                                   3
sector 27                                                      3
patel nagar                                                    3
sector 110 a                                                   3
sector 45                                                      3
maruti kunj                                                    3
samaspur                                                       2
lajpat nagar                                                   2
sector 32                                                      2
bhawani enclave                                                2
sheetla colony                                                 2
sohna  road                                                    2
sispal vihar                                                   2
block a surya vihar                                            2
daulatabad                                                     2
sector 15 part 1                                               2
surat nagar                                                    2
bissar                                                         2
shanti nagar                                                   2
sector 15 part 2                                               2
sushant lok                                                    2
, delhi ncr                                                    2
sector-2 sohna                                                 2
shankar vihar                                                  2
sector 41                                                      2
sector 24                                                      2
shakti nagar                                                   2
nars                                                           2
west rajiv nagar                                               2
ambience island                                                2
rosewood                                                       2
golf course ext road                                           2
faridabad road                                                 2
new palam vihar phase 1                                        2
rajiv chowk                                                    2
farukhnagar                                                    2
new palam vihar phase 2                                        2
sector 21                                                      2
hira nagar                                                     2
mayfield garden                                                2
pratap nagar                                                   2
acharya puri                                                   2
golf course road                                               2
new basti                                                      2
sector-11 sohna                                                2
mohan nagar                                                    2
manohar nagar                                                  2
surat nagar phase 2                                            2
iffco chowk                                                    2
near sector 1 market                                           1
hno 13 sagar enclave sura                                      1
sector 17c                                                     1
sultanpur                                                      1
sai kunj                                                       1
ansal's palam vihar                                            1
nirvana country pocket h                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
park view                                                      1
block g sector-57                                              1
rajiv colony                                                   1
sector-35 sohna                                                1
sadar bazar                                                    1
sector-7 hous                                                  1
near nand hospital                                             1
devi lal colony gali no 12 gurgaon nr omkar public school      1
kheri                                                          1
om nagar                                                       1
sector 21a faridabad                                           1
alipur                                                         1
hsiidc plot sector 1 imt manesar                               1
mahavir pura                                                   1
kanahi                                                         1
block h ashok vihar phase iii extension                        1
b1 block sector 57                                             1
sector 37a                                                     1
shivji park colony                                             1
sector-5 sohna                                                 1
urban estate, sector 5                                         1
sector 42                                                      1
near euro                                                      1
ravi nager basai road                                          1
saroop garden rajendra park                                    1
jacobpura near sadar bazar                                     1
lucknow                                                        1
bhora kalan                                                    1
sector 9b                                                      1
south city                                                     1
near khandsa road                                              1
near pataudi chowk                                             1
garauli kalan                                                  1
huda saraswati vihar                                           1
saraswati enclave                                              1
new colony, sector 7                                           1
v block dlf phase 3                                            1
jat colony,fazilpur/taj nagar road                             1
carterpuri village                                             1
begampur khatola                                               1
tekchand nagar                                                 1
laxmna vihar, phase 2                                          1
sector 13                                                      1
rattan garden                                                  1
pataudi road                                                   1
sector 4 urban estate                                          1
mahalaxmi garden, rajendra place                               1
sector-5 sheetla colony                                        1
ashok vihar phase 3                                            1
sector 5 chowk                                                 1
part 3 sector 5                                                1
old delhi road, opp sector-14                                  1
damdma                                                         1
new jyoti park                                                 1
g block dlf city phase 1                                       1
khandsa                                                        1
ashok vihar phase i                                            1
heritage city                                                  1
vir nagar                                                      1
godrej aria , sector 79 ,                                      1
gopal nagar, garhi ghasita, sonipat                            1
sector 37b                                                     1
bhimgarh kheri phase 3                                         1
dhankot                                                        1
anand garden, sector-105                                       1
bptp                                                           1
ram nagar                                                      1
cyber city                                                     1
laxman vihar, railway road,                                    1
civil l                                                        1
ats marigold                                                   1
Name: count, dtype: int64

In [51]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 2]
df = df[df['sector'].isin(a.index)]

In [52]:
df[df['sector'] == 'nirvana country']

,property_name,property_type,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
55,5 Bedroom House for sale in Nirvana Country,house,NaN,11.58,nirvana country,35741.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Nirwana villa for sale\nConfirm deal\nDuplex v...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
63,3 BHK Flat in Nirvana Country,flat,the close north,2.51,nirvana country,11992.0,2093.0,Super Built up area 2093(194.45 sq.m.),3,3,3,"pooja room,store room","101, Nirvana Country, Gurgaon, Haryana",11.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Situated in nirvana country, gurgaon, the clos...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."
239,2 BHK Flat in Nirvana Country,flat,woodstock floors,1.05,nirvana country,10627.0,988.0,Carpet area: 988 (91.79 sq.m.),2,2,2,not available,"047, Nirvana Country, Gurgaon, Haryana",2.0,North,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",Corner flat with ample natural lights \nOne of...,NaN,"['Security / Fire Alarm', 'Maintenance Staff',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
274,3 BHK Flat in Nirvana Country,flat,the close north,3.00,nirvana country,11516.0,2605.0,Super Built up area 2605(242.01 sq.m.),3,3,3+,servant room,"Nirvana Country, Gurgaon, Haryana",14.0,North,10+ Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","This beautiful 3 bhk flat in nirvana country, ...","['3 Wardrobe', '1 Water Purifier', '7 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
447,3 Bedroom House for sale in Nirvana Country,house,unitech espace,7.50,nirvana country,34722.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 241 ...,3,3,2,servant room,"240 Yards Espace Nirvana Country Villa, Nirvan...",2.0,West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Available for sale 240 yards simplex villa in ...,"['1 Exhaust Fan', '4 Geyser', '1 Stove', '1 Mi...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety5 out of 5', ..."
486,3 BHK Flat in Nirvana Country,flat,the close north,3.00,nirvana country,11516.0,2605.0,Super Built up area 2605(242.01 sq.m.),3,3,3+,servant room,"Nirvana Country, Gurgaon, Haryana",14.0,North,10+ Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","This beautiful 3 bhk flat in nirvana country, ...","['3 Wardrobe', '1 Water Purifier', '7 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Connectivity4 out of 5', 'Management4.5 out ..."
586,6 Bedroom House for sale in Nirvana Country,house,NaN,13.20,nirvana country,27155.0,4861.0,Built Up area: 4861 (451.6 sq.m.),6,6,No,not available,"Nirvana Country, Sector 50, Nirvana Country, G...",2.0,NaN,undefined,NaN,6bhk residential house for resale in nirvana c...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
793,3 BHK Flat in Nirvana Country,flat,the close north,2.35,nirvana country,11358.0,2069.0,Super Built up area 2069(192.22 sq.m.)Built Up...,3,3,3,not available,"8,9, Nirvana Country, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Available for sale in a 3 bedroom room, 3bathr...","['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
810,3 BHK Flat in Nirvana Country,flat,the close north,2.50,nirvana country,11944.0,2093.0,Super Built up area 2093(194.45 sq.m.),3,3,3,pooja room,"111, Nirvana Country, Gurgaon, Haryana",11.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","3 bhk apartment for sale in the close north, a...","['3 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Water purifier', 'Power Back-up', 'Feng Shui...","['Green Area5 out of 5', 'Construction4 out of..."
829,5 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,7.10,nirvana country,32870.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 239 ...,5,4,3,"store room,pooja room,study room","240 Sq Yd, Ground And First Floor At 7.10 Cr, ...",2.0,East,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",This is residential house for sale in the very...,"['3 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
915,5 Bedroom House for sale in Nirvana Country,house,unitech espace,10.45,nirvana country,32253.0,3240.0,Plot area 360(301.01 sq.m.),5,7,3+,"pooja room,study room,servant room,others","Es-201, Nirvana Country, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Available for sale well maintained villa in es...,"['1 Water Purifier', '1 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1011,3 BHK Flat in Nirvana Country,flat,unitech fresco,1.82,nirvana country,9912.0,1836.0,Super Built up area 1836(170.57 sq.m.)Built Up...,3,3,3+,others,"1402, Nirvana Country, Gurgaon, Haryana",14.0,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...",Looking for a 3 bhk property for sale in gurga...,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction3 out of..."
1065,5 Bedroom House for sale in Nirvana Country,house,unitech espace,10.30,nirvana country,31790.0,3240.0,Plot area 360(301.01 sq.m.),5,6,3+,"pooja room,study room,servant room,store room","Nirvana Country, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Nirvana country is one of gurgaon's most sough...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1086,3 BHK Flat in Nirvana Country,flat,the close south,3.25,nirvana country,12810.0,2537.0,Carpet area: 2537 (235.7 sq.m.),3,4,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,South-East,10+ Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...",Preference location. Facing the front garden e...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '3 Geys...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
1170,3 BHK Flat in Nirvana Country,flat,the close north,2.97,nirvana country,11401.0,2605.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3+,servant room,"801, Nirvana Country, Gurgaon, Haryana",8.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",This lovely 3 bhk apartment/flat in nirvana co...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1223,3 BHK Flat in Nirvana Country,flat,the close north,2.65,nirvana country,10685.0,2480.0,Super Built up area 2480(230.4 sq.m.)Built Up ...,3,4,3+,servant room,"602, Nirvana Country, Gurgaon, Haryana",6.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",This lovely 3 bhk apartment/flat in nirvana co...,"['5 Fan', '1 Exhaust Fan', '4 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1367,4 Bedroom House for sale in Nirvana Country,house,unitech espace,7.42,nirvana country,34351.0,2160.0,Plot area 2160(200.67 sq.m.)Built Up area: 320...,4,4,3,not available,"Good Location Villa On Sale, Nirvana Country, ...",2.0,West,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...","4bhk independent villa on sale, espace, nirvan...","['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1506,5 Bedroom House for sale in Nirvana Country,house,unitech espace,11.29,nirvana country,34846.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3+,"study room,pooja room","Nirvana Country, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Urgent for sale villa\nConfirm deal\nNice loca...,"['7 Fan', '8 Light', '4 AC', 'No Bed', 'No Chi...","['Maintenance Staff', 'Water Storage', 'Fitnes...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1511,2 BHK Flat in Nirvana Country,flat,unitech fresco,1.14,nirvana country,8532.0,1336.0,Super Built up area 1336(124.12 sq.m.)Built Up...,2,2,2,others,"1902, Nirvana Country, Gurgaon, Haryana",19.0,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...","Situated in nirvana country, gurgaon, unitech ...","['4 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction3 out of..."
1556,4 Bedroom House for sale in Nirvana Country,house,unitech espace,7.35,nirvana country,41762.0,1760.0,Plot area 240(200.67 sq.m.),4,4,3+,"pooja room,servant room","Nirvana Country, Gurgaon, Haryana",3.0,South,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",This is property is next to park and sunfacing.,"['5 Wardrobe', '1 Exhaust Fan', '4 Geyser', '9...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1569,4 Bedroom House for sale in Nirvana Country,house,unitech espace,9.80,nirvana country,30247.0,3240.0,Plot area 360(301.01 sq.m.)Built Up area: 300 ...,4,4,3,servant room,"Nirvana Country, Gurgaon, Haryana",2.0,North-West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",A north west facing beautiful and well maintai...,"['4 Light', 'No AC', 'No Bed', 'No Chimney', '...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1578,3 Bedroom House for sale in Nirvana Country,house,unitech aspen greens,6.95,nirvana country,4490.0,15479.0,Plot area 240(200.67 sq.m.)Built Up area: 2160...,3,3,1,servant room,"Lm 96, Nirvana Country, Gurgaon, Haryana",2.0,North-East,5 to 10 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",A magnificent lifestyle curated for just the e...,"['7 Light', '1 Modular Kitchen', 'No AC', 'No ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1692,3 BHK Flat in Nirvana Country,flat,the close north,2.70,nirvana country,9980.0,2705.0,Super Built up area 2605(242.01 sq.m.),3,3,3+,servant room,"16floor, Nirvana Country, Gurgaon, Haryana",3.0,South,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",This 3 bhk apartment is available for sale in ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
1761,3 BHK Flat in Nirvana Country,flat,unitech harmony,2.60,nirvana country,9590.0,2711.0,Super Built up area 2711(251.86 sq.m.)Built Up...,3,4,2,"servant room,others","1501, Nirvana Country, Gurgaon, Haryana",15.0,North-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'M3M Cosmopo...","Situated in nirvana country, gurgaon, unitech ...","['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1824,4 Bedroom House for sale in Nirvana Country,house,unitech nirvana birch court,6.80,nirvana country,31481.0,2160.0,Plot area 240(200.67 sq.m.),4,4,3+,"pooja room,study room,servant room","Nirvana Country, Gurgaon, Haryana",2.0,South-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Available for villa in birch court nirvana cou...,"['1 Wardrobe', '1 Fan', '1 Geyser', '1 Light',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1994,3 Bedroom House for sale in Nirvana Country,house,unitech nirvana birch court,11.95,nirvana country,36883.0,3240.0,Plot area 360(301.01 sq.m.),3,3,2,"study room,servant room","Nirvana Country, Gurgaon, Haryana",1.0,West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Park fecing villa for sale in nirvana country ...,"['1 Wardrobe', '1 Fan', '1 Geyser', '3 Light',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
2034,3 BHK Flat in Nirvana Country,flat,the close north,2.70,nirvana country,10364.0,2605.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3+,servant room,"002, Nirvana Country, Gurgaon, Haryana",6.0,East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",Check out this 3 bhk apartment for sale in the...,"['5 Fan', '15 Light', 'No AC', 'No Bed', 'No C...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2040,3 BHK Flat in Nirvana Country,flat,unitech fresco,1.88,nirvana country,10479.0,1794.0,Super Built up area 1794(166.67 sq.m.)Built Up...,3,3,3+,others,"1402, Nirvana Country, Gurgaon, Haryana",14.0,North,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...","Situated in nirvana country, gurgaon, unitech ...","['7 Fan', '1 Exhaust Fan', '4 Geyser', '12 Lig...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction3 out of..."
2062,3 BHK Flat in Nirvana Country,flat,the close north,2.75,nirvana country,12500.0,2200.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3,servant room,"221, Nirvana Country, Gurgaon, Haryana",3.0,South-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Power back up, lift, rain water harvesting, cl...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
2099,4 Bedroom House for sale in Nirvana Country,house,unitech aspen greens,7.00,nirvana country,32407.0,2160.0,Plot area 240(200.67 sq.m.),4,4,2,servant room,"0000, Nirvana Country, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",A nice location villa livable condition for sale.,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Maintenance Staff', 'Water Storage', 'No ope...","['Environment5 out of 5', 'Safety5 out of 5', ..."
2118,3 Bedroom House for sale in Nirvana Country,house,unitech nirvana birch court,7.10,nirvana country,283333.0,251.0,Plot area 240(22.3 sq.m.),3,3,3,servant room,"Nirvana Country, Gurgaon, Haryana",1.0,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",It is good livable house with 100 power backup...,"['1 Modular Kitchen', '3 Wardrobe', 'No AC', '...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
2285,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,3.99,nirvana country,8866.0,4500.0,Plot area 4500(418.06 sq.m.),4,5,3+,"pooja room,servant room","Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2530,5 Bedroom House for sale in Nirvana Country,house,NaN,10.55,nirvana country,32562.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,"study room,servant room","Nirvana Country, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nConfirm deal\nNice location\n...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2585,5 Bedroom House for sale in Nirvana Country,house,NaN,10.56,nirvana country,32593.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2670,3 Bedroom House for sale in Nirvana Country,house,NaN,7.00,nirvana country,32407.0,2160.0,Built Up area: 240 (200.67 sq.m.),3,2,No,not available,"Nirvana Country, Gurgaon, Haryana",1.0,NaN,undefined,NaN,"2 bath, semi-Furnished, at nirvana country loc...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
2714,3 Bedroom House for sale in Nirvana Country,house,unitech aspen greens,12.00,nirvana country,37037.0,3240.0,Plot area 360(301.01 sq.m.),3,4,2,"study room,servant room","Nirvana Country, Gurgaon, Haryana",1.0,East,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Park feacing villa for sale in nirvana country...,"['3 Wardrobe', '3 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
2822,4 Bedroom House for sale in Nirvana Country,house,NaN,10.45,nirvana country,38703.0,2700.0,Plot area 2700(250.84 sq.m.)Built Up area: 400...,4,5,2,"servant room,study room,pooja room","Espace Nirvana Country Gurgaon, Nirvana Countr...",3.0,North,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",4 bhk park facing prime location villa in \nNi...,"['8 Fan', '5 Geyser', '14 Light', '1 Modular K...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2901,5 Bedroom House for sale in Nirvana Country,house,unitech escape,12.00,nirvana country,37037.0,3240.0,Carpet area: 360 (301.01 sq.m.),5,6,3+,not available,"Nirvana Country, Sector 50, Nirvana Country, G...",3.0,East,undefined,"['Sector 55-56 Metro Station', 'Airia Mall', '...",5bhk villa for resale in unitech escape at nir...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
2914,3 BHK Flat in Nirvana Country,flat,the close north,2.92,nirvana country,11209.0,2605.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3,servant room,"1002, Nirvana Country, Gurgaon, Haryana",10.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",Looking for a 3 bhk property for sale in gurga...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2973,4 Bedroom House for sale in Nirvana Country,house,unitech espace,7.45,nirvana country,34491.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 4500...,4,4,3,servant room,"240 Sq.Yds Duplex Villa, Nirvana Country, Gurg...",3.0,NaN,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...","240 sq.Yds old built duplex villa on sale, at ...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3053,4 Bedroom House for sale in Nirvana Country,house,unitech espace,11.00,nirvana country,40741.0,2700.0,Plot area 360(301.01 sq.m.)Built Up area: 361 ...,4,4,3+,servant room,"360 Yards Duplex Villa Espace Nirvana Country,...",2.0,North,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Available for sale espace 360 yards duplex vil...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [53]:
df['sector'] = df['sector'].str.replace('nirvana country', 'sector 50')
df['sector'] = df['sector'].str.replace('dlf phase 1', 'sector 26')
df['sector'] = df['sector'].str.replace('palam vihar', 'sector 23')
df['sector'] = df['sector'].str.replace('dlf phase 2', 'sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1', 'sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar', 'sector 3a')
df['sector'] = df['sector'].str.replace('dlf phase 4', 'sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3', 'sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 3', 'sector 57')
df['sector'] = df['sector'].str.replace('rajendra park', 'sector 105')
df['sector'] = df['sector'].str.replace('dlf phase 5', 'sector 43')
df['sector'] = df['sector'].str.replace('gwal pahari', 'sector 2')
df['sector'] = df['sector'].str.replace('laxman vihar phase 2', 'sector 4')
df['sector'] = df['sector'].str.replace('uppals southend', 'sector 49')
df['sector'] = df['sector'].str.replace('sohna road', 'sector 48')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension', 'sector 3')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2', 'sector 5')
df['sector'] = df['sector'].str.replace('south city 1', 'sector 41')
df['sector'] = df['sector'].str.replace('c block sushant lok phase 1', 'sector 43')
df['sector'] = df['sector'].str.replace('palam vihar extension', 'sector 22')
df['sector'] = df['sector'].str.replace('malibu town', 'sector 47')
df['sector'] = df['sector'].str.replace('new colony', 'sector 7')
df['sector'] = df['sector'].str.replace('rajiv nagar', 'sector 13')
df['sector'] = df['sector'].str.replace('jyoti park', 'sector 7')
df['sector'] = df['sector'].str.replace('jacobpura', 'sector 12a')
df['sector'] = df['sector'].str.replace('ashok vihar', 'sector 5')
df['sector'] = df['sector'].str.replace('greenwood city', 'sector 40')
df['sector'] = df['sector'].str.replace('ansal plaza', 'sector 23')
df['sector'] = df['sector'].str.replace('new palam vihar', 'sector 110')
df['sector'] = df['sector'].str.replace('subhash nagar', 'sector 8')
df['sector'] = df['sector'].str.replace('chakkarpur', 'sector 28')
df['sector'] = df['sector'].str.replace('sushant lok phase 2', 'sector 56')
df['sector'] = df['sector'].str.replace('arjun nagar', 'sector 8')
df['sector'] = df['sector'].str.replace('Saraswati Vihar, Gurgaon', 'sector 28')
df['sector'] = df['sector'].str.replace('dayanand colony', 'sector 6')
df['sector'] = df['sector'].str.replace('adarsh nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('vishnu garden', 'sector 105')
df['sector'] = df['sector'].str.replace('ravi nagar', 'sector 9')
df['sector'] = df['sector'].str.replace('baldev nagar', 'sector 7')
df['sector'] = df['sector'].str.replace('surya vihar', 'sector 4')
df['sector'] = df['sector'].str.replace('suncity', 'sector 76')
df['sector'] = df['sector'].str.replace('madanpuri', 'sector 7')
df['sector'] = df['sector'].str.replace('shivpuri', 'sector 7')
df['sector'] = df['sector'].str.replace('krishna colony', 'sector 7')
df['sector'] = df['sector'].str.replace('valley view estate', 'sector 2')
df['sector'] = df['sector'].str.replace('bhim nagar', 'sector 6')
df['sector'] = df['sector'].str.replace('devilal colony', 'sector 9')
df['sector'] = df['sector'].str.replace('shivaji nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('dharam colony', 'sector 12')
df['sector'] = df['sector'].str.replace('garhi harsaru', 'sector 88')
df['sector'] = df['sector'].str.replace('patel nagar', 'sector 15')
df['sector'] = df['sector'].str.replace('a block sushant lok phase 1', 'sector 27')
df['sector'] = df['sector'].str.replace('mg road', 'sector 25')
df['sector'] = df['sector'].str.replace('b block sushant lok phase 1', 'sector 30m')
df['sector'] = df['sector'].str.replace('prem nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('maruti kunj', 'sector 62')
df['sector'] = df['sector'].str.replace('laxmi garden', 'sector 11')
df['sector'] = df['sector'].str.replace('gandhi nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('ambience island', 'sector 24')
df['sector'] = df['sector'].str.replace('shakti nagar', 'sector 54')
df['sector'] = df['sector'].str.replace('sohna  road', 'sector 49')
df['sector'] = df['sector'].str.replace('daulatabad', 'sector 103')
df['sector'] = df['sector'].str.replace('lajpat nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('hira nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('samaspur', 'sector 51')
df['sector'] = df['sector'].str.replace('iffco chowk', 'sector 29')
df['sector'] = df['sector'].str.replace('new palam vihar phase 2', 'sector 110')
df['sector'] = df['sector'].str.replace('rajiv chowk', 'sector 33')
df['sector'] = df['sector'].str.replace('manohar nagar', 'sector 12')
df['sector'] = df['sector'].str.replace('sheetla colony', 'sector 5')
df['sector'] = df['sector'].str.replace('block a surya vihar', 'sector 4')
df['sector'] = df['sector'].str.replace('sispal vihar', 'sector 49')
df['sector'] = df['sector'].str.replace(', delhi ncr', 'sector 63')
df['sector'] = df['sector'].str.replace('new basti', 'sector 8')
df['sector'] = df['sector'].str.replace('pratap nagar', 'sector 8')
df['sector'] = df['sector'].str.replace('west rajiv nagar', 'sector 13')
df['sector'] = df['sector'].str.replace('acharya puri', 'sector 12')
df['sector'] = df['sector'].str.replace('surat nagar phase 2', 'sector 104')
df['sector'] = df['sector'].str.replace('faridabad road', 'sector 2')
df['sector'] = df['sector'].str.replace('sushant lok', 'sector 3')
df['sector'] = df['sector'].str.replace('mayfield garden', 'sector 51')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('bhawani enclave', 'sector 61')
df['sector'] = df['sector'].str.replace('rosewood', 'sector 49')
df['sector'] = df['sector'].str.replace('new palam vihar phase 1', 'sector 110')
df['sector'] = df['sector'].str.replace('shanti nagar', 'sector 11')
df['sector'] = df['sector'].str.replace('mohan vihar', 'sector 11')
df['sector'] = df['sector'].str.replace('surat nagar', 'sector 104')
df['sector'] = df['sector'].str.replace('ats marigold', 'sector 89a')
df['sector'] = df['sector'].str.replace('vir nagar', 'sector 8')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')
df['sector'] = df['sector'].str.replace('shankar vihar', 'sector 103')

/tmp/ipykernel_337531/2327422208.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('nirvana country', 'sector 50')
/tmp/ipykernel_337531/2327422208.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dlf phase 1', 'sector 26')
/tmp/ipykernel_337531/2327422208.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('palam vihar', 'sector 23')
/tmp/ipykernel_337531/2327422208.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dlf phase 2', 'sector 25')
/tmp/ipykernel_337531/2327422208.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sushant lok phase 1', 'sector 43')
/tmp/ipykernel_337531/2327422208.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('laxman vihar', 'sector 3a')
/tmp/ipykernel_337531/2327422208.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dlf phase 4', 'sector 28')
/tmp/ipykernel_337531/2327422208.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dlf phase 3', 'sector 25')
/tmp/ipykernel_337531/2327422208.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sushant lok phase 3', 'sector 57')
/tmp/ipykernel_337531/2327422208.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('rajendra park', 'sector 105')
/tmp/ipykernel_337531/2327422208.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dlf phase 5', 'sector 43')
/tmp/ipykernel_337531/2327422208.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('gwal pahari', 'sector 2')
/tmp/ipykernel_337531/2327422208.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('laxman vihar phase 2', 'sector 4')
/tmp/ipykernel_337531/2327422208.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('uppals southend', 'sector 49')
/tmp/ipykernel_337531/2327422208.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sohna road', 'sector 48')
/tmp/ipykernel_337531/2327422208.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension', 'sector 3')
/tmp/ipykernel_337531/2327422208.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('ashok vihar phase 2', 'sector 5')
/tmp/ipykernel_337531/2327422208.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('south city 1', 'sector 41')
/tmp/ipykernel_337531/2327422208.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('c block sushant lok phase 1', 'sector 43')
/tmp/ipykernel_337531/2327422208.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('palam vihar extension', 'sector 22')
/tmp/ipykernel_337531/2327422208.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('malibu town', 'sector 47')
/tmp/ipykernel_337531/2327422208.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('new colony', 'sector 7')
/tmp/ipykernel_337531/2327422208.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('rajiv nagar', 'sector 13')
/tmp/ipykernel_337531/2327422208.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('jyoti park', 'sector 7')
/tmp/ipykernel_337531/2327422208.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('jacobpura', 'sector 12a')
/tmp/ipykernel_337531/2327422208.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('ashok vihar', 'sector 5')
/tmp/ipykernel_337531/2327422208.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('greenwood city', 'sector 40')
/tmp/ipykernel_337531/2327422208.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('ansal plaza', 'sector 23')
/tmp/ipykernel_337531/2327422208.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('new palam vihar', 'sector 110')
/tmp/ipykernel_337531/2327422208.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('subhash nagar', 'sector 8')
/tmp/ipykernel_337531/2327422208.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('chakkarpur', 'sector 28')
/tmp/ipykernel_337531/2327422208.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sushant lok phase 2', 'sector 56')
/tmp/ipykernel_337531/2327422208.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('arjun nagar', 'sector 8')
/tmp/ipykernel_337531/2327422208.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('Saraswati Vihar, Gurgaon', 'sector 28')
/tmp/ipykernel_337531/2327422208.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dayanand colony', 'sector 6')
/tmp/ipykernel_337531/2327422208.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('adarsh nagar', 'sector 12')
/tmp/ipykernel_337531/2327422208.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('vishnu garden', 'sector 105')
/tmp/ipykernel_337531/2327422208.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('ravi nagar', 'sector 9')
/tmp/ipykernel_337531/2327422208.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('baldev nagar', 'sector 7')
/tmp/ipykernel_337531/2327422208.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('surya vihar', 'sector 4')
/tmp/ipykernel_337531/2327422208.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('suncity', 'sector 76')
/tmp/ipykernel_337531/2327422208.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('madanpuri', 'sector 7')
/tmp/ipykernel_337531/2327422208.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('shivpuri', 'sector 7')
/tmp/ipykernel_337531/2327422208.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('krishna colony', 'sector 7')
/tmp/ipykernel_337531/2327422208.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('valley view estate', 'sector 2')
/tmp/ipykernel_337531/2327422208.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('bhim nagar', 'sector 6')
/tmp/ipykernel_337531/2327422208.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('devilal colony', 'sector 9')
/tmp/ipykernel_337531/2327422208.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('shivaji nagar', 'sector 11')
/tmp/ipykernel_337531/2327422208.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('dharam colony', 'sector 12')
/tmp/ipykernel_337531/2327422208.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('garhi harsaru', 'sector 88')

In [54]:
df[df['sector'] == 'new']

,property_name,property_type,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
600,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,0.67,new,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2226,4 BHK Flat in New Gurgaon,flat,dlf 76,4.00,new,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2387,4 BHK Flat in New Gurgaon,flat,sare homes,0.85,new,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3271,2 BHK Flat in New Gurgaon,flat,green court,0.38,new,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [55]:
df.loc[1087,'sector'] = 'sector 37'
df.loc[2235,'sector'] = 'sector 92'
df.loc[2766,'sector'] = 'sector 90'
df.loc[2839,'sector'] = 'sector 76'

In [57]:
df.sample(3)

,property_name,property_type,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1566,2 BHK Flat in Sector 77 Gurgaon,flat,umang winter hills,0.75,sector 77,5588.0,1342.0,Super Built up area 1342(124.68 sq.m.)Built Up...,2,2,2,not available,"Middle Floor, Sector 77 Gurgaon, Gurgaon, Haryana",7.0,North-East,1 to 5 Year Old,"['Entertainland Mall', 'Delhi Jaipur Expresswa...",Umang winter hills is one of gurgaon's most so...,"['2 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
2034,3 BHK Flat in Nirvana Country,flat,the close north,2.70,sector 50,10364.0,2605.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3+,servant room,"002, Nirvana Country, Gurgaon, Haryana",6.0,East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",Check out this 3 bhk apartment for sale in the...,"['5 Fan', '15 Light', 'No AC', 'No Bed', 'No C...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
196,4 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,6.16,sector 22,20533.0,3000.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [64]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address'],inplace=True)

/tmp/ipykernel_337531/970199603.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['property_name', 'address'],inplace=True)

In [65]:
df.duplicated().sum()

13

In [66]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)