In [1]:
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import ast

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('../data/appartments.csv').drop(22)

In [4]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."

In [5]:
df.iloc[2].NearbyLocations

"['AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56']"

In [6]:
df.iloc[2].LocationAdvantages

"{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}"

In [7]:
# 1st recommender system
df[['PropertyName','TopFacilities']]['TopFacilities'][0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

In [8]:
def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [9]:
df['TopFacilities'][0]

['Swimming Pool',
 'Salon',
 'Restaurant',
 'Spa',
 'Cafeteria',
 'Sun Deck',
 '24x7 Security',
 'Club House',
 'Gated Community']

In [10]:
df['FacilitiesStr'] = df['TopFacilities'].apply(' '.join)

In [11]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities,FacilitiesStr
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete...",Swimming Pool Salon Restaurant Spa Cafeteria S...
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","[Bowling Alley, Mini Theatre, Manicured Garden...",Bowling Alley Mini Theatre Manicured Garden Sw...
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"[Terrace Garden, Gazebo, Fountain, Amphitheatr...",Terrace Garden Gazebo Fountain Amphitheatre Pa...
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Volley Ball Court, Aerobics Ce...",Swimming Pool Volley Ball Court Aerobics Centr...
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"[Mini Theatre, Doctor on Call, Concierge Servi...",Mini Theatre Doctor on Call Concierge Service ...

In [12]:
df['FacilitiesStr'][0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

In [13]:
# tfidf vectorization
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [14]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [15]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.18809342, 0.18809342,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16873099, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27811185, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17445059, 0.17445059,
       0.15589841, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16355699, 0.29372893, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18084455, 0.18084455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17445059, 0.        , 0.24773259, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06440364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2659983 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12932284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21010446, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16522746,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25610081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15177345,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21412748, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14918792,
       0.29372893, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16355699, 0.16355699, 0.        ,
       0.        , 0.        , 0.06493586, 0.06493586, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [16]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [17]:
cosine_sim1.shape

(246, 246)

In [18]:
df[['PropertyName','PriceDetails']]['PriceDetails'][1]

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}"

In [19]:
def recommend_properties(property_name, cosine_sim=cosine_sim1):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [20]:
recommend_properties("DLF The Arbour")

           PropertyName            SimilarityScore
64      Ace Palm Floors   (63, 0.4529382062441955)
217         Yashika 104  (216, 0.4199606322926784)
93       JMS The Nation   (92, 0.4166584649363288)
154       India Rashtra   (153, 0.398954234680194)
0    Smartworld One DXP   (0, 0.38885046199432893)

In [21]:
# 2nd recommender system
import pandas as pd
import json

# Load the dataset
df_appartments = pd.read_csv('../data/appartments.csv').drop(22)

# Function to parse and extract the required features from the PriceDetails column
def refined_parse_modified_v2(detail_str):
    try:
        details = json.loads(detail_str.replace("'", "\""))
    except:
        return {}

    extracted = {}
    for bhk, detail in details.items():
        # Extract building type
        extracted[f'building type_{bhk}'] = detail.get('building_type')

        # Parsing area details
        area = detail.get('area', '')
        area_parts = area.split('-')
        if len(area_parts) == 1:
            try:
                value = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area low {bhk}'] = value
                extracted[f'area high {bhk}'] = value
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
        elif len(area_parts) == 2:
            try:
                extracted[f'area low {bhk}'] = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area high {bhk}'] = float(area_parts[1].replace(',', '').replace(' sq.ft.', '').strip())
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None

        # Parsing price details
        price_range = detail.get('price-range', '')
        price_parts = price_range.split('-')
        if len(price_parts) == 2:
            try:
                extracted[f'price low {bhk}'] = float(price_parts[0].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                extracted[f'price high {bhk}'] = float(price_parts[1].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                if 'L' in price_parts[0]:
                    extracted[f'price low {bhk}'] /= 100
                if 'L' in price_parts[1]:
                    extracted[f'price high {bhk}'] /= 100
            except:
                extracted[f'price low {bhk}'] = None
                extracted[f'price high {bhk}'] = None

    return extracted
# Apply the refined parsing and generate the new DataFrame structure
data_refined = []

for _, row in df_appartments.iterrows():
    features = refined_parse_modified_v2(row['PriceDetails'])
    
    # Construct a new row for the transformed dataframe
    new_row = {'PropertyName': row['PropertyName']}
    
    # Populate the new row with extracted features
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        new_row[f'building type_{config}'] = features.get(f'building type_{config}')
        new_row[f'area low {config}'] = features.get(f'area low {config}')
        new_row[f'area high {config}'] = features.get(f'area high {config}')
        new_row[f'price low {config}'] = features.get(f'price low {config}')
        new_row[f'price high {config}'] = features.get(f'price high {config}')
    
    data_refined.append(new_row)

df_final_refined_v2 = pd.DataFrame(data_refined).set_index('PropertyName')

In [22]:
df_final_refined_v2['building type_Land'] = df_final_refined_v2['building type_Land'].replace({'':'Land'})

In [23]:
df['PriceDetails'][10]

"{'2 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,055 sq.ft.', 'price-range': '₹ 1.05 - 1.5 Cr'}, '3 BHK': {'building_type': 'Independent Floor', 'area_type': 'Carpet Area', 'area': '1,325 - 1,525 sq.ft.', 'price-range': '₹ 1.35 - 1.84 Cr'}}"

In [24]:
df_final_refined_v2

,building type_1 BHK,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,building type_2 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,building type_3 BHK,area low 3 BHK,area high 3 BHK,price low 3 BHK,price high 3 BHK,building type_4 BHK,area low 4 BHK,area high 4 BHK,price low 4 BHK,price high 4 BHK,building type_5 BHK,area low 5 BHK,area high 5 BHK,price low 5 BHK,price high 5 BHK,building type_6 BHK,area low 6 BHK,area high 6 BHK,price low 6 BHK,price high 6 BHK,building type_1 RK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,building type_Land,area low Land,area high Land,price low Land,price high Land
PropertyName,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,None,NaN,NaN,NaN,NaN,Apartment,1370.0,1370.0,2.0000,2.40,Apartment,1850.0,2050.0,2.25,3.59,Apartment,2600.0,2600.0,3.24,4.56,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
M3M Crown,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,Apartment,1605.0,2170.0,2.20,3.03,Apartment,2248.0,2670.0,3.08,3.73,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Adani Brahma Samsara Vilasa,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,Independent Floor,1800.0,3150.0,2.43,15.75,Independent Floor,2750.0,4500.0,3.36,22.50,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,Land,500.0,4329.0,2.05,41.13
Sobha City,None,NaN,NaN,NaN,NaN,Apartment,1381.0,1692.0,1.5500,3.21,Apartment,1711.0,2343.0,1.76,4.79,Apartment,2423.0,2963.0,2.50,6.06,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Signature Global City 93,None,NaN,NaN,NaN,NaN,Independent Floor,981.0,1118.0,0.9301,1.06,Independent Floor,1235.0,1530.0,1.12,1.45,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,None,NaN,NaN,NaN,NaN,Apartment,964.0,964.0,NaN,NaN,Apartment,1127.0,1127.0,NaN,NaN,Apartment,1562.0,1562.0,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Pyramid Urban Homes 2,Apartment,335.0,398.0,23.45,0.2786,Apartment,500.0,625.0,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
Satya The Hermitage,None,NaN,NaN,NaN,NaN,Apartment,1450.0,1450.0,NaN,NaN,Apartment,1991.0,1991.0,NaN,NaN,Apartment,2639.0,4711.0,1.20,2.14,Apartment,4731.0,4731.0,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
BPTP Spacio,None,NaN,NaN,NaN,NaN,Apartment,1000.0,1079.0,NaN,NaN,Apartment,1225.0,1865.0,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
SS The Coralwood,None,NaN,NaN,NaN,NaN,Apartment,1320.0,1425.0,NaN,NaN,Apartment,1750.0,1890.0,1.10,1.19,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [25]:
categorical_columns = df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [26]:
categorical_columns

['building type_1 BHK',
 'building type_2 BHK',
 'building type_3 BHK',
 'building type_4 BHK',
 'building type_5 BHK',
 'building type_6 BHK',
 'building type_1 RK',
 'building type_Land']

In [27]:
ohe_df = pd.get_dummies(df_final_refined_v2, columns=categorical_columns, drop_first=True)

In [28]:
ohe_df.fillna(0,inplace=True)

In [29]:
ohe_df

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,price low 3 BHK,price high 3 BHK,area low 4 BHK,area high 4 BHK,price low 4 BHK,price high 4 BHK,area low 5 BHK,area high 5 BHK,price low 5 BHK,price high 5 BHK,area low 6 BHK,area high 6 BHK,price low 6 BHK,price high 6 BHK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,area low Land,area high Land,price low Land,price high Land,building type_1 BHK_Service Apartment,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0.0,0.0,0.00,0.0000,1370.0,1370.0,2.0000,2.40,1850.0,2050.0,2.25,3.59,2600.0,2600.0,3.24,4.56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
M3M Crown,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1605.0,2170.0,2.20,3.03,2248.0,2670.0,3.08,3.73,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
Adani Brahma Samsara Vilasa,0.0,0.0,0.00,0.0000,0.0,0.0,0.0000,0.00,1800.0,3150.0,2.43,15.75,2750.0,4500.0,3.36,22.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,500.0,4329.0,2.05,41.13,False,False,False,True,False,False,True,False,False,False,False
Sobha City,0.0,0.0,0.00,0.0000,1381.0,1692.0,1.5500,3.21,1711.0,2343.0,1.76,4.79,2423.0,2963.0,2.50,6.06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
Signature Global City 93,0.0,0.0,0.00,0.0000,981.0,1118.0,0.9301,1.06,1235.0,1530.0,1.12,1.45,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,True,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.0,0.0,0.00,0.0000,964.0,964.0,0.0000,0.00,1127.0,1127.0,0.00,0.00,1562.0,1562.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
Pyramid Urban Homes 2,335.0,398.0,23.45,0.2786,500.0,625.0,0.0000,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
Satya The Hermitage,0.0,0.0,0.00,0.0000,1450.0,1450.0,0.0000,0.00,1991.0,1991.0,0.00,0.00,2639.0,4711.0,1.20,2.14,4731.0,4731.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
BPTP Spacio,0.0,0.0,0.00,0.0000,1000.0,1079.0,0.0000,0.00,1225.0,1865.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False
SS The Coralwood,0.0,0.0,0.00,0.0000,1320.0,1425.0,0.0000,0.00,1750.0,1890.0,1.10,1.19,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,False,False,False,False,False,False,False,False,False,False,False

In [30]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
ohe_df_normalized = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=ohe_df.index)

In [31]:
ohe_df_normalized.head()

,area low 1 BHK,area high 1 BHK,price low 1 BHK,price high 1 BHK,area low 2 BHK,area high 2 BHK,price low 2 BHK,price high 2 BHK,area low 3 BHK,area high 3 BHK,price low 3 BHK,price high 3 BHK,area low 4 BHK,area high 4 BHK,price low 4 BHK,price high 4 BHK,area low 5 BHK,area high 5 BHK,price low 5 BHK,price high 5 BHK,area low 6 BHK,area high 6 BHK,price low 6 BHK,price high 6 BHK,area low 1 RK,area high 1 RK,price low 1 RK,price high 1 RK,area low Land,area high Land,price low Land,price high Land,building type_1 BHK_Service Apartment,building type_2 BHK_Independent Floor,building type_2 BHK_Service Apartment,building type_3 BHK_Independent Floor,building type_3 BHK_Service Apartment,building type_3 BHK_Villa,building type_4 BHK_Independent Floor,building type_4 BHK_Villa,building type_5 BHK_Independent Floor,building type_5 BHK_Villa,building type_6 BHK_Villa
PropertyName,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,-0.252266,-0.169584,-0.105197,-0.082332,1.223499,1.020101,-0.173712,1.158423,0.553787,0.370864,0.807098,0.515061,0.602838,0.212073,0.383381,0.242019,-0.468954,-0.460463,-0.248049,-0.235915,-0.125582,-0.118934,-0.077649,-0.073387,-0.105157,-0.10253,-0.090521,-0.082725,-0.447044,-0.371421,-0.195703,-0.240489,-0.111111,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
M3M Crown,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.293086,0.472749,0.772095,0.342903,0.382746,0.243172,0.341443,0.108677,-0.468954,-0.460463,-0.248049,-0.235915,-0.125582,-0.118934,-0.077649,-0.073387,-0.105157,-0.10253,-0.090521,-0.082725,-0.447044,-0.371421,-0.195703,-0.240489,-0.111111,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Adani Brahma Samsara Vilasa,-0.252266,-0.169584,-0.105197,-0.082332,-0.893541,-0.896660,-0.283546,-0.387986,0.500583,1.304803,0.933110,4.253341,0.696627,1.056178,0.414835,3.124152,-0.468954,-0.460463,-0.248049,-0.235915,-0.125582,-0.118934,-0.077649,-0.073387,-0.105157,-0.10253,-0.090521,-0.082725,0.369534,1.828502,0.643875,7.635886,-0.111111,-0.289310,-0.063888,2.683282,-0.063888,-0.171139,3.924283,-0.236208,-0.111111,-0.216353,-0.063888
Sobha City,-0.252266,-0.169584,-0.105197,-0.082332,1.240497,1.470610,-0.198425,1.680336,0.405879,0.619632,0.464065,0.883970,0.492166,0.373342,0.189416,0.483000,-0.468954,-0.460463,-0.248049,-0.235915,-0.125582,-0.118934,-0.077649,-0.073387,-0.105157,-0.10253,-0.090521,-0.082725,-0.447044,-0.371421,-0.195703,-0.240489,-0.111111,-0.289310,-0.063888,-0.372678,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888
Signature Global City 93,-0.252266,-0.169584,-0.105197,-0.082332,0.622383,0.667529,-0.232468,0.295011,-0.100626,-0.070634,0.016022,-0.142827,-1.022842,-0.943016,-0.465873,-0.490563,-0.468954,-0.460463,-0.248049,-0.235915,-0.125582,-0.118934,-0.077649,-0.073387,-0.105157,-0.10253,-0.090521,-0.082725,-0.447044,-0.371421,-0.195703,-0.240489,-0.111111,3.456497,-0.063888,2.683282,-0.063888,-0.171139,-0.254824,-0.236208,-0.111111,-0.216353,-0.063888

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix
cosine_sim2 = cosine_similarity(ohe_df_normalized)

In [33]:
cosine_sim2.shape

(246, 246)

In [34]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim2[ohe_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = ohe_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('M3M Golf Hills')

                PropertyName  SimilarityScore
0    AIPL The Peaceful Homes         0.955462
1         Smartworld One DXP         0.954670
2             Unitech Escape         0.953092
3                M3M Capital         0.951156
4                 BPTP Terra         0.943128
..                       ...              ...
240              Golden Park        -0.522391
241      Satya Merano Greens        -0.523660
242       ROF Normanton Park        -0.525129
243          BPTP Green Oaks        -0.525286
244           JMS The Nation        -0.526287

[245 rows x 2 columns]

In [35]:
# 3rd recommender systems
df[['PropertyName','LocationAdvantages']]['LocationAdvantages'][0]

"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"

In [36]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [37]:
# Extract distances for each location
location_matrix = {}
for index, row in df.iterrows():
    distances = {}
    for location, distance in ast.literal_eval(row['LocationAdvantages']).items():
        distances[location] = distance_to_meters(distance)
    location_matrix[index] = distances

# Convert the dictionary to a dataframe
location_df = pd.DataFrame.from_dict(location_matrix, orient='index')

# Display the first few rows
location_df.head()

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,Indira Gandhi International Airport,Hamoni Golf Camp,Fun N Food Waterpark,Accenture DDC5,DPSG Palam Vihar Gurugram,"Park Hospital, Palam Vihar",Palam Vihar Halt Railway Station,Dwarka Sector 21 Metro Station,Dwarka Expressway,Fun N Food Water Park,Tau DeviLal Sports Complex,Hyatt Place,Altrade Business Centre,AIPL Business Club Sector 62,Heritage Xperiential Learning School,CK Birla Hospital,Paras Trinity Mall Sector 63,Rapid Metro Station Sector 56,De Adventure Park,Golf Course Ext Rd,DoubleTree by Hilton Hotel Gurgaon,KIIT College of Engineering Sohna Road,Mehrauli-Gurgaon Road,Nirvana Rd,TERI Golf Course,The Shikshiyan School,WTC Plaza,Luxus Haritma Resort,BSF Golf Course,Rions Hospital,Gurgaon,Dwarka Sector 21,Nehru Stadium,Fun N Food WaterPark,IGI Airport,Vasant Kunj,Pranavananda Int. School,DLF Site central office,Holiday Inn Gurugram Sector 90,Krishna Hospital,Royal Institute Of Science,Sapphire 83 Mall,NH48,Garhi Harsaru Junction,Manesar Golf Course,AapnoGhar,Vega Schools NH-8,DLF Corporate Greens,Miracles Apollo Cradle Hospital,Hyatt Regency Gurugram,NH 48,Golden Greens Golf & Resorts Limited,Mount Olympus Junior School,Miracles Apollo Hospital,NH -8,"Savoy Suites, Manesar",Golden Greens Golf & Resorts,IMT Manesar,Amity University Gurugram,Golf Course Extension Road,"Dwarka Expy, Sector 109","Euro International School, Sector- 109",Jai Sai Ram Hospital,Aryan Hospital,Idea Cosmic Plaza,Indira Gandhi Intl Airport,Royal Institute Of Science & Management,Pataudi Road,Holiday Inn Sector 90,RPS International School,Aarvy Healthcare Hospital,Iris Broadway Mall,Imperia Mindspace,AIPL Business Tower,Heritage School,"Lotus Valley Intl School, Gurgaon",Gurugram University,Sector 55-56 Metro Station,Omaxe Gurgaon Mall,Sushant University,"Badshahpur Sohna Rd Hwy,Sector 48",Naurangpur Cricket Stadium,Naurangpur Road,National Highway 48,Vatika Town Square-INXT,Ompee International School,Manesar Bus Stand,Yashlok Medical Centre,Euro International School,WorldMark Gurgaon,Capital Cyberscape,The Shriram Millennium School,DoubleTree by Hilton Hotel,Badshahpur Sohna Hwy,Nakhrola Stadium,Delhi - Jaipur Expressway,Vatika Town Square-INXT Mall,Savoy Suites,Bal Bharati Public School,Vatika Business Centre,Indira Gandhi Int. Airport,St. Xavier's High School,Miracles Apollo Cradle,Ambience Mall New,NH8,Hyatt Regency Gurgaon,Delhi Public School,Elan Miracle Mall,Miracles Apollo Cradle Spectra Hospital,Agri Business Management Collage,Delhi Jaipur Expressway,Grand Hyatt Gurgaon,Duke Horse Riding Club,PVR Drive In Cinema,W Pratiksha Hospital,Metro World Mall,Unicosmos School,Faridabad Gurgaon Road,Sohna Road,Bestech Business Tower,Appu Ghar,SkyJumper Trampoline Park,Axis Bank,KMP Expressway,Karma Lakelands,Jungle Safari & Trails,DPS Manesar,Medanta Hospital,Faridabad - Gurgaon Road,Lingaya's Lalita Devi Institute,ASF Insignia SEZ,Banjara Market Gurugram,Central Plaza Mall,"Paras Hospitals, Gurgaon",Badshahpur Sohna Rd Hwy,Vega School,Indian School of Hospitality,Vatika City Centre,Aatish Hospital,Info Technology Park Phase 2,Huda Metro Station,Southern Peripheral Rd,Global Ways School,Radisson Hotel,NH 248A,Sector 55/56 Metro Station,Mavens Inn,Sanar International Hospital,Sector 53-54 Metro Station,"IILM University, Gurugram",The Banyan Tree World School,The Big Tree Cafe,DLF Golf and Country Club,"Delhi Public School, Sector 84",Aarvy Hospital,DPG Degree College,Shivani public school,Baghera University,Kutumbh Hospital,Bijwasan Railway Station,Global Foyer Mall,Phase 2 Metro Station,Gurgaon Dreamz Mall,"Metro Hospital, Palam Vihar",Delhi Ajmer Expressway,Infinity Business Park,Huda metro station,Rion's Hospital,"Euro International School, Sector- 109.",Golf Course Ext Road,"Heritage Xperiential Learning, CRPF Rd",Sector 54 Chowk Metro Station,Gurgaon - Delhi Expy,Genesis Hospital Sector 84,DPGITM Engineering College Sector 34,Sapphire 83 Mall Sector 83,Holiday Inn Hotel Sector 90,SkyJumper Trampoline Park Gurgaon,National Tennis Academy Sector 98,NH-8 Delhi Jaipur Highway,Nouveau Medics Multispeciality OPD,Heritage Village Resort & Spa,Sector 86 Road,Genesis Hospital,Delh-Ajmer Expy,DPG Institute of Technology,Medanta -The Medicity,Airia Mall,Amma Hospital,DPS International Edge,Eros City Square,Splendor Trade Tower,Narayana Junior College,Sector 55 Metro Station,Dharampur Main Road,Oyster's Water Park,Vivanta Dwarka New Delhi,DLF Corporate Park,GD Goenka World School,KR Mangalam University,Smart View Hotel and Resort,Central Park Flower Valley,Shopping complex,Delhi Public School Sector 84,Central Peripheral Road,Nakhrola Stadium Sector 81A,NH 08,Imt Manesar,G D Goenka University,Fly India Adventure Resort,Vardaan Hospital,IMT Office Sohna,JMS Marine Square Mall,Vibrant Hospital,Prime Scholars Int. School,Ramgarh Farms & Resort,Basai Road,Shree Krishna Hospital,The Esplanade Mall,GEMS International School,Pranavananda International School,Greenway Hospital,National Tennis Academy,NH-8,Paras Trinity Mall,Rajesh Pilot Road,Scottish High International School,KIIT College of Engineering,The Vivekananda School,Southern Peripheral Road,Holiday Inn Express Gurugram Sector 50,Early Basket Grocery shop,Aradhya Cricket Club Gurgaon,Imperial Heritage School,Daultabad Village Park,Skylark Cricket Academy,Yashroop Hospital,Gurgaon Old Railway Station,Domino's Pizza,Conscient One Mall,Emerald Plaza Shopping Mall,Pawlywoof - Dog Park,SCC Drive-In Cinema,"Lemon Tree Hotel, Sohna Road",Shiksha Bharti Public School,Holiday Inn Express Gurugram,Sahara Mall,Dhanwapur Road,Govt. PG College,Basai Dhankot,Park Inn,IFFCO Chowk Metro Station,The Executive Centre,"Dwarka Expy, Sector 88","Euro Int School, Sector 37D, Gurugram",Reliance Trends Newtown Square Mall,SGT University,Medanta-The Medicity,SGT Hospital 1,Suncity School,Green Field School,Narayana E Techno,Alpine Convent School,Little E Step –Pre School,Sheetla Mata Mandir,Captain Chandan Lal Marg,CD International School,Raheja Mall,Basai Dhankot Railway Station,First Step Play School,Sri Ma Montessori International,Dwaraka Expressway,Ansal Plaza,Proposed Metro Station,Delhi International Airport,KMP Corridor,Vega Schools Sector 48,Cloudnine Hospital Sector 47,PVR Drive In Theatre,City Hospital,"NH 352W, Pataudi","Pathfinder Global School, Pataudi",Vistar Complex,BML Munjal University (BMU),Sector 55-56 Metro station,Bestech Central Square Mall,ORCHIDS The International School,Marengo Asia Hospitals,Sector 42-43 Rapid Metro,Sector 53-54 Rapid Metro,Bank Of Baroda,HDFC Bank ATM,Muincipal Corporation of Gurugram,One Horizon Center Bus Stop,Shalom Hills International School,Satyam Medicare Hospital,Anand Preschool,Choice pharmacy,Qutub Plaza,Sunset point,EPF Regional Office,IFFCO Chowk,Kingdom of Dreams,Gaytri Public School,KIIT College,SPM Hospital,Sealdah Railway Station,International Airport,Lemon Tree Hotel,"CK Birla Hospital, Gurgaon",Golf Pavilion,Golf Course Road,Ardee Mall,Shiv Nadar School,NH 148A,Ambience Public School,Heritage Intl Xperiential School,Summer Fields School,Primamed Super Speciality Hospital,Uma Sanjeevani Health Centre,Anya Gurgaon,Hotel Golf View Suites,Apollo Pharmacy,Rx Pharmacy,Sector 42/43 Bus Stand,Genpact Chowk Bus Stop,Huda City Centre Metro Station,Sector 53 Metro Station,ICICI Bank ATM,Bharat Petroleum Retail Outlet,DLF Linear Park,Le Meridien Gurgaon,Sector 42-43 Metro Station,Faridabad - Gurgaon Rd,Ambience Mall,Fun N Food Village,F9 Go Karting Gurgaon,Proposed Metro corridor,N.H-8,Shiskshantar,DPS,Amity,Pathways,GD Goenka,Medicity,Artemis,"Max, Fortis",Apollo,Paras Trinity Shopping Mall,Swastik Multispeciality Hospital,AIPL Business Co Working Space,Lemon Tree Hotel Sector 60,MKD Hospital,PVR Drive in Theatre,Sant Soordas Sihi Metro Station,De Adventure Amusement Park,Vatika Business Park Sector 49,"Suncity School, Sector 37D",The Signature Advanced Super Speciality,Gurugram University Kankrola,"Candor TechSpace, Sector 48",IndusInd Bank ATM,Cherub's Cradle,Mavens Orange - Hotel,Learning Stars School,State Bank of India,Deerika HyperMart,Triangular Park,Artimis hospital,Sector 45 SO Post Office,FUEL NATION,HSBC,Women Police Station,Best IVF Centre,Huda City Centre,Gurugram Public School,Shikshantar - Primary School,Mamta Hospital,IG International Airport,Omaxe City Centre,DLF Grand Mall,Arvy Hospital,Matrikiran School,DLF Cyber City,Vatika Town Square,Global city centre,Sohna road dhunela,Gd goenka university,Vardaan hospital and trauma centre,Maharana pratap school,Sector 55-56 metro,Garhi harsaru railway station Gurgaon,HUB 66,Sealdah,Sector 55-56 Rapid Metro Station,Hasanpur,The Oberoi,"Euro Intl School, Sector- 109",Najafgarh Kapashera Road,Dwarka Sector 21 Metro station,Hong Kong Bazaar,Bharti International Convent School,"Badshahpur Sohna Rd Hwy, Sector 68",Ashoka International School,The Oberoi Gurgaon,GD Goenka Public School,Chauma Road,Chirag Hospital,Sector-21 Metro Dwarka,AIPL Joy Street Mall,Radisson Hotel Sohna Road,iON Digital Zone (Gurugram),HUDA Mini Golf Course,IMT Road,National Highway 48,Sohna Gurgaon Road,Spaze Itech Park,"Pallavan PreSchool, Sohna Road",Radisson Hotel Gurugram Sohna Road,Polaris Hospital,RBSM Public school,Health Care Pharmacy,Sector 54 Chowk,EuroKids Preschool Suncity,YES Bank ATM,Suncity School Gurgaon,Suncity Shopping Complex,Vallores Pre School,Umkal Hospital,Haryana City Gas,Marigold Secondary School,Alpine Hospital,Pushpanjali Hospital,Golf Course Extension Rd,Country Inn,Westin,The Millenium School,Rajiv Chowk - Sohna Highway,KMP corridor,Central Park Resorts,GD Goenka University,Swastik Hospital Sec 66,Adarsh Senior Secondary School,Golf Course Extension,"International Tech Park Gurgaon,",Sector 55-56 Metro,"Surajgarh Gurgaon, Golf Course Ext Rd",Ananta Hospital,Indus World School,Golf Corse Ext. Rd.,National Highway-48,Prime Scholars International School,"Dwarka Expy, Dhanwapur Village",Shri Balaji’s Multispeciality Hospital,"Euro International School, Sector 37D","Delhi Public School, Sector 103","Park Inn, Gurgaon",DLF World Tech Park,Star Mall,The Hive Shopping Mall,"NH-8, IMT Manesar",Yaduvanshi Shiksha Niketan,Royal Institute Of Science and Mgt,Newtown Square Mall,NH 352W,Eros Corporate Park,Manesar Road,"Euro International School, Sec 84",Huda Metro Station (Gurugram),InfinityS Badminton Academy,Sanskar Bharti Public School,"Manipal Hospital, Gurugram","HUDA Market, Sector 14",Delhi Gurgaon Expressway,SCC Rooftop Drive-In,"The Oberoi, Gurgaon",Gurugram Railway Station,Kings International School,HUDA Market,Basai Metro Station,CBR Cricket Ground,Rapid Metro Sector 55-56,Kunskapsskolan School,Omaxe Celebration Mall,"Gurgaon - Delhi Expy, Sector 75A",International Tech Park Gurgaon,Shalom Presidency School,Sector 55-56 Rapid Metro,Jinga Lala Theme Park Gurgaon Delhi,"Pataudi Rd, Sector 95B",RELIANCE TRENDS Newtown Square Mall,Aarvy Healthcare Super Speciality,Approved Sector 37 Mero Station,Signature Hospital,Xavier’s International,Alpine School,Esplanade Mall,Sector 10 Market,Blue Bells Public School,infinity Business Park,Medanta The Medicity,Galleria 108 Mall,Manipal Hospital,"Vivanta New Delhi, Dwarka",Bharat Ram Global School,Canara Bank ATM,Yes Bank,Arc Hospital,Canara Bank,Axis Bank ATM,City Square,Shishu Kalyan School,Rathore IMT Hospital,DSD College,Patil Station,Amity University,ICFAI University,Indira Gandhi Airport,Sapphire 83,Cambridge Montessori,Hyatt Regency,Rao Bharat Singh International School,Aarvy Healthcare,"NH-8, Imt Manesar",Aapno Ghar,Cambridge College Of Education,Iffco Chowk,"Euro International School, Sector 84",Dharampeth Main Road,Gurgaon railway station,Dwarka sector 21 metro station,Old Delhi Gurgaon Road,Rotary Public School,Candor Techspace,"Manipal Hospital, Palam Vihar",Moulsari Avenue,"Adarsh public school,Garhi Harsaru",PHC Garhi Harsaru,Excellere World School,Aman Hospital & Surgical Centre,Neemrana Palace,K. R. Mangalam University,Global City Centre,Vishwas Hospital,Ibis Hotel,Horizon 1 Mall,Sector 42-43 Metro station,Ernst & Young,Paras Hospital,Gurgaon Faridabad Highway,"Mount Olympus School, Sec 79","Singhania University, Manesar",Capital Business Park,Old Sohna Dhani Road,GD Goenka Signature School,Vardaan Hospital & Trauma Centre,Public Bazar,GD Goenka School,Vatika Business Park,Bharat Petrol Pump,The Millennium School,IndusInd Bank,Artemis Hospital,Tau Devi Lal Sports Complex,Children Park,Medanta Dialysis Center,"Central Park, Sohna Rd","HDFC Bank ATM, Dhunela Ghamroj",Ashiana Anmol Kid Centric Homes,"Indianoil, Sohna - Gurgaon Rd",Taj Hotel & Family Restaurant,V-Square Sohna New Residential,G D Goenka World School,"The Phoenix Project, Sohna - Gurgaon Rd",Signature Global Park,Signum 36,"Kotak Mahindra Bank, MBS Tower","Pasco Automobiles, Alipur, Sohna",Sohna Bus Stand,Imperio School,Ektaa Hospitals,Vipul Trade Business Centre,Radisson Hotel Gurugram,Airia Mall Sector 68,Damdama More,Civil Hospital,K.R. Mangalam University,Western Peripheral Expressway,Bhondsi Nature Park,Enkays Hospital,"Lemon Tree Hotel,",Ram Krishna Public School,Aravalli Hill View Point,Gurugram Global Heights School,Satya The Hive Mall,Gurugram Road,The Signature Super Speciality Hospital,Sunrise University,Country Inn & Suites by Radisson,Yonex Badminton Stadium,Grand Hyatt,Au Grand Air,Indira Gandhi Eye Hospital,Double Tree by Hilton,Swastik Hospital,Jinaglala Theme Park,Scottish International School,Ap Sports cricket ground,Nischay Cricket Academy,DLC Cricket Ground,Drona Sports Village,Ramada by Wyndham Gurgaon,Mehrauli-Gurgaon Rd,Surajgarh Gurgaon,Apex Plus Hospital,ZEN Golf Range & Academy,The Banyan Tree Hiking Area,MG Road,Plaza Mall,MGF Metropolitan Mall,Lancers International School,Gurjar Samrat Jaipal Khatana Marg,Signature Global Infinity Mall Sohna,Vidya Niketan Sr Sec School,Sanjivani Hospital,Spectra Hospital,Golf Course Extn Road,"Tulip Violet Society, Sector 69","Spaze Palazo, Golf Course Ext Rd",Federal Bank Sector 71,Kunskapsskolan International,"Southern Peripheral Rd, Gurugram",Ektaa Hospitals Main Sohna Rd,Central Bank Of India Sohna Rd,Sanjeevani Hospital - Child Specialist,VATIKA BUSINESS PARK Sohna Rd,"IndianOil, Hasanpur","The Medicity, Spaze iTech Park","Axis Bank, Sohna Rd",Shambhu Dayal High School,Global City Centre Mall,Vardaan Hospital and Trauma Centre,Ascendas OneHub Gurgaon,IRIS Broadway Mall,Flying Wings Badminton Academy,Saraswati Model School,Orchid Business Park,Farrukh Nagar Railway Station,Medanta - The Medicity,M3m 65th Avenue Mall,DPS International School,Rapid Metro Sector 56,Sneh Hospital,Gems International School,National Highway 8,Appu Ghar Water Park,Tennis Vidyalaya (Tennis Academy),Zooper India Trampoline Park,Teri Golf Course,"Park Dr, DLF Phase 5",Paras Hospitals,Heritage badminton academy,Green Field Public School,Kadipur Industrial Area,Spazedge IT Park,JMD Megapolis,Sapphire Mall,"More Hypermart , Vipul business park",Basant Valley Global School,The Paras World School,Vipul Trade Centre,"WorldMark Gurgaon, Maidawas Rd",Artemis Hospital Gurgaon,"Western Peripheral Expy, Gurugram",Raghunath Bal Vidya Mandir School,ESIC Hospital,S N International School,Infinitys Badminton Academy,Country Inn and Suites by Radisson,Sector 29 Gurgaon Pubs and Bars,Emaar Business Park,"Southern Peripheral Rd, Dhani",Omaxe City Centre Mall,"Badshahpur Sohna Rd Hwy, Malibu Town",Ektaa Hospital,St. Xavier's School,PVR Drive In Theater,American Express,IDFC FIRST Bank,Sector 42-43,Sector 53-54,MGF Megacity Mall,Fortis hospital,Pataudi road,Dwarka expressway,Double Infinity market,Bamroli Cricket Ground,Aman Hospital,Kidzee,Paras Trinity,Golf course extension road,AIPL Business Club,Sector 55-56 rapid metro station,Narayana e-Techno School - Manesar,"HDFC Bank, Pataudi Rd","SS Omnia, Sector 86",Canara Bank - Nawada Fatehpur,"ICICI Bank ATM, Sector 86",Silver Streak Multi Speciality,RHM Public School,Minda Industries Nawada Fatehpur,"Numberdar market, IMT Manesar","Sodhi's Supermarket, Sector 82",M3M SCO Shop cum Office,Sector 42-43 Rapid Metro Station,Quality Inn Gurgaon,Minda Industries Limited,Central Park II Road,Omex City Centre Mall,Damdama Lake Rd,Sohna Hill Viewpoint,KR Mangalam University Sohna,Country Inn & Suites By Radisson,Hero Honda Chowk,Jagdish Super Market,Gyaananda School,Bharat Petroleum Shree Shyam Filling,"The Club, International City",Conscient One,"ICICI BANK ATM, Annapurna MKT",ESIC Dispensary,Canara Bank New Palam Vihar,Dwarka,Radha Krishan Mandir,Daultabad Stadium,Gurgaon Gramin Bank,IGIA Airport,SCR Model School,Golden Tulip Suites Gurgaon,South point Mall,Pathways School Gurgaon,Kidzee Sec-93,Jhankar Group of Institutions,Heritage Badminton Academy,Dwarka Expy/Northern Peripheral Rd,Dwarka expressway Basai crossing,"Euro Intl School, Sector 37D, Gurugram",Sethi Hospital,HDFC Bank,The Sixth Element School,K.R.Mangalam World School,Sushil Park,Peer Baba Ki Mazar,Punjab National Bank,CoNexus.Life B35,Medhaam Pre School & Daycare,Moksh Wellness Pvt Ltd.,Marriott Courtyard,World Tech Park,Athena,Bharat Petroleum Petrol Pump,Sanskar Jyoti School,Arc Multi Speciality Hospital,NH-48,Narayana e Techno School,"Medeor Hospital, Manesar",Guls' Kitchen,The Nook,Open Tap,Frescos,Subway,BOB ATM,PNB ATM,HDFC bank ATM,YES bank ATM,Citibank ATM,Gurugram Hospital,Govind Hospital,Manish Gallexie 91,Silver Streak Multi Speciality Hospital,Holiday Inn Gurugram,NH-8 IMT Manesar,Airport,Vatika Sector Road,Gurugram University Sector 87,CNG Petrol Pump,Miracles Apollo Cradle/Spectra Hospital,Vivek Model School,Dwarka Expressway Link Road,McDonald's India 24 Hours,Garhi Budhera Road,Iris Broadway Gurugram,iGrow Montessori Play School,Matrikiran High School,Badsa AMS Hospital,GlobalHealthcare Multispeciality,Cricket Academy,V'Lante Mall,NH 48 Gurugram,Patli Railway Station,V Club,"Fitso Sector 48 Spuddy, Badminton",Lotus Valley International School,Badshapur Sohna Highway,Golf Course Rd,Bharat Singh fuel company,Basai Enclave Park,CANARA BANK,Bank Of Baroda ATM,The Holy Kingdom Public School,Shiv Mandir,Open gym garden,KFG sports club Parking,ESIC HOSPITAL,Sector 37 Police Station,Alfaa Health Care Hospital,Euro Intl School Sec-51,Mall Fifty One,"NH 8, Sector 15 Part 2",K.D. Hospital,Gurgaon Road,Saint Paul's School,Indus valley Public School,MDS Public School,Signature Super Speciality Hospital,Harsaru Village Bus Stop,Health care pharmacy,Jadon Pharmacy,JMS Crosswalk,Essar Petrol Pump,The Heritage Pride Modern School,SS Omnia Mall,Miracles Apollo Cradle / Spectra,Gurgaon Toll,Propose Metro Station,Rajiv Chowk,Lions Public School,M3M Cosmopolitan,M3M International Financial Center (IFC),"Badshahpur Sohna Rd Hwy, Haryana",Holiday Inn Express Gurugram Sec 50,"NH 48, Sector 78",ICICI ATM,Sai Sports Club cricket ground,Silver Streak Hospital,Gurukul Preschool,HP PETROL PUMP Unnamed Rd,INOX Cinema,Nawada Cricket Accadmy,Arc Multi Speciality,Sanjeevani Hospital,Baba Kanala Chowk,Pataudi Rd,Dronacharya College of Engineering,Netaji Subhash Marg,"Euro International School, sector- 51",NH 248 A,NH 248,Faridabad,Delhi-Mumbai Expressway,IMT Sohna,Kundli Manesar Palwal Expressway,KR Mangalam,SCJ Academy,Taj,Damdama Lake,Ascendas OneHub Gurgaon Business Park,GD Goenka High School,"Badshahpur Sohna Rd Hwy, Rajoria Ngr","GD Goenka University, Gurugram",Jhankar Senior Secondary School,Entertainland Mall,Aravalli Hills,Delhi,Red Roses Public School,Delhi Jaipur Highway,Iffco Chowk Metro Station,Galleria Market,Fortis Memorial Research Institute,The Westin Hotel,BM College of Technology & Mgmt,NeoSquare Shopping Mall,Glorious World School,MG Road Metro Station,Lovely Public School,AIPL Business Centre,Signature Advanced Hospital,"iON Digital Zone, Gurgaon",Sapphire 93 Mall,RPS International School Sector 89,Signature tower,Jharsha Chowk,Umang Bhawaj Chawk,NH 8,Basai Dhancourt Railway 

In [38]:
location_df.columns[10:50]

Index(['Indira Gandhi International Airport', 'Hamoni Golf Camp',
       'Fun N Food Waterpark', 'Accenture DDC5', 'DPSG Palam Vihar Gurugram',
       'Park Hospital, Palam Vihar', 'Palam Vihar Halt Railway Station',
       'Dwarka Sector 21 Metro Station', 'Dwarka Expressway',
       'Fun N Food Water Park', 'Tau DeviLal Sports Complex', 'Hyatt Place',
       'Altrade Business Centre', 'AIPL Business Club Sector 62',
       'Heritage Xperiential Learning School', 'CK Birla Hospital',
       'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56',
       'De Adventure Park', 'Golf Course Ext Rd',
       'DoubleTree by Hilton Hotel Gurgaon',
       'KIIT College of Engineering Sohna Road', 'Mehrauli-Gurgaon Road',
       'Nirvana Rd', 'TERI Golf Course', 'The Shikshiyan School', 'WTC Plaza',
       'Luxus Haritma Resort', 'BSF Golf Course', 'Rions Hospital', 'Gurgaon',
       'Dwarka Sector 21', 'Nehru Stadium', 'Fun N Food WaterPark',
       'IGI Airport', 'Vasant Kunj', 'Pranavananda Int. School',
       'DLF Site central office', 'Holiday Inn Gurugram Sector 90',
       'Krishna Hospital'],
      dtype='object')

In [39]:
location_df.index = df.PropertyName

In [40]:
location_df.head()

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expy,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,Indira Gandhi International Airport,Hamoni Golf Camp,Fun N Food Waterpark,Accenture DDC5,DPSG Palam Vihar Gurugram,"Park Hospital, Palam Vihar",Palam Vihar Halt Railway Station,Dwarka Sector 21 Metro Station,Dwarka Expressway,Fun N Food Water Park,Tau DeviLal Sports Complex,Hyatt Place,Altrade Business Centre,AIPL Business Club Sector 62,Heritage Xperiential Learning School,CK Birla Hospital,Paras Trinity Mall Sector 63,Rapid Metro Station Sector 56,De Adventure Park,Golf Course Ext Rd,DoubleTree by Hilton Hotel Gurgaon,KIIT College of Engineering Sohna Road,Mehrauli-Gurgaon Road,Nirvana Rd,TERI Golf Course,The Shikshiyan School,WTC Plaza,Luxus Haritma Resort,BSF Golf Course,Rions Hospital,Gurgaon,Dwarka Sector 21,Nehru Stadium,Fun N Food WaterPark,IGI Airport,Vasant Kunj,Pranavananda Int. School,DLF Site central office,Holiday Inn Gurugram Sector 90,Krishna Hospital,Royal Institute Of Science,Sapphire 83 Mall,NH48,Garhi Harsaru Junction,Manesar Golf Course,AapnoGhar,Vega Schools NH-8,DLF Corporate Greens,Miracles Apollo Cradle Hospital,Hyatt Regency Gurugram,NH 48,Golden Greens Golf & Resorts Limited,Mount Olympus Junior School,Miracles Apollo Hospital,NH -8,"Savoy Suites, Manesar",Golden Greens Golf & Resorts,IMT Manesar,Amity University Gurugram,Golf Course Extension Road,"Dwarka Expy, Sector 109","Euro International School, Sector- 109",Jai Sai Ram Hospital,Aryan Hospital,Idea Cosmic Plaza,Indira Gandhi Intl Airport,Royal Institute Of Science & Management,Pataudi Road,Holiday Inn Sector 90,RPS International School,Aarvy Healthcare Hospital,Iris Broadway Mall,Imperia Mindspace,AIPL Business Tower,Heritage School,"Lotus Valley Intl School, Gurgaon",Gurugram University,Sector 55-56 Metro Station,Omaxe Gurgaon Mall,Sushant University,"Badshahpur Sohna Rd Hwy,Sector 48",Naurangpur Cricket Stadium,Naurangpur Road,National Highway 48,Vatika Town Square-INXT,Ompee International School,Manesar Bus Stand,Yashlok Medical Centre,Euro International School,WorldMark Gurgaon,Capital Cyberscape,The Shriram Millennium School,DoubleTree by Hilton Hotel,Badshahpur Sohna Hwy,Nakhrola Stadium,Delhi - Jaipur Expressway,Vatika Town Square-INXT Mall,Savoy Suites,Bal Bharati Public School,Vatika Business Centre,Indira Gandhi Int. Airport,St. Xavier's High School,Miracles Apollo Cradle,Ambience Mall New,NH8,Hyatt Regency Gurgaon,Delhi Public School,Elan Miracle Mall,Miracles Apollo Cradle Spectra Hospital,Agri Business Management Collage,Delhi Jaipur Expressway,Grand Hyatt Gurgaon,Duke Horse Riding Club,PVR Drive In Cinema,W Pratiksha Hospital,Metro World Mall,Unicosmos School,Faridabad Gurgaon Road,Sohna Road,Bestech Business Tower,Appu Ghar,SkyJumper Trampoline Park,Axis Bank,KMP Expressway,Karma Lakelands,Jungle Safari & Trails,DPS Manesar,Medanta Hospital,Faridabad - Gurgaon Road,Lingaya's Lalita Devi Institute,ASF Insignia SEZ,Banjara Market Gurugram,Central Plaza Mall,"Paras Hospitals, Gurgaon",Badshahpur Sohna Rd Hwy,Vega School,Indian School of Hospitality,Vatika City Centre,Aatish Hospital,Info Technology Park Phase 2,Huda Metro Station,Southern Peripheral Rd,Global Ways School,Radisson Hotel,NH 248A,Sector 55/56 Metro Station,Mavens Inn,Sanar International Hospital,Sector 53-54 Metro Station,"IILM University, Gurugram",The Banyan Tree World School,The Big Tree Cafe,DLF Golf and Country Club,"Delhi Public School, Sector 84",Aarvy Hospital,DPG Degree College,Shivani public school,Baghera University,Kutumbh Hospital,Bijwasan Railway Station,Global Foyer Mall,Phase 2 Metro Station,Gurgaon Dreamz Mall,"Metro Hospital, Palam Vihar",Delhi Ajmer Expressway,Infinity Business Park,Huda metro station,Rion's Hospital,"Euro International School, Sector- 109.",Golf Course Ext Road,"Heritage Xperiential Learning, CRPF Rd",Sector 54 Chowk Metro Station,Gurgaon - Delhi Expy,Genesis Hospital Sector 84,DPGITM Engineering College Sector 34,Sapphire 83 Mall Sector 83,Holiday Inn Hotel Sector 90,SkyJumper Trampoline Park Gurgaon,National Tennis Academy Sector 98,NH-8 Delhi Jaipur Highway,Nouveau Medics Multispeciality OPD,Heritage Village Resort & Spa,Sector 86 Road,Genesis Hospital,Delh-Ajmer Expy,DPG Institute of Technology,Medanta -The Medicity,Airia Mall,Amma Hospital,DPS International Edge,Eros City Square,Splendor Trade Tower,Narayana Junior College,Sector 55 Metro Station,Dharampur Main Road,Oyster's Water Park,Vivanta Dwarka New Delhi,DLF Corporate Park,GD Goenka World School,KR Mangalam University,Smart View Hotel and Resort,Central Park Flower Valley,Shopping complex,Delhi Public School Sector 84,Central Peripheral Road,Nakhrola Stadium Sector 81A,NH 08,Imt Manesar,G D Goenka University,Fly India Adventure Resort,Vardaan Hospital,IMT Office Sohna,JMS Marine Square Mall,Vibrant Hospital,Prime Scholars Int. School,Ramgarh Farms & Resort,Basai Road,Shree Krishna Hospital,The Esplanade Mall,GEMS International School,Pranavananda International School,Greenway Hospital,National Tennis Academy,NH-8,Paras Trinity Mall,Rajesh Pilot Road,Scottish High International School,KIIT College of Engineering,The Vivekananda School,Southern Peripheral Road,Holiday Inn Express Gurugram Sector 50,Early Basket Grocery shop,Aradhya Cricket Club Gurgaon,Imperial Heritage School,Daultabad Village Park,Skylark Cricket Academy,Yashroop Hospital,Gurgaon Old Railway Station,Domino's Pizza,Conscient One Mall,Emerald Plaza Shopping Mall,Pawlywoof - Dog Park,SCC Drive-In Cinema,"Lemon Tree Hotel, Sohna Road",Shiksha Bharti Public School,Holiday Inn Express Gurugram,Sahara Mall,Dhanwapur Road,Govt. PG College,Basai Dhankot,Park Inn,IFFCO Chowk Metro Station,The Executive Centre,"Dwarka Expy, Sector 88","Euro Int School, Sector 37D, Gurugram",Reliance Trends Newtown Square Mall,SGT University,Medanta-The Medicity,SGT Hospital 1,Suncity School,Green Field School,Narayana E Techno,Alpine Convent School,Little E Step –Pre School,Sheetla Mata Mandir,Captain Chandan Lal Marg,CD International School,Raheja Mall,Basai Dhankot Railway Station,First Step Play School,Sri Ma Montessori International,Dwaraka Expressway,Ansal Plaza,Proposed Metro Station,Delhi International Airport,KMP Corridor,Vega Schools Sector 48,Cloudnine Hospital Sector 47,PVR Drive In Theatre,City Hospital,"NH 352W, Pataudi","Pathfinder Global School, Pataudi",Vistar Complex,BML Munjal University (BMU),Sector 55-56 Metro station,Bestech Central Square Mall,ORCHIDS The International School,Marengo Asia Hospitals,Sector 42-43 Rapid Metro,Sector 53-54 Rapid Metro,Bank Of Baroda,HDFC Bank ATM,Muincipal Corporation of Gurugram,One Horizon Center Bus Stop,Shalom Hills International School,Satyam Medicare Hospital,Anand Preschool,Choice pharmacy,Qutub Plaza,Sunset point,EPF Regional Office,IFFCO Chowk,Kingdom of Dreams,Gaytri Public School,KIIT College,SPM Hospital,Sealdah Railway Station,International Airport,Lemon Tree Hotel,"CK Birla Hospital, Gurgaon",Golf Pavilion,Golf Course Road,Ardee Mall,Shiv Nadar School,NH 148A,Ambience Public School,Heritage Intl Xperiential School,Summer Fields School,Primamed Super Speciality Hospital,Uma Sanjeevani Health Centre,Anya Gurgaon,Hotel Golf View Suites,Apollo Pharmacy,Rx Pharmacy,Sector 42/43 Bus Stand,Genpact Chowk Bus Stop,Huda City Centre Metro Station,Sector 53 Metro Station,ICICI Bank ATM,Bharat Petroleum Retail Outlet,DLF Linear Park,Le Meridien Gurgaon,Sector 42-43 Metro Station,Faridabad - Gurgaon Rd,Ambience Mall,Fun N Food Village,F9 Go Karting Gurgaon,Proposed Metro corridor,N.H-8,Shiskshantar,DPS,Amity,Pathways,GD Goenka,Medicity,Artemis,"Max, Fortis",Apollo,Paras Trinity Shopping Mall,Swastik Multispeciality Hospital,AIPL Business Co Working Space,Lemon Tree Hotel Sector 60,MKD Hospital,PVR Drive in Theatre,Sant Soordas Sihi Metro Station,De Adventure Amusement Park,Vatika Business Park Sector 49,"Suncity School, Sector 37D",The Signature Advanced Super Speciality,Gurugram University Kankrola,"Candor TechSpace, Sector 48",IndusInd Bank ATM,Cherub's Cradle,Mavens Orange - Hotel,Learning Stars School,State Bank of India,Deerika HyperMart,Triangular Park,Artimis hospital,Sector 45 SO Post Office,FUEL NATION,HSBC,Women Police Station,Best IVF Centre,Huda City Centre,Gurugram Public School,Shikshantar - Primary School,Mamta Hospital,IG International Airport,Omaxe City Centre,DLF Grand Mall,Arvy Hospital,Matrikiran School,DLF Cyber City,Vatika Town Square,Global city centre,Sohna road dhunela,Gd goenka university,Vardaan hospital and trauma centre,Maharana pratap school,Sector 55-56 metro,Garhi harsaru railway station Gurgaon,HUB 66,Sealdah,Sector 55-56 Rapid Metro Station,Hasanpur,The Oberoi,"Euro Intl School, Sector- 109",Najafgarh Kapashera Road,Dwarka Sector 21 Metro station,Hong Kong Bazaar,Bharti International Convent School,"Badshahpur Sohna Rd Hwy, Sector 68",Ashoka International School,The Oberoi Gurgaon,GD Goenka Public School,Chauma Road,Chirag Hospital,Sector-21 Metro Dwarka,AIPL Joy Street Mall,Radisson Hotel Sohna Road,iON Digital Zone (Gurugram),HUDA Mini Golf Course,IMT Road,National Highway 48,Sohna Gurgaon Road,Spaze Itech Park,"Pallavan PreSchool, Sohna Road",Radisson Hotel Gurugram Sohna Road,Polaris Hospital,RBSM Public school,Health Care Pharmacy,Sector 54 Chowk,EuroKids Preschool Suncity,YES Bank ATM,Suncity School Gurgaon,Suncity Shopping Complex,Vallores Pre School,Umkal Hospital,Haryana City Gas,Marigold Secondary School,Alpine Hospital,Pushpanjali Hospital,Golf Course Extension Rd,Country Inn,Westin,The Millenium School,Rajiv Chowk - Sohna Highway,KMP corridor,Central Park Resorts,GD Goenka University,Swastik Hospital Sec 66,Adarsh Senior Secondary School,Golf Course Extension,"International Tech Park Gurgaon,",Sector 55-56 Metro,"Surajgarh Gurgaon, Golf Course Ext Rd",Ananta Hospital,Indus World School,Golf Corse Ext. Rd.,National Highway-48,Prime Scholars International School,"Dwarka Expy, Dhanwapur Village",Shri Balaji’s Multispeciality Hospital,"Euro International School, Sector 37D","Delhi Public School, Sector 103","Park Inn, Gurgaon",DLF World Tech Park,Star Mall,The Hive Shopping Mall,"NH-8, IMT Manesar",Yaduvanshi Shiksha Niketan,Royal Institute Of Science and Mgt,Newtown Square Mall,NH 352W,Eros Corporate Park,Manesar Road,"Euro International School, Sec 84",Huda Metro Station (Gurugram),InfinityS Badminton Academy,Sanskar Bharti Public School,"Manipal Hospital, Gurugram","HUDA Market, Sector 14",Delhi Gurgaon Expressway,SCC Rooftop Drive-In,"The Oberoi, Gurgaon",Gurugram Railway Station,Kings International School,HUDA Market,Basai Metro Station,CBR Cricket Ground,Rapid Metro Sector 55-56,Kunskapsskolan School,Omaxe Celebration Mall,"Gurgaon - Delhi Expy, Sector 75A",International Tech Park Gurgaon,Shalom Presidency School,Sector 55-56 Rapid Metro,Jinga Lala Theme Park Gurgaon Delhi,"Pataudi Rd, Sector 95B",RELIANCE TRENDS Newtown Square Mall,Aarvy Healthcare Super Speciality,Approved Sector 37 Mero Station,Signature Hospital,Xavier’s International,Alpine School,Esplanade Mall,Sector 10 Market,Blue Bells Public School,infinity Business Park,Medanta The Medicity,Galleria 108 Mall,Manipal Hospital,"Vivanta New Delhi, Dwarka",Bharat Ram Global School,Canara Bank ATM,Yes Bank,Arc Hospital,Canara Bank,Axis Bank ATM,City Square,Shishu Kalyan School,Rathore IMT Hospital,DSD College,Patil Station,Amity University,ICFAI University,Indira Gandhi Airport,Sapphire 83,Cambridge Montessori,Hyatt Regency,Rao Bharat Singh International School,Aarvy Healthcare,"NH-8, Imt Manesar",Aapno Ghar,Cambridge College Of Education,Iffco Chowk,"Euro International School, Sector 84",Dharampeth Main Road,Gurgaon railway station,Dwarka sector 21 metro station,Old Delhi Gurgaon Road,Rotary Public School,Candor Techspace,"Manipal Hospital, Palam Vihar",Moulsari Avenue,"Adarsh public school,Garhi Harsaru",PHC Garhi Harsaru,Excellere World School,Aman Hospital & Surgical Centre,Neemrana Palace,K. R. Mangalam University,Global City Centre,Vishwas Hospital,Ibis Hotel,Horizon 1 Mall,Sector 42-43 Metro station,Ernst & Young,Paras Hospital,Gurgaon Faridabad Highway,"Mount Olympus School, Sec 79","Singhania University, Manesar",Capital Business Park,Old Sohna Dhani Road,GD Goenka Signature School,Vardaan Hospital & Trauma Centre,Public Bazar,GD Goenka School,Vatika Business Park,Bharat Petrol Pump,The Millennium School,IndusInd Bank,Artemis Hospital,Tau Devi Lal Sports Complex,Children Park,Medanta Dialysis Center,"Central Park, Sohna Rd","HDFC Bank ATM, Dhunela Ghamroj",Ashiana Anmol Kid Centric Homes,"Indianoil, Sohna - Gurgaon Rd",Taj Hotel & Family Restaurant,V-Square Sohna New Residential,G D Goenka World School,"The Phoenix Project, Sohna - Gurgaon Rd",Signature Global Park,Signum 36,"Kotak Mahindra Bank, MBS Tower","Pasco Automobiles, Alipur, Sohna",Sohna Bus Stand,Imperio School,Ektaa Hospitals,Vipul Trade Business Centre,Radisson Hotel Gurugram,Airia Mall Sector 68,Damdama More,Civil Hospital,K.R. Mangalam University,Western Peripheral Expressway,Bhondsi Nature Park,Enkays Hospital,"Lemon Tree Hotel,",Ram Krishna Public School,Aravalli Hill View Point,Gurugram Global Heights School,Satya The Hive Mall,Gurugram Road,The Signature Super Speciality Hospital,Sunrise University,Country Inn & Suites by Radisson,Yonex Badminton Stadium,Grand Hyatt,Au Grand Air,Indira Gandhi Eye Hospital,Double Tree by Hilton,Swastik Hospital,Jinaglala Theme Park,Scottish International School,Ap Sports cricket ground,Nischay Cricket Academy,DLC Cricket Ground,Drona Sports Village,Ramada by Wyndham Gurgaon,Mehrauli-Gurgaon Rd,Surajgarh Gurgaon,Apex Plus Hospital,ZEN Golf Range & Academy,The Banyan Tree Hiking Area,MG Road,Plaza Mall,MGF Metropolitan Mall,Lancers International School,Gurjar Samrat Jaipal Khatana Marg,Signature Global Infinity Mall Sohna,Vidya Niketan Sr Sec School,Sanjivani Hospital,Spectra Hospital,Golf Course Extn Road,"Tulip Violet Society, Sector 69","Spaze Palazo, Golf Course Ext Rd",Federal Bank Sector 71,Kunskapsskolan International,"Southern Peripheral Rd, Gurugram",Ektaa Hospitals Main Sohna Rd,Central Bank Of India Sohna Rd,Sanjeevani Hospital - Child Specialist,VATIKA BUSINESS PARK Sohna Rd,"IndianOil, Hasanpur","The Medicity, Spaze iTech Park","Axis Bank, Sohna Rd",Shambhu Dayal High School,Global City Centre Mall,Vardaan Hospital and Trauma Centre,Ascendas OneHub Gurgaon,IRIS Broadway Mall,Flying Wings Badminton Academy,Saraswati Model School,Orchid Business Park,Farrukh Nagar Railway Station,Medanta - The Medicity,M3m 65th Avenue Mall,DPS International School,Rapid Metro Sector 56,Sneh Hospital,Gems International School,National Highway 8,Appu Ghar Water Park,Tennis Vidyalaya (Tennis Academy),Zooper India Trampoline Park,Teri Golf Course,"Park Dr, DLF Phase 5",Paras Hospitals,Heritage badminton academy,Green Field Public School,Kadipur Industrial Area,Spazedge IT Park,JMD Megapolis,Sapphire Mall,"More Hypermart , Vipul business park",Basant Valley Global School,The Paras World School,Vipul Trade Centre,"WorldMark Gurgaon, Maidawas Rd",Artemis Hospital Gurgaon,"Western Peripheral Expy, Gurugram",Raghunath Bal Vidya Mandir School,ESIC Hospital,S N International School,Infinitys Badminton Academy,Country Inn and Suites by Radisson,Sector 29 Gurgaon Pubs and Bars,Emaar Business Park,"Southern Peripheral Rd, Dhani",Omaxe City Centre Mall,"Badshahpur Sohna Rd Hwy, Malibu Town",Ektaa Hospital,St. Xavier's School,PVR Drive In Theater,American Express,IDFC FIRST Bank,Sector 42-43,Sector 53-54,MGF Megacity Mall,Fortis hospital,Pataudi road,Dwarka expressway,Double Infinity market,Bamroli Cricket Ground,Aman Hospital,Kidzee,Paras Trinity,Golf course extension road,AIPL Business Club,Sector 55-56 rapid metro station,Narayana e-Techno School - Manesar,"HDFC Bank, Pataudi Rd","SS Omnia, Sector 86",Canara Bank - Nawada Fatehpur,"ICICI Bank ATM, Sector 86",Silver Streak Multi Speciality,RHM Public School,Minda Industries Nawada Fatehpur,"Numberdar market, IMT Manesar","Sodhi's Supermarket, Sector 82",M3M SCO Shop cum Office,Sector 42-43 Rapid Metro Station,Quality Inn Gurgaon,Minda Industries Limited,Central Park II Road,Omex City Centre Mall,Damdama Lake Rd,Sohna Hill Viewpoint,KR Mangalam University Sohna,Country Inn & Suites By Radisson,Hero Honda Chowk,Jagdish Super Market,Gyaananda School,Bharat Petroleum Shree Shyam Filling,"The Club, International City",Conscient One,"ICICI BANK ATM, Annapurna MKT",ESIC Dispensary,Canara Bank New Palam Vihar,Dwarka,Radha Krishan Mandir,Daultabad Stadium,Gurgaon Gramin Bank,IGIA Airport,SCR Model School,Golden Tulip Suites Gurgaon,South point Mall,Pathways School Gurgaon,Kidzee Sec-93,Jhankar Group of Institutions,Heritage Badminton Academy,Dwarka Expy/Northern Peripheral Rd,Dwarka expressway Basai crossing,"Euro Intl School, Sector 37D, Gurugram",Sethi Hospital,HDFC Bank,The Sixth Element School,K.R.Mangalam World School,Sushil Park,Peer Baba Ki Mazar,Punjab National Bank,CoNexus.Life B35,Medhaam Pre School & Daycare,Moksh Wellness Pvt Ltd.,Marriott Courtyard,World Tech Park,Athena,Bharat Petroleum Petrol Pump,Sanskar Jyoti School,Arc Multi Speciality Hospital,NH-48,Narayana e Techno School,"Medeor Hospital, Manesar",Guls' Kitchen,The Nook,Open Tap,Frescos,Subway,BOB ATM,PNB ATM,HDFC bank ATM,YES bank ATM,Citibank ATM,Gurugram Hospital,Govind Hospital,Manish Gallexie 91,Silver Streak Multi Speciality Hospital,Holiday Inn Gurugram,NH-8 IMT Manesar,Airport,Vatika Sector Road,Gurugram University Sector 87,CNG Petrol Pump,Miracles Apollo Cradle/Spectra Hospital,Vivek Model School,Dwarka Expressway Link Road,McDonald's India 24 Hours,Garhi Budhera Road,Iris Broadway Gurugram,iGrow Montessori Play School,Matrikiran High School,Badsa AMS Hospital,GlobalHealthcare Multispeciality,Cricket Academy,V'Lante Mall,NH 48 Gurugram,Patli Railway Station,V Club,"Fitso Sector 48 Spuddy, Badminton",Lotus Valley International School,Badshapur Sohna Highway,Golf Course Rd,Bharat Singh fuel company,Basai Enclave Park,CANARA BANK,Bank Of Baroda ATM,The Holy Kingdom Public School,Shiv Mandir,Open gym garden,KFG sports club Parking,ESIC HOSPITAL,Sector 37 Police Station,Alfaa Health Care Hospital,Euro Intl School Sec-51,Mall Fifty One,"NH 8, Sector 15 Part 2",K.D. Hospital,Gurgaon Road,Saint Paul's School,Indus valley Public School,MDS Public School,Signature Super Speciality Hospital,Harsaru Village Bus Stop,Health care pharmacy,Jadon Pharmacy,JMS Crosswalk,Essar Petrol Pump,The Heritage Pride Modern School,SS Omnia Mall,Miracles Apollo Cradle / Spectra,Gurgaon Toll,Propose Metro Station,Rajiv Chowk,Lions Public School,M3M Cosmopolitan,M3M International Financial Center (IFC),"Badshahpur Sohna Rd Hwy, Haryana",Holiday Inn Express Gurugram Sec 50,"NH 48, Sector 78",ICICI ATM,Sai Sports Club cricket ground,Silver Streak Hospital,Gurukul Preschool,HP PETROL PUMP Unnamed Rd,INOX Cinema,Nawada Cricket Accadmy,Arc Multi Speciality,Sanjeevani Hospital,Baba Kanala Chowk,Pataudi Rd,Dronacharya College of Engineering,Netaji Subhash Marg,"Euro International School, sector- 51",NH 248 A,NH 248,Faridabad,Delhi-Mumbai Expressway,IMT Sohna,Kundli Manesar Palwal Expressway,KR Mangalam,SCJ Academy,Taj,Damdama Lake,Ascendas OneHub Gurgaon Business Park,GD Goenka High School,"Badshahpur Sohna Rd Hwy, Rajoria Ngr","GD Goenka University, Gurugram",Jhankar Senior Secondary School,Entertainland Mall,Aravalli Hills,Delhi,Red Roses Public School,Delhi Jaipur Highway,Iffco Chowk Metro Station,Galleria Market,Fortis Memorial Research Institute,The Westin Hotel,BM College of Technology & Mgmt,NeoSquare Shopping Mall,Glorious World School,MG Road Metro Station,Lovely Public School,AIPL Business Centre,Signature Advanced Hospital,"iON Digital Zone, Gurgaon",Sapphire 93 Mall,RPS International School Sector 89,Signature tower,Jharsha Chowk,Umang Bhawaj Chawk,NH 8,Basai Dhancourt Railway 

In [41]:
location_df.fillna(54000,inplace=True)

In [42]:
location_df.to_csv('location_df.csv')

In [43]:
location_df = pd.read_csv('../data/location_df_cleaned_raw.csv')

In [44]:
location_df.set_index('PropertyName', inplace=True)

In [45]:
location_df

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,Indira Gandhi International Airport,Hamoni Golf Camp,Fun N Food Water Park,Accenture DDC5,DPSG Palam Vihar Gurugram,"Park Hospital, Palam Vihar",Palam Vihar Halt Railway Station,Tau DeviLal Sports Complex,Hyatt Place,Altrade Business Centre,AIPL Business Club Sector 62,Heritage Xperiential Learning School,CK Birla Hospital,Paras Trinity Mall Sector 63,Rapid Metro Station Sector 56,De Adventure Park,Golf Course Ext Road,DoubleTree by Hilton Hotel Gurgaon,KIIT College of Engineering Sohna Road,Mehrauli-Gurgaon Road,Nirvana Rd,TERI Golf Course,The Shikshiyan School,WTC Plaza,Luxus Haritma Resort,BSF Golf Course,Rions Hospital,Gurgaon,Dwarka Sector 21,Nehru Stadium,IGI Airport,Vasant Kunj,Pranavananda International School,DLF Site central office,Holiday Inn Gurugram Sector 90,Krishna Hospital,Royal Institute Of Science,Sapphire 83 Mall,NH 48,Garhi Harsaru Junction,Manesar Golf Course,AapnoGhar,Vega Schools NH-8,DLF Corporate Greens,Miracles Apollo Cradle Hospital,Hyatt Regency Gurugram,Golden Greens Golf & Resorts Limited,Mount Olympus Junior School,Miracles Apollo Hospital,NH -8,"Savoy Suites, Manesar",Golden Greens Golf & Resorts,IMT Manesar,Amity University Gurugram,Golf Course Extension Road,"Dwarka Expy, Sector 109","Euro International School, Sector- 109.",Jai Sai Ram Hospital,Aryan Hospital,Idea Cosmic Plaza,Royal Institute Of Science & Management,Pataudi Road,Holiday Inn Sector 90,RPS International School,Aarvy Healthcare Hospital,Iris Broadway Mall,Imperia Mindspace,AIPL Business Tower,Heritage School,"Lotus Valley Intl School, Gurgaon",Gurugram University,Sector 55-56 Metro Station,Omaxe Gurgaon Mall,Sushant University,"Badshahpur Sohna Rd Hwy,Sector 48",Naurangpur Cricket Stadium,Naurangpur Road,National Highway 48,Vatika Town Square-INXT,Ompee International School,Manesar Bus Stand,Yashlok Medical Centre,Euro International School,WorldMark Gurgaon,Capital Cyberscape,The Shriram Millennium School,DoubleTree by Hilton Hotel,Badshahpur Sohna Hwy,Nakhrola Stadium,Delhi - Jaipur Expressway,Vatika Town Square-INXT Mall,Savoy Suites,Bal Bharati Public School,Vatika Business Centre,St. Xavier's High School,Miracles Apollo Cradle,Ambience Mall New,Hyatt Regency Gurgaon,Delhi Public School,Elan Miracle Mall,Miracles Apollo Cradle Spectra Hospital,Agri Business Management Collage,Grand Hyatt Gurgaon,Duke Horse Riding Club,PVR Drive In Cinema,W Pratiksha Hospital,Metro World Mall,Unicosmos School,Faridabad - Gurgaon Road,Sohna Road,Bestech Business Tower,Appu Ghar,SkyJumper Trampoline Park,Axis Bank,KMP Expressway,Karma Lakelands,Jungle Safari & Trails,DPS Manesar,Medanta Hospital,Lingaya's Lalita Devi Institute,ASF Insignia SEZ,Banjara Market Gurugram,Central Plaza Mall,"Paras Hospitals, Gurgaon",Badshahpur Sohna Rd Hwy,Vega School,Indian School of Hospitality,Vatika City Centre,Aatish Hospital,Info Technology Park Phase 2,Huda Metro Station,Southern Peripheral Road,Global Ways School,Radisson Hotel,NH 248A,Mavens Inn,Sanar International Hospital,Sector 53-54 Metro Station,"IILM University, Gurugram",The Banyan Tree World School,The Big Tree Cafe,DLF Golf and Country Club,"Delhi Public School, Sector 84",Aarvy Hospital,DPG Degree College,Shivani public school,Baghera University,Kutumbh Hospital,Bijwasan Railway Station,Global Foyer Mall,Phase 2 Metro Station,Gurgaon Dreamz Mall,"Metro Hospital, Palam Vihar",Delhi Ajmer Expressway,Infinity Business Park,Rion's Hospital,"Heritage Xperiential Learning, CRPF Rd",Sector 54 Chowk Metro Station,Gurgaon - Delhi Expy,Genesis Hospital Sector 84,DPGITM Engineering College Sector 34,Sapphire 83 Mall Sector 83,Holiday Inn Hotel Sector 90,SkyJumper Trampoline Park Gurgaon,National Tennis Academy Sector 98,NH-8 Delhi Jaipur Highway,Nouveau Medics Multispeciality OPD,Heritage Village Resort & Spa,Sector 86 Road,Genesis Hospital,Delh-Ajmer Expy,DPG Institute of Technology,Medanta - The Medicity,Airia Mall,Amma Hospital,DPS International Edge,Eros City Square,Splendor Trade Tower,Narayana Junior College,Sector 55 Metro Station,Dharampur Main Road,Oyster's Water Park,Vivanta Dwarka New Delhi,DLF Corporate Park,GD Goenka World School,KR Mangalam University,Smart View Hotel and Resort,Central Park Flower Valley,Shopping complex,Central Peripheral Road,Nakhrola Stadium Sector 81A,NH 08,G D Goenka University,Fly India Adventure Resort,Vardaan Hospital,IMT Office Sohna,JMS Marine Square Mall,Vibrant Hospital,Prime Scholars International School,Ramgarh Farms & Resort,Basai Road,Shree Krishna Hospital,The Esplanade Mall,GEMS International School,Greenway Hospital,National Tennis Academy,Paras Trinity Mall,Rajesh Pilot Road,Scottish High International School,KIIT College of Engineering,The Vivekananda School,Holiday Inn Express Gurugram Sector 50,Early Basket Grocery shop,Aradhya Cricket Club Gurgaon,Imperial Heritage School,Daultabad Village Park,Skylark Cricket Academy,Yashroop Hospital,Gurgaon Old Railway Station,Domino's Pizza,Conscient One Mall,Emerald Plaza Shopping Mall,Pawlywoof - Dog Park,SCC Drive-In Cinema,"Lemon Tree Hotel, Sohna Road",Shiksha Bharti Public School,Holiday Inn Express Gurugram,Sahara Mall,Dhanwapur Road,Govt. PG College,Basai Dhankot,Park Inn,IFFCO Chowk Metro Station,The Executive Centre,"Dwarka Expy, Sector 88","Euro Intl School, Sector 37D, Gurugram",Reliance Trends Newtown Square Mall,SGT University,SGT Hospital 1,Suncity School,Green Field School,Narayana E Techno,Alpine Convent School,Little E Step –Pre School,Sheetla Mata Mandir,Captain Chandan Lal Marg,CD International School,Raheja Mall,Basai Dhankot Railway Station,First Step Play School,Sri Ma Montessori International,Dwaraka Expressway,Ansal Plaza,Proposed Metro Station,Delhi International Airport,KMP Corridor,Vega Schools Sector 48,Cloudnine Hospital Sector 47,PVR Drive In Theatre,City Hospital,"NH 352W, Pataudi","Pathfinder Global School, Pataudi",Vistar Complex,BML Munjal University (BMU),Bestech Central Square Mall,ORCHIDS The International School,Marengo Asia Hospitals,Sector 42-43 Rapid Metro,Sector 53-54 Rapid Metro,Bank Of Baroda,HDFC Bank ATM,Muincipal Corporation of Gurugram,One Horizon Center Bus Stop,Shalom Hills International School,Satyam Medicare Hospital,Anand Preschool,Choice pharmacy,Qutub Plaza,Sunset point,EPF Regional Office,IFFCO Chowk,Kingdom of Dreams,Gaytri Public School,KIIT College,SPM Hospital,Sealdah Railway Station,International Airport,"Lemon Tree Hotel,","CK Birla Hospital, Gurgaon",Golf Pavilion,Golf Course Road,Ardee Mall,Shiv Nadar School,NH 148A,Ambience Public School,Heritage Intl Xperiential School,Summer Fields School,Primamed Super Speciality Hospital,Uma Sanjeevani Health Centre,Anya Gurgaon,Hotel Golf View Suites,Apollo Pharmacy,Rx Pharmacy,Sector 42/43 Bus Stand,Genpact Chowk Bus Stop,Huda City Centre Metro Station,Sector 53 Metro Station,ICICI Bank ATM,Bharat Petroleum Retail Outlet,DLF Linear Park,Le Meridien Gurgaon,Sector 42-43 Metro Station,Ambience Mall,Fun N Food Village,F9 Go Karting Gurgaon,Proposed Metro corridor,N.H-8,Shiskshantar,DPS,Amity,Pathways,GD Goenka,Medicity,Artemis,"Max, Fortis",Apollo,Paras Trinity Shopping Mall,Swastik Multispeciality Hospital,AIPL Business Co Working Space,Lemon Tree Hotel Sector 60,MKD Hospital,Sant Soordas Sihi Metro Station,De Adventure Amusement Park,Vatika Business Park Sector 49,"Suncity School, Sector 37D",The Signature Advanced Super Speciality,Gurugram University Kankrola,"Candor TechSpace, Sector 48",IndusInd Bank ATM,Cherub's Cradle,Mavens Orange - Hotel,Learning Stars School,State Bank of India,Deerika HyperMart,Triangular Park,Artimis hospital,Sector 45 SO Post Office,FUEL NATION,HSBC,Women Police Station,Best IVF Centre,Huda City Centre,Gurugram Public School,Shikshantar - Primary School,Mamta Hospital,IG International Airport,Omaxe City Centre,DLF Grand Mall,Arvy Hospital,Matrikiran School,DLF Cyber City,Vatika Town Square,Global City Centre,Sohna road dhunela,GD Goenka University,Vardaan Hospital and Trauma Centre,Maharana pratap school,Sector 55-56 Metro,Garhi harsaru railway station Gurgaon,HUB 66,Sealdah,Sector 55-56 Rapid Metro Station,Hasanpur,The Oberoi,Najafgarh Kapashera Road,Hong Kong Bazaar,Bharti International Convent School,"Badshahpur Sohna Rd Hwy, Sector 68",Ashoka International School,"The Oberoi, Gurgaon",GD Goenka Public School,Chauma Road,Chirag Hospital,Sector-21 Metro Dwarka,AIPL Joy Street Mall,Radisson Hotel Sohna Road,iON Digital Zone (Gurugram),HUDA Mini Golf Course,IMT Road,Sohna Gurgaon Road,Spaze Itech Park,"Pallavan PreSchool, Sohna Road",Radisson Hotel Gurugram Sohna Road,Polaris Hospital,RBSM Public school,Health Care Pharmacy,Sector 54 Chowk,EuroKids Preschool Suncity,YES Bank ATM,Suncity School Gurgaon,Suncity Shopping Complex,Vallores Pre School,Umkal Hospital,Haryana City Gas,Marigold Secondary School,Alpine Hospital,Pushpanjali Hospital,Country Inn,Westin,The Millenium School,Rajiv Chowk - Sohna Highway,Central Park Resorts,Swastik Hospital Sec 66,Adarsh Senior Secondary School,Golf Course Extension,"International Tech Park Gurgaon,","Surajgarh Gurgaon, Golf Course Ext Rd",Ananta Hospital,Indus World School,Golf Corse Ext. Rd.,"Dwarka Expy, Dhanwapur Village",Shri Balaji’s Multispeciality Hospital,"Euro International School, Sector 37D","Delhi Public School, Sector 103","Park Inn, Gurgaon",DLF World Tech Park,Star Mall,The Hive Shopping Mall,"NH-8, IMT Manesar",Yaduvanshi Shiksha Niketan,Royal Institute Of Science and Mgt,Newtown Square Mall,NH 352W,Eros Corporate Park,Manesar Road,"Euro International School, Sec 84",Huda Metro Station (Gurugram),InfinityS Badminton Academy,Sanskar Bharti Public School,"Manipal Hospital, Gurugram","HUDA Market, Sector 14",Delhi Gurgaon Expressway,SCC Rooftop Drive-In,Gurugram Railway Station,Kings International School,HUDA Market,Basai Metro Station,CBR Cricket Ground,Rapid Metro Sector 55-56,Kunskapsskolan School,Omaxe Celebration Mall,"Gurgaon - Delhi Expy, Sector 75A",Shalom Presidency School,Sector 55-56 Rapid Metro,Jinga Lala Theme Park Gurgaon Delhi,"Pataudi Rd, Sector 95B",Aarvy Healthcare Super Speciality,Approved Sector 37 Mero Station,Signature Hospital,Xavier’s International,Alpine School,Esplanade Mall,Sector 10 Market,Blue Bells Public School,Galleria 108 Mall,Manipal Hospital,"Vivanta New Delhi, Dwarka",Bharat Ram Global School,Canara Bank ATM,Yes Bank,Arc Hospital,Canara Bank,Axis Bank ATM,City Square,Shishu Kalyan School,Rathore IMT Hospital,DSD College,Patil Station,Amity University,ICFAI University,Indira Gandhi Airport,Sapphire 83,Cambridge Montessori,Hyatt Regency,Rao Bharat Singh International School,Aarvy Healthcare,Aapno Ghar,Cambridge College Of Education,"Euro International School, Sector 84",Dharampeth Main Road,Old Delhi Gurgaon Road,Rotary Public School,Candor Techspace,"Manipal Hospital, Palam Vihar",Moulsari Avenue,"Adarsh public school,Garhi Harsaru",PHC Garhi Harsaru,Excellere World School,Aman Hospital & Surgical Centre,Neemrana Palace,K. R. Mangalam University,Vishwas Hospital,Ibis Hotel,Horizon 1 Mall,Ernst & Young,Paras Hospital,Gurgaon Faridabad Highway,"Mount Olympus School, Sec 79","Singhania University, Manesar",Capital Business Park,Old Sohna Dhani Road,GD Goenka Signature School,Vardaan Hospital & Trauma Centre,Public Bazar,GD Goenka School,Vatika Business Park,Bharat Petrol Pump,The Millennium School,IndusInd Bank,Artemis Hospital,Tau Devi Lal Sports Complex,Children Park,Medanta Dialysis Center,"Central Park, Sohna Rd","HDFC Bank ATM, Dhunela Ghamroj",Ashiana Anmol Kid Centric Homes,"Indianoil, Sohna - Gurgaon Rd",Taj Hotel & Family Restaurant,V-Square Sohna New Residential,G D Goenka World School,"The Phoenix Project, Sohna - Gurgaon Rd",Signature Global Park,Signum 36,"Kotak Mahindra Bank, MBS Tower","Pasco Automobiles, Alipur, Sohna",Sohna Bus Stand,Imperio School,Ektaa Hospitals,Vipul Trade Business Centre,Radisson Hotel Gurugram,Airia Mall Sector 68,Damdama More,Civil Hospital,Western Peripheral Expressway,Bhondsi Nature Park,Enkays Hospital,Ram Krishna Public School,Aravalli Hill View Point,Gurugram Global Heights School,Satya The Hive Mall,Gurugram Road,The Signature Super Speciality Hospital,Sunrise University,Country Inn & Suites By Radisson,Yonex Badminton Stadium,Grand Hyatt,Au Grand Air,Indira Gandhi Eye Hospital,Double Tree by Hilton,Swastik Hospital,Jinaglala Theme Park,Scottish International School,Ap Sports cricket ground,Nischay Cricket Academy,DLC Cricket Ground,Drona Sports Village,Ramada by Wyndham Gurgaon,Surajgarh Gurgaon,Apex Plus Hospital,ZEN Golf Range & Academy,The Banyan Tree Hiking Area,MG Road,Plaza Mall,MGF Metropolitan Mall,Lancers International School,Gurjar Samrat Jaipal Khatana Marg,Signature Global Infinity Mall Sohna,Vidya Niketan Sr Sec School,Sanjivani Hospital,Spectra Hospital,Golf Course Extn Road,"Tulip Violet Society, Sector 69","Spaze Palazo, Golf Course Ext Rd",Federal Bank Sector 71,Kunskapsskolan International,"Southern Peripheral Rd, Gurugram",Ektaa Hospitals Main Sohna Rd,Central Bank Of India Sohna Rd,Sanjeevani Hospital - Child Specialist,VATIKA BUSINESS PARK Sohna Rd,"IndianOil, Hasanpur","The Medicity, Spaze iTech Park","Axis Bank, Sohna Rd",Shambhu Dayal High School,Global City Centre Mall,Ascendas OneHub Gurgaon,Flying Wings Badminton Academy,Saraswati Model School,Orchid Business Park,Farrukh Nagar Railway Station,M3m 65th Avenue Mall,DPS International School,Rapid Metro Sector 56,Sneh Hospital,National Highway 8,Appu Ghar Water Park,Tennis Vidyalaya (Tennis Academy),Zooper India Trampoline Park,"Park Dr, DLF Phase 5",Paras Hospitals,Heritage Badminton Academy,Green Field Public School,Kadipur Industrial Area,Spazedge IT Park,JMD Megapolis,Sapphire Mall,"More Hypermart , Vipul business park",Basant Valley Global School,The Paras World School,Vipul Trade Centre,"WorldMark Gurgaon, Maidawas Rd",Artemis Hospital Gurgaon,"Western Peripheral Expy, Gurugram",Raghunath Bal Vidya Mandir School,ESIC Hospital,S N International School,Country Inn and Suites by Radisson,Sector 29 Gurgaon Pubs and Bars,Emaar Business Park,"Southern Peripheral Rd, Dhani",Omaxe City Centre Mall,"Badshahpur Sohna Rd Hwy, Malibu Town",Ektaa Hospital,St. Xavier's School,PVR Drive In Theater,American Express,IDFC FIRST Bank,Sector 42-43,Sector 53-54,MGF Megacity Mall,Fortis hospital,Double Infinity market,Bamroli Cricket Ground,Aman Hospital,Kidzee,Paras Trinity,AIPL Business Club,Narayana e-Techno School - Manesar,"HDFC Bank, Pataudi Rd","SS Omnia, Sector 86",Canara Bank - Nawada Fatehpur,"ICICI Bank ATM, Sector 86",Silver Streak Multi Speciality,RHM Public School,Minda Industries Nawada Fatehpur,"Numberdar market, IMT Manesar","Sodhi's Supermarket, Sector 82",M3M SCO Shop cum Office,Sector 42-43 Rapid Metro Station,Quality Inn Gurgaon,Minda Industries Limited,Central Park II Road,Omex City Centre Mall,Damdama Lake Rd,Sohna Hill Viewpoint,KR Mangalam University Sohna,Hero Honda Chowk,Jagdish Super Market,Gyaananda School,Bharat Petroleum Shree Shyam Filling,"The Club, International City",Conscient One,"ICICI BANK ATM, Annapurna MKT",ESIC Dispensary,Canara Bank New Palam Vihar,Dwarka,Radha Krishan Mandir,Daultabad Stadium,Gurgaon Gramin Bank,IGIA Airport,SCR Model School,Golden Tulip Suites Gurgaon,South point Mall,Pathways School Gurgaon,Kidzee Sec-93,Jhankar Group of Institutions,Dwarka Expy/Northern Peripheral Rd,Dwarka expressway Basai crossing,Sethi Hospital,HDFC Bank,The Sixth Element School,K.R.Mangalam World School,Sushil Park,Peer Baba Ki Mazar,Punjab National Bank,CoNexus.Life B35,Medhaam Pre School & Daycare,Moksh Wellness Pvt Ltd.,Marriott Courtyard,World Tech Park,Athena,Bharat Petroleum Petrol Pump,Sanskar Jyoti School,Arc Multi Speciality Hospital,Narayana e Techno School,"Medeor Hospital, Manesar",Guls' Kitchen,The Nook,Open Tap,Frescos,Subway,BOB ATM,PNB ATM,Citibank ATM,Gurugram Hospital,Govind Hospital,Manish Gallexie 91,Silver Streak Multi Speciality Hospital,Holiday Inn Gurugram,Airport,Vatika Sector Road,Gurugram University Sector 87,CNG Petrol Pump,Vivek Model School,Dwarka Expressway Link Road,McDonald's India 24 Hours,Garhi Budhera Road,Iris Broadway Gurugram,iGrow Montessori Play School,Matrikiran High School,Badsa AMS Hospital,GlobalHealthcare Multispeciality,Cricket Academy,V'Lante Mall,NH 48 Gurugram,Patli Railway Station,V Club,"Fitso Sector 48 Spuddy, Badminton",Lotus Valley International School,Badshapur Sohna Highway,Bharat Singh fuel company,Basai Enclave Park,Bank Of Baroda ATM,The Holy Kingdom Public School,Shiv Mandir,Open gym garden,KFG sports club Parking,Sector 37 Police Station,Alfaa Health Care Hospital,Euro Intl School Sec-51,Mall Fifty One,"NH 8, Sector 15 Part 2",K.D. Hospital,Gurgaon Road,Saint Paul's School,Indus valley Public School,MDS Public School,Signature Super Speciality Hospital,Harsaru Village Bus Stop,Jadon Pharmacy,JMS Crosswalk,Essar Petrol Pump,The Heritage Pride Modern School,SS Omnia Mall,Miracles Apollo Cradle / Spectra,Gurgaon Toll,Propose Metro Station,Rajiv Chowk,Lions Public School,M3M Cosmopolitan,M3M International Financial Center (IFC),"Badshahpur Sohna Rd Hwy, Haryana",Holiday Inn Express Gurugram Sec 50,"NH 48, Sector 78",ICICI ATM,Sai Sports Club cricket ground,Silver Streak Hospital,Gurukul Preschool,HP PETROL PUMP Unnamed Rd,INOX Cinema,Nawada Cricket Accadmy,Arc Multi Speciality,Sanjeevani Hospital,Baba Kanala Chowk,Dronacharya College of Engineering,Netaji Subhash Marg,"Euro International School, sector- 51",NH 248 A,NH 248,Faridabad,Delhi-Mumbai Expressway,IMT Sohna,Kundli Manesar Palwal Expressway,KR Mangalam,SCJ Academy,Taj,Damdama Lake,Ascendas OneHub Gurgaon Business Park,GD Goenka High School,"Badshahpur Sohna Rd Hwy, Rajoria Ngr","GD Goenka University, Gurugram",Jhankar Senior Secondary School,Entertainland Mall,Aravalli Hills,Delhi,Red Roses Public School,Delhi Jaipur Highway,Galleria Market,Fortis Memorial Research Institute,The Westin Hotel,BM College of Technology & Mgmt,NeoSquare Shopping Mall,Glorious World School,MG Road Metro Station,Lovely Public School,AIPL Business Centre,Signature Advanced Hospital,"iON Digital Zone, Gurgaon",Sapphire 93 Mall,RPS International School Sector 89,Signature tower,Jharsha Chowk,Umang Bhawaj Chawk,Basai Dhancourt Railway Station,AIIMS Jhajjar,Vedic Hospital,Balaji Hospital,SGT Medical College,Garima Public School,Tigra Market,Imperfecto Patio,ISKCON Temple,APJ Abdul Kalam Park,Ramprastha Police Post,Taxila cricket ground,St Pauls School,Edge towers tennis court,SGT UHTC Basai,Hanuman & Shani Mandir,KFG Sports Club,Metro Station Kankrola sec 87,Vatika City Centre Mall,Broadways International School,Sultanpur National Park,"Dwarka Expy, Block D, New Palam Vihar","Global Foyer Mall, Palam Vihar",Ocus Medley Mall,The Westin Gurgaon,Colonel's Central Academy,Trident Hotel Gurgaon,Signum 107,Nora Solomon Medicenter,Najafgarh Jheel Bird Sanctuary,ICICI Bank,INXT High Street,iGrow Montessori,Urusvati Museum Of Folklore,Prakash Hospital,Aravali Adventure Hill,"KDM Public School, Sohna","Badshahpur Sohna Rd Hwy, Raghav Vatika",Discount Department Store,Kinder Care Playschool,Kangaroo Kids Preschool,BigBazaar,SRS Cinemas,VIBGYOR High School,Gyan Bharti Public School,Keshav Pharmacy,Diamond Public School,Mother land public school,Kamal Hospital,Creative Tennis Academy,Shanti Tennis Academy,Lotus Sports Academy,ISBM College,Huda city center,Centrum Plaza,Shoppers Stop,Suncity Market,Govt. Model Sanskriti Primary School,Cyber ​​Park,IILM School of Management,Shree Deep Petrol Pump,Gurugram City Bus Depot,Starbucks,Khatu Shyam Mandir,Mps World School,Northern Peripheral Road,Tomar Hospital,Taj City Centre Hotel,DPS Sector 103,Cambridge Montessori Preschool,Shree Balaji College,New Water Pond,Sun's Spa,Cool Deck Coffee,Shivai Hospital,Solitaire Banquet Hall,Hud

In [48]:
from sklearn.preprocessing import StandardScaler
# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(location_df), columns=location_df.columns, index=location_df.index)

In [49]:
location_df_normalized

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,Indira Gandhi International Airport,Hamoni Golf Camp,Fun N Food Water Park,Accenture DDC5,DPSG Palam Vihar Gurugram,"Park Hospital, Palam Vihar",Palam Vihar Halt Railway Station,Tau DeviLal Sports Complex,Hyatt Place,Altrade Business Centre,AIPL Business Club Sector 62,Heritage Xperiential Learning School,CK Birla Hospital,Paras Trinity Mall Sector 63,Rapid Metro Station Sector 56,De Adventure Park,Golf Course Ext Road,DoubleTree by Hilton Hotel Gurgaon,KIIT College of Engineering Sohna Road,Mehrauli-Gurgaon Road,Nirvana Rd,TERI Golf Course,The Shikshiyan School,WTC Plaza,Luxus Haritma Resort,BSF Golf Course,Rions Hospital,Gurgaon,Dwarka Sector 21,Nehru Stadium,IGI Airport,Vasant Kunj,Pranavananda International School,DLF Site central office,Holiday Inn Gurugram Sector 90,Krishna Hospital,Royal Institute Of Science,Sapphire 83 Mall,NH 48,Garhi Harsaru Junction,Manesar Golf Course,AapnoGhar,Vega Schools NH-8,DLF Corporate Greens,Miracles Apollo Cradle Hospital,Hyatt Regency Gurugram,Golden Greens Golf & Resorts Limited,Mount Olympus Junior School,Miracles Apollo Hospital,NH -8,"Savoy Suites, Manesar",Golden Greens Golf & Resorts,IMT Manesar,Amity University Gurugram,Golf Course Extension Road,"Dwarka Expy, Sector 109","Euro International School, Sector- 109.",Jai Sai Ram Hospital,Aryan Hospital,Idea Cosmic Plaza,Royal Institute Of Science & Management,Pataudi Road,Holiday Inn Sector 90,RPS International School,Aarvy Healthcare Hospital,Iris Broadway Mall,Imperia Mindspace,AIPL Business Tower,Heritage School,"Lotus Valley Intl School, Gurgaon",Gurugram University,Sector 55-56 Metro Station,Omaxe Gurgaon Mall,Sushant University,"Badshahpur Sohna Rd Hwy,Sector 48",Naurangpur Cricket Stadium,Naurangpur Road,National Highway 48,Vatika Town Square-INXT,Ompee International School,Manesar Bus Stand,Yashlok Medical Centre,Euro International School,WorldMark Gurgaon,Capital Cyberscape,The Shriram Millennium School,DoubleTree by Hilton Hotel,Badshahpur Sohna Hwy,Nakhrola Stadium,Delhi - Jaipur Expressway,Vatika Town Square-INXT Mall,Savoy Suites,Bal Bharati Public School,Vatika Business Centre,St. Xavier's High School,Miracles Apollo Cradle,Ambience Mall New,Hyatt Regency Gurgaon,Delhi Public School,Elan Miracle Mall,Miracles Apollo Cradle Spectra Hospital,Agri Business Management Collage,Grand Hyatt Gurgaon,Duke Horse Riding Club,PVR Drive In Cinema,W Pratiksha Hospital,Metro World Mall,Unicosmos School,Faridabad - Gurgaon Road,Sohna Road,Bestech Business Tower,Appu Ghar,SkyJumper Trampoline Park,Axis Bank,KMP Expressway,Karma Lakelands,Jungle Safari & Trails,DPS Manesar,Medanta Hospital,Lingaya's Lalita Devi Institute,ASF Insignia SEZ,Banjara Market Gurugram,Central Plaza Mall,"Paras Hospitals, Gurgaon",Badshahpur Sohna Rd Hwy,Vega School,Indian School of Hospitality,Vatika City Centre,Aatish Hospital,Info Technology Park Phase 2,Huda Metro Station,Southern Peripheral Road,Global Ways School,Radisson Hotel,NH 248A,Mavens Inn,Sanar International Hospital,Sector 53-54 Metro Station,"IILM University, Gurugram",The Banyan Tree World School,The Big Tree Cafe,DLF Golf and Country Club,"Delhi Public School, Sector 84",Aarvy Hospital,DPG Degree College,Shivani public school,Baghera University,Kutumbh Hospital,Bijwasan Railway Station,Global Foyer Mall,Phase 2 Metro Station,Gurgaon Dreamz Mall,"Metro Hospital, Palam Vihar",Delhi Ajmer Expressway,Infinity Business Park,Rion's Hospital,"Heritage Xperiential Learning, CRPF Rd",Sector 54 Chowk Metro Station,Gurgaon - Delhi Expy,Genesis Hospital Sector 84,DPGITM Engineering College Sector 34,Sapphire 83 Mall Sector 83,Holiday Inn Hotel Sector 90,SkyJumper Trampoline Park Gurgaon,National Tennis Academy Sector 98,NH-8 Delhi Jaipur Highway,Nouveau Medics Multispeciality OPD,Heritage Village Resort & Spa,Sector 86 Road,Genesis Hospital,Delh-Ajmer Expy,DPG Institute of Technology,Medanta - The Medicity,Airia Mall,Amma Hospital,DPS International Edge,Eros City Square,Splendor Trade Tower,Narayana Junior College,Sector 55 Metro Station,Dharampur Main Road,Oyster's Water Park,Vivanta Dwarka New Delhi,DLF Corporate Park,GD Goenka World School,KR Mangalam University,Smart View Hotel and Resort,Central Park Flower Valley,Shopping complex,Central Peripheral Road,Nakhrola Stadium Sector 81A,NH 08,G D Goenka University,Fly India Adventure Resort,Vardaan Hospital,IMT Office Sohna,JMS Marine Square Mall,Vibrant Hospital,Prime Scholars International School,Ramgarh Farms & Resort,Basai Road,Shree Krishna Hospital,The Esplanade Mall,GEMS International School,Greenway Hospital,National Tennis Academy,Paras Trinity Mall,Rajesh Pilot Road,Scottish High International School,KIIT College of Engineering,The Vivekananda School,Holiday Inn Express Gurugram Sector 50,Early Basket Grocery shop,Aradhya Cricket Club Gurgaon,Imperial Heritage School,Daultabad Village Park,Skylark Cricket Academy,Yashroop Hospital,Gurgaon Old Railway Station,Domino's Pizza,Conscient One Mall,Emerald Plaza Shopping Mall,Pawlywoof - Dog Park,SCC Drive-In Cinema,"Lemon Tree Hotel, Sohna Road",Shiksha Bharti Public School,Holiday Inn Express Gurugram,Sahara Mall,Dhanwapur Road,Govt. PG College,Basai Dhankot,Park Inn,IFFCO Chowk Metro Station,The Executive Centre,"Dwarka Expy, Sector 88","Euro Intl School, Sector 37D, Gurugram",Reliance Trends Newtown Square Mall,SGT University,SGT Hospital 1,Suncity School,Green Field School,Narayana E Techno,Alpine Convent School,Little E Step –Pre School,Sheetla Mata Mandir,Captain Chandan Lal Marg,CD International School,Raheja Mall,Basai Dhankot Railway Station,First Step Play School,Sri Ma Montessori International,Dwaraka Expressway,Ansal Plaza,Proposed Metro Station,Delhi International Airport,KMP Corridor,Vega Schools Sector 48,Cloudnine Hospital Sector 47,PVR Drive In Theatre,City Hospital,"NH 352W, Pataudi","Pathfinder Global School, Pataudi",Vistar Complex,BML Munjal University (BMU),Bestech Central Square Mall,ORCHIDS The International School,Marengo Asia Hospitals,Sector 42-43 Rapid Metro,Sector 53-54 Rapid Metro,Bank Of Baroda,HDFC Bank ATM,Muincipal Corporation of Gurugram,One Horizon Center Bus Stop,Shalom Hills International School,Satyam Medicare Hospital,Anand Preschool,Choice pharmacy,Qutub Plaza,Sunset point,EPF Regional Office,IFFCO Chowk,Kingdom of Dreams,Gaytri Public School,KIIT College,SPM Hospital,Sealdah Railway Station,International Airport,"Lemon Tree Hotel,","CK Birla Hospital, Gurgaon",Golf Pavilion,Golf Course Road,Ardee Mall,Shiv Nadar School,NH 148A,Ambience Public School,Heritage Intl Xperiential School,Summer Fields School,Primamed Super Speciality Hospital,Uma Sanjeevani Health Centre,Anya Gurgaon,Hotel Golf View Suites,Apollo Pharmacy,Rx Pharmacy,Sector 42/43 Bus Stand,Genpact Chowk Bus Stop,Huda City Centre Metro Station,Sector 53 Metro Station,ICICI Bank ATM,Bharat Petroleum Retail Outlet,DLF Linear Park,Le Meridien Gurgaon,Sector 42-43 Metro Station,Ambience Mall,Fun N Food Village,F9 Go Karting Gurgaon,Proposed Metro corridor,N.H-8,Shiskshantar,DPS,Amity,Pathways,GD Goenka,Medicity,Artemis,"Max, Fortis",Apollo,Paras Trinity Shopping Mall,Swastik Multispeciality Hospital,AIPL Business Co Working Space,Lemon Tree Hotel Sector 60,MKD Hospital,Sant Soordas Sihi Metro Station,De Adventure Amusement Park,Vatika Business Park Sector 49,"Suncity School, Sector 37D",The Signature Advanced Super Speciality,Gurugram University Kankrola,"Candor TechSpace, Sector 48",IndusInd Bank ATM,Cherub's Cradle,Mavens Orange - Hotel,Learning Stars School,State Bank of India,Deerika HyperMart,Triangular Park,Artimis hospital,Sector 45 SO Post Office,FUEL NATION,HSBC,Women Police Station,Best IVF Centre,Huda City Centre,Gurugram Public School,Shikshantar - Primary School,Mamta Hospital,IG International Airport,Omaxe City Centre,DLF Grand Mall,Arvy Hospital,Matrikiran School,DLF Cyber City,Vatika Town Square,Global City Centre,Sohna road dhunela,GD Goenka University,Vardaan Hospital and Trauma Centre,Maharana pratap school,Sector 55-56 Metro,Garhi harsaru railway station Gurgaon,HUB 66,Sealdah,Sector 55-56 Rapid Metro Station,Hasanpur,The Oberoi,Najafgarh Kapashera Road,Hong Kong Bazaar,Bharti International Convent School,"Badshahpur Sohna Rd Hwy, Sector 68",Ashoka International School,"The Oberoi, Gurgaon",GD Goenka Public School,Chauma Road,Chirag Hospital,Sector-21 Metro Dwarka,AIPL Joy Street Mall,Radisson Hotel Sohna Road,iON Digital Zone (Gurugram),HUDA Mini Golf Course,IMT Road,Sohna Gurgaon Road,Spaze Itech Park,"Pallavan PreSchool, Sohna Road",Radisson Hotel Gurugram Sohna Road,Polaris Hospital,RBSM Public school,Health Care Pharmacy,Sector 54 Chowk,EuroKids Preschool Suncity,YES Bank ATM,Suncity School Gurgaon,Suncity Shopping Complex,Vallores Pre School,Umkal Hospital,Haryana City Gas,Marigold Secondary School,Alpine Hospital,Pushpanjali Hospital,Country Inn,Westin,The Millenium School,Rajiv Chowk - Sohna Highway,Central Park Resorts,Swastik Hospital Sec 66,Adarsh Senior Secondary School,Golf Course Extension,"International Tech Park Gurgaon,","Surajgarh Gurgaon, Golf Course Ext Rd",Ananta Hospital,Indus World School,Golf Corse Ext. Rd.,"Dwarka Expy, Dhanwapur Village",Shri Balaji’s Multispeciality Hospital,"Euro International School, Sector 37D","Delhi Public School, Sector 103","Park Inn, Gurgaon",DLF World Tech Park,Star Mall,The Hive Shopping Mall,"NH-8, IMT Manesar",Yaduvanshi Shiksha Niketan,Royal Institute Of Science and Mgt,Newtown Square Mall,NH 352W,Eros Corporate Park,Manesar Road,"Euro International School, Sec 84",Huda Metro Station (Gurugram),InfinityS Badminton Academy,Sanskar Bharti Public School,"Manipal Hospital, Gurugram","HUDA Market, Sector 14",Delhi Gurgaon Expressway,SCC Rooftop Drive-In,Gurugram Railway Station,Kings International School,HUDA Market,Basai Metro Station,CBR Cricket Ground,Rapid Metro Sector 55-56,Kunskapsskolan School,Omaxe Celebration Mall,"Gurgaon - Delhi Expy, Sector 75A",Shalom Presidency School,Sector 55-56 Rapid Metro,Jinga Lala Theme Park Gurgaon Delhi,"Pataudi Rd, Sector 95B",Aarvy Healthcare Super Speciality,Approved Sector 37 Mero Station,Signature Hospital,Xavier’s International,Alpine School,Esplanade Mall,Sector 10 Market,Blue Bells Public School,Galleria 108 Mall,Manipal Hospital,"Vivanta New Delhi, Dwarka",Bharat Ram Global School,Canara Bank ATM,Yes Bank,Arc Hospital,Canara Bank,Axis Bank ATM,City Square,Shishu Kalyan School,Rathore IMT Hospital,DSD College,Patil Station,Amity University,ICFAI University,Indira Gandhi Airport,Sapphire 83,Cambridge Montessori,Hyatt Regency,Rao Bharat Singh International School,Aarvy Healthcare,Aapno Ghar,Cambridge College Of Education,"Euro International School, Sector 84",Dharampeth Main Road,Old Delhi Gurgaon Road,Rotary Public School,Candor Techspace,"Manipal Hospital, Palam Vihar",Moulsari Avenue,"Adarsh public school,Garhi Harsaru",PHC Garhi Harsaru,Excellere World School,Aman Hospital & Surgical Centre,Neemrana Palace,K. R. Mangalam University,Vishwas Hospital,Ibis Hotel,Horizon 1 Mall,Ernst & Young,Paras Hospital,Gurgaon Faridabad Highway,"Mount Olympus School, Sec 79","Singhania University, Manesar",Capital Business Park,Old Sohna Dhani Road,GD Goenka Signature School,Vardaan Hospital & Trauma Centre,Public Bazar,GD Goenka School,Vatika Business Park,Bharat Petrol Pump,The Millennium School,IndusInd Bank,Artemis Hospital,Tau Devi Lal Sports Complex,Children Park,Medanta Dialysis Center,"Central Park, Sohna Rd","HDFC Bank ATM, Dhunela Ghamroj",Ashiana Anmol Kid Centric Homes,"Indianoil, Sohna - Gurgaon Rd",Taj Hotel & Family Restaurant,V-Square Sohna New Residential,G D Goenka World School,"The Phoenix Project, Sohna - Gurgaon Rd",Signature Global Park,Signum 36,"Kotak Mahindra Bank, MBS Tower","Pasco Automobiles, Alipur, Sohna",Sohna Bus Stand,Imperio School,Ektaa Hospitals,Vipul Trade Business Centre,Radisson Hotel Gurugram,Airia Mall Sector 68,Damdama More,Civil Hospital,Western Peripheral Expressway,Bhondsi Nature Park,Enkays Hospital,Ram Krishna Public School,Aravalli Hill View Point,Gurugram Global Heights School,Satya The Hive Mall,Gurugram Road,The Signature Super Speciality Hospital,Sunrise University,Country Inn & Suites By Radisson,Yonex Badminton Stadium,Grand Hyatt,Au Grand Air,Indira Gandhi Eye Hospital,Double Tree by Hilton,Swastik Hospital,Jinaglala Theme Park,Scottish International School,Ap Sports cricket ground,Nischay Cricket Academy,DLC Cricket Ground,Drona Sports Village,Ramada by Wyndham Gurgaon,Surajgarh Gurgaon,Apex Plus Hospital,ZEN Golf Range & Academy,The Banyan Tree Hiking Area,MG Road,Plaza Mall,MGF Metropolitan Mall,Lancers International School,Gurjar Samrat Jaipal Khatana Marg,Signature Global Infinity Mall Sohna,Vidya Niketan Sr Sec School,Sanjivani Hospital,Spectra Hospital,Golf Course Extn Road,"Tulip Violet Society, Sector 69","Spaze Palazo, Golf Course Ext Rd",Federal Bank Sector 71,Kunskapsskolan International,"Southern Peripheral Rd, Gurugram",Ektaa Hospitals Main Sohna Rd,Central Bank Of India Sohna Rd,Sanjeevani Hospital - Child Specialist,VATIKA BUSINESS PARK Sohna Rd,"IndianOil, Hasanpur","The Medicity, Spaze iTech Park","Axis Bank, Sohna Rd",Shambhu Dayal High School,Global City Centre Mall,Ascendas OneHub Gurgaon,Flying Wings Badminton Academy,Saraswati Model School,Orchid Business Park,Farrukh Nagar Railway Station,M3m 65th Avenue Mall,DPS International School,Rapid Metro Sector 56,Sneh Hospital,National Highway 8,Appu Ghar Water Park,Tennis Vidyalaya (Tennis Academy),Zooper India Trampoline Park,"Park Dr, DLF Phase 5",Paras Hospitals,Heritage Badminton Academy,Green Field Public School,Kadipur Industrial Area,Spazedge IT Park,JMD Megapolis,Sapphire Mall,"More Hypermart , Vipul business park",Basant Valley Global School,The Paras World School,Vipul Trade Centre,"WorldMark Gurgaon, Maidawas Rd",Artemis Hospital Gurgaon,"Western Peripheral Expy, Gurugram",Raghunath Bal Vidya Mandir School,ESIC Hospital,S N International School,Country Inn and Suites by Radisson,Sector 29 Gurgaon Pubs and Bars,Emaar Business Park,"Southern Peripheral Rd, Dhani",Omaxe City Centre Mall,"Badshahpur Sohna Rd Hwy, Malibu Town",Ektaa Hospital,St. Xavier's School,PVR Drive In Theater,American Express,IDFC FIRST Bank,Sector 42-43,Sector 53-54,MGF Megacity Mall,Fortis hospital,Double Infinity market,Bamroli Cricket Ground,Aman Hospital,Kidzee,Paras Trinity,AIPL Business Club,Narayana e-Techno School - Manesar,"HDFC Bank, Pataudi Rd","SS Omnia, Sector 86",Canara Bank - Nawada Fatehpur,"ICICI Bank ATM, Sector 86",Silver Streak Multi Speciality,RHM Public School,Minda Industries Nawada Fatehpur,"Numberdar market, IMT Manesar","Sodhi's Supermarket, Sector 82",M3M SCO Shop cum Office,Sector 42-43 Rapid Metro Station,Quality Inn Gurgaon,Minda Industries Limited,Central Park II Road,Omex City Centre Mall,Damdama Lake Rd,Sohna Hill Viewpoint,KR Mangalam University Sohna,Hero Honda Chowk,Jagdish Super Market,Gyaananda School,Bharat Petroleum Shree Shyam Filling,"The Club, International City",Conscient One,"ICICI BANK ATM, Annapurna MKT",ESIC Dispensary,Canara Bank New Palam Vihar,Dwarka,Radha Krishan Mandir,Daultabad Stadium,Gurgaon Gramin Bank,IGIA Airport,SCR Model School,Golden Tulip Suites Gurgaon,South point Mall,Pathways School Gurgaon,Kidzee Sec-93,Jhankar Group of Institutions,Dwarka Expy/Northern Peripheral Rd,Dwarka expressway Basai crossing,Sethi Hospital,HDFC Bank,The Sixth Element School,K.R.Mangalam World School,Sushil Park,Peer Baba Ki Mazar,Punjab National Bank,CoNexus.Life B35,Medhaam Pre School & Daycare,Moksh Wellness Pvt Ltd.,Marriott Courtyard,World Tech Park,Athena,Bharat Petroleum Petrol Pump,Sanskar Jyoti School,Arc Multi Speciality Hospital,Narayana e Techno School,"Medeor Hospital, Manesar",Guls' Kitchen,The Nook,Open Tap,Frescos,Subway,BOB ATM,PNB ATM,Citibank ATM,Gurugram Hospital,Govind Hospital,Manish Gallexie 91,Silver Streak Multi Speciality Hospital,Holiday Inn Gurugram,Airport,Vatika Sector Road,Gurugram University Sector 87,CNG Petrol Pump,Vivek Model School,Dwarka Expressway Link Road,McDonald's India 24 Hours,Garhi Budhera Road,Iris Broadway Gurugram,iGrow Montessori Play School,Matrikiran High School,Badsa AMS Hospital,GlobalHealthcare Multispeciality,Cricket Academy,V'Lante Mall,NH 48 Gurugram,Patli Railway Station,V Club,"Fitso Sector 48 Spuddy, Badminton",Lotus Valley International School,Badshapur Sohna Highway,Bharat Singh fuel company,Basai Enclave Park,Bank Of Baroda ATM,The Holy Kingdom Public School,Shiv Mandir,Open gym garden,KFG sports club Parking,Sector 37 Police Station,Alfaa Health Care Hospital,Euro Intl School Sec-51,Mall Fifty One,"NH 8, Sector 15 Part 2",K.D. Hospital,Gurgaon Road,Saint Paul's School,Indus valley Public School,MDS Public School,Signature Super Speciality Hospital,Harsaru Village Bus Stop,Jadon Pharmacy,JMS Crosswalk,Essar Petrol Pump,The Heritage Pride Modern School,SS Omnia Mall,Miracles Apollo Cradle / Spectra,Gurgaon Toll,Propose Metro Station,Rajiv Chowk,Lions Public School,M3M Cosmopolitan,M3M International Financial Center (IFC),"Badshahpur Sohna Rd Hwy, Haryana",Holiday Inn Express Gurugram Sec 50,"NH 48, Sector 78",ICICI ATM,Sai Sports Club cricket ground,Silver Streak Hospital,Gurukul Preschool,HP PETROL PUMP Unnamed Rd,INOX Cinema,Nawada Cricket Accadmy,Arc Multi Speciality,Sanjeevani Hospital,Baba Kanala Chowk,Dronacharya College of Engineering,Netaji Subhash Marg,"Euro International School, sector- 51",NH 248 A,NH 248,Faridabad,Delhi-Mumbai Expressway,IMT Sohna,Kundli Manesar Palwal Expressway,KR Mangalam,SCJ Academy,Taj,Damdama Lake,Ascendas OneHub Gurgaon Business Park,GD Goenka High School,"Badshahpur Sohna Rd Hwy, Rajoria Ngr","GD Goenka University, Gurugram",Jhankar Senior Secondary School,Entertainland Mall,Aravalli Hills,Delhi,Red Roses Public School,Delhi Jaipur Highway,Galleria Market,Fortis Memorial Research Institute,The Westin Hotel,BM College of Technology & Mgmt,NeoSquare Shopping Mall,Glorious World School,MG Road Metro Station,Lovely Public School,AIPL Business Centre,Signature Advanced Hospital,"iON Digital Zone, Gurgaon",Sapphire 93 Mall,RPS International School Sector 89,Signature tower,Jharsha Chowk,Umang Bhawaj Chawk,Basai Dhancourt Railway Station,AIIMS Jhajjar,Vedic Hospital,Balaji Hospital,SGT Medical College,Garima Public School,Tigra Market,Imperfecto Patio,ISKCON Temple,APJ Abdul Kalam Park,Ramprastha Police Post,Taxila cricket ground,St Pauls School,Edge towers tennis court,SGT UHTC Basai,Hanuman & Shani Mandir,KFG Sports Club,Metro Station Kankrola sec 87,Vatika City Centre Mall,Broadways International School,Sultanpur National Park,"Dwarka Expy, Block D, New Palam Vihar","Global Foyer Mall, Palam Vihar",Ocus Medley Mall,The Westin Gurgaon,Colonel's Central Academy,Trident Hotel Gurgaon,Signum 107,Nora Solomon Medicenter,Najafgarh Jheel Bird Sanctuary,ICICI Bank,INXT High Street,iGrow Montessori,Urusvati Museum Of Folklore,Prakash Hospital,Aravali Adventure Hill,"KDM Public School, Sohna","Badshahpur Sohna Rd Hwy, Raghav Vatika",Discount Department Store,Kinder Care Playschool,Kangaroo Kids Preschool,BigBazaar,SRS Cinemas,VIBGYOR High School,Gyan Bharti Public School,Keshav Pharmacy,Diamond Public School,Mother land public school,Kamal Hospital,Creative Tennis Academy,Shanti Tennis Academy,Lotus Sports Academy,ISBM College,Huda city center,Centrum Plaza,Shoppers Stop,Suncity Market,Govt. Model Sanskriti Primary School,Cyber ​​Park,IILM School of Management,Shree Deep Petrol Pump,Gurugram City Bus Depot,Starbucks,Khatu Shyam Mandir,Mps World School,Northern Peripheral Road,Tomar Hospital,Taj City Centre Hotel,DPS Sector 103,Cambridge Montessori Preschool,Shree Balaji College,New Water Pond,Sun's Spa,Cool Deck Coffee,Shivai Hospital,Solitaire Banquet Hall,Hud

In [50]:
cosine_sim3 = cosine_similarity(location_df_normalized)

In [51]:
cosine_sim3.shape

(246, 246)

In [57]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 0.5*cosine_sim1 + 0.8*cosine_sim2 + 1*cosine_sim3
    # cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('Godrej Aria')

               PropertyName  SimilarityScore
0             M3M Sierra 68         0.876958
1               BPTP Spacio         0.836801
2                 ILD Grand         0.831934
3          SS The Coralwood         0.766552
4            Unitech Fresco         0.746331
..                      ...              ...
240   Elan The Presidential        -0.384885
241  Pioneer Urban Presidia        -0.399343
242      Emaar MGF Marbella        -0.416441
243           Tata Primanti        -0.425275
244     Whiteland The Aspen        -0.429019

[245 rows x 2 columns]

In [54]:
import pickle

In [83]:
pickle.dump(location_df, open('location_distance.pkl', 'wb'))

In [84]:
location_df[location_df['Bajghera Road'] < 2000]

,Bajghera Road,Palam Vihar Halt,DPSG Palam Vihar,Park Hospital,Gurgaon Railway Station,The NorthCap University,Dwarka Expressway,Hyatt Place Gurgaon Udyog Vihar,"Dwarka Sector 21, Metro Station",Pacific D21 Mall,Indira Gandhi International Airport,Hamoni Golf Camp,Fun N Food Water Park,Accenture DDC5,DPSG Palam Vihar Gurugram,"Park Hospital, Palam Vihar",Palam Vihar Halt Railway Station,Tau DeviLal Sports Complex,Hyatt Place,Altrade Business Centre,AIPL Business Club Sector 62,Heritage Xperiential Learning School,CK Birla Hospital,Paras Trinity Mall Sector 63,Rapid Metro Station Sector 56,De Adventure Park,Golf Course Ext Road,DoubleTree by Hilton Hotel Gurgaon,KIIT College of Engineering Sohna Road,Mehrauli-Gurgaon Road,Nirvana Rd,TERI Golf Course,The Shikshiyan School,WTC Plaza,Luxus Haritma Resort,BSF Golf Course,Rions Hospital,Gurgaon,Dwarka Sector 21,Nehru Stadium,IGI Airport,Vasant Kunj,Pranavananda International School,DLF Site central office,Holiday Inn Gurugram Sector 90,Krishna Hospital,Royal Institute Of Science,Sapphire 83 Mall,NH 48,Garhi Harsaru Junction,Manesar Golf Course,AapnoGhar,Vega Schools NH-8,DLF Corporate Greens,Miracles Apollo Cradle Hospital,Hyatt Regency Gurugram,Golden Greens Golf & Resorts Limited,Mount Olympus Junior School,Miracles Apollo Hospital,NH -8,"Savoy Suites, Manesar",Golden Greens Golf & Resorts,IMT Manesar,Amity University Gurugram,Golf Course Extension Road,"Dwarka Expy, Sector 109","Euro International School, Sector- 109.",Jai Sai Ram Hospital,Aryan Hospital,Idea Cosmic Plaza,Royal Institute Of Science & Management,Pataudi Road,Holiday Inn Sector 90,RPS International School,Aarvy Healthcare Hospital,Iris Broadway Mall,Imperia Mindspace,AIPL Business Tower,Heritage School,"Lotus Valley Intl School, Gurgaon",Gurugram University,Sector 55-56 Metro Station,Omaxe Gurgaon Mall,Sushant University,"Badshahpur Sohna Rd Hwy,Sector 48",Naurangpur Cricket Stadium,Naurangpur Road,National Highway 48,Vatika Town Square-INXT,Ompee International School,Manesar Bus Stand,Yashlok Medical Centre,Euro International School,WorldMark Gurgaon,Capital Cyberscape,The Shriram Millennium School,DoubleTree by Hilton Hotel,Badshahpur Sohna Hwy,Nakhrola Stadium,Delhi - Jaipur Expressway,Vatika Town Square-INXT Mall,Savoy Suites,Bal Bharati Public School,Vatika Business Centre,St. Xavier's High School,Miracles Apollo Cradle,Ambience Mall New,Hyatt Regency Gurgaon,Delhi Public School,Elan Miracle Mall,Miracles Apollo Cradle Spectra Hospital,Agri Business Management Collage,Grand Hyatt Gurgaon,Duke Horse Riding Club,PVR Drive In Cinema,W Pratiksha Hospital,Metro World Mall,Unicosmos School,Faridabad - Gurgaon Road,Sohna Road,Bestech Business Tower,Appu Ghar,SkyJumper Trampoline Park,Axis Bank,KMP Expressway,Karma Lakelands,Jungle Safari & Trails,DPS Manesar,Medanta Hospital,Lingaya's Lalita Devi Institute,ASF Insignia SEZ,Banjara Market Gurugram,Central Plaza Mall,"Paras Hospitals, Gurgaon",Badshahpur Sohna Rd Hwy,Vega School,Indian School of Hospitality,Vatika City Centre,Aatish Hospital,Info Technology Park Phase 2,Huda Metro Station,Southern Peripheral Road,Global Ways School,Radisson Hotel,NH 248A,Mavens Inn,Sanar International Hospital,Sector 53-54 Metro Station,"IILM University, Gurugram",The Banyan Tree World School,The Big Tree Cafe,DLF Golf and Country Club,"Delhi Public School, Sector 84",Aarvy Hospital,DPG Degree College,Shivani public school,Baghera University,Kutumbh Hospital,Bijwasan Railway Station,Global Foyer Mall,Phase 2 Metro Station,Gurgaon Dreamz Mall,"Metro Hospital, Palam Vihar",Delhi Ajmer Expressway,Infinity Business Park,Rion's Hospital,"Heritage Xperiential Learning, CRPF Rd",Sector 54 Chowk Metro Station,Gurgaon - Delhi Expy,Genesis Hospital Sector 84,DPGITM Engineering College Sector 34,Sapphire 83 Mall Sector 83,Holiday Inn Hotel Sector 90,SkyJumper Trampoline Park Gurgaon,National Tennis Academy Sector 98,NH-8 Delhi Jaipur Highway,Nouveau Medics Multispeciality OPD,Heritage Village Resort & Spa,Sector 86 Road,Genesis Hospital,Delh-Ajmer Expy,DPG Institute of Technology,Medanta - The Medicity,Airia Mall,Amma Hospital,DPS International Edge,Eros City Square,Splendor Trade Tower,Narayana Junior College,Sector 55 Metro Station,Dharampur Main Road,Oyster's Water Park,Vivanta Dwarka New Delhi,DLF Corporate Park,GD Goenka World School,KR Mangalam University,Smart View Hotel and Resort,Central Park Flower Valley,Shopping complex,Central Peripheral Road,Nakhrola Stadium Sector 81A,NH 08,G D Goenka University,Fly India Adventure Resort,Vardaan Hospital,IMT Office Sohna,JMS Marine Square Mall,Vibrant Hospital,Prime Scholars International School,Ramgarh Farms & Resort,Basai Road,Shree Krishna Hospital,The Esplanade Mall,GEMS International School,Greenway Hospital,National Tennis Academy,Paras Trinity Mall,Rajesh Pilot Road,Scottish High International School,KIIT College of Engineering,The Vivekananda School,Holiday Inn Express Gurugram Sector 50,Early Basket Grocery shop,Aradhya Cricket Club Gurgaon,Imperial Heritage School,Daultabad Village Park,Skylark Cricket Academy,Yashroop Hospital,Gurgaon Old Railway Station,Domino's Pizza,Conscient One Mall,Emerald Plaza Shopping Mall,Pawlywoof - Dog Park,SCC Drive-In Cinema,"Lemon Tree Hotel, Sohna Road",Shiksha Bharti Public School,Holiday Inn Express Gurugram,Sahara Mall,Dhanwapur Road,Govt. PG College,Basai Dhankot,Park Inn,IFFCO Chowk Metro Station,The Executive Centre,"Dwarka Expy, Sector 88","Euro Intl School, Sector 37D, Gurugram",Reliance Trends Newtown Square Mall,SGT University,SGT Hospital 1,Suncity School,Green Field School,Narayana E Techno,Alpine Convent School,Little E Step –Pre School,Sheetla Mata Mandir,Captain Chandan Lal Marg,CD International School,Raheja Mall,Basai Dhankot Railway Station,First Step Play School,Sri Ma Montessori International,Dwaraka Expressway,Ansal Plaza,Proposed Metro Station,Delhi International Airport,KMP Corridor,Vega Schools Sector 48,Cloudnine Hospital Sector 47,PVR Drive In Theatre,City Hospital,"NH 352W, Pataudi","Pathfinder Global School, Pataudi",Vistar Complex,BML Munjal University (BMU),Bestech Central Square Mall,ORCHIDS The International School,Marengo Asia Hospitals,Sector 42-43 Rapid Metro,Sector 53-54 Rapid Metro,Bank Of Baroda,HDFC Bank ATM,Muincipal Corporation of Gurugram,One Horizon Center Bus Stop,Shalom Hills International School,Satyam Medicare Hospital,Anand Preschool,Choice pharmacy,Qutub Plaza,Sunset point,EPF Regional Office,IFFCO Chowk,Kingdom of Dreams,Gaytri Public School,KIIT College,SPM Hospital,Sealdah Railway Station,International Airport,"Lemon Tree Hotel,","CK Birla Hospital, Gurgaon",Golf Pavilion,Golf Course Road,Ardee Mall,Shiv Nadar School,NH 148A,Ambience Public School,Heritage Intl Xperiential School,Summer Fields School,Primamed Super Speciality Hospital,Uma Sanjeevani Health Centre,Anya Gurgaon,Hotel Golf View Suites,Apollo Pharmacy,Rx Pharmacy,Sector 42/43 Bus Stand,Genpact Chowk Bus Stop,Huda City Centre Metro Station,Sector 53 Metro Station,ICICI Bank ATM,Bharat Petroleum Retail Outlet,DLF Linear Park,Le Meridien Gurgaon,Sector 42-43 Metro Station,Ambience Mall,Fun N Food Village,F9 Go Karting Gurgaon,Proposed Metro corridor,N.H-8,Shiskshantar,DPS,Amity,Pathways,GD Goenka,Medicity,Artemis,"Max, Fortis",Apollo,Paras Trinity Shopping Mall,Swastik Multispeciality Hospital,AIPL Business Co Working Space,Lemon Tree Hotel Sector 60,MKD Hospital,Sant Soordas Sihi Metro Station,De Adventure Amusement Park,Vatika Business Park Sector 49,"Suncity School, Sector 37D",The Signature Advanced Super Speciality,Gurugram University Kankrola,"Candor TechSpace, Sector 48",IndusInd Bank ATM,Cherub's Cradle,Mavens Orange - Hotel,Learning Stars School,State Bank of India,Deerika HyperMart,Triangular Park,Artimis hospital,Sector 45 SO Post Office,FUEL NATION,HSBC,Women Police Station,Best IVF Centre,Huda City Centre,Gurugram Public School,Shikshantar - Primary School,Mamta Hospital,IG International Airport,Omaxe City Centre,DLF Grand Mall,Arvy Hospital,Matrikiran School,DLF Cyber City,Vatika Town Square,Global City Centre,Sohna road dhunela,GD Goenka University,Vardaan Hospital and Trauma Centre,Maharana pratap school,Sector 55-56 Metro,Garhi harsaru railway station Gurgaon,HUB 66,Sealdah,Sector 55-56 Rapid Metro Station,Hasanpur,The Oberoi,Najafgarh Kapashera Road,Hong Kong Bazaar,Bharti International Convent School,"Badshahpur Sohna Rd Hwy, Sector 68",Ashoka International School,"The Oberoi, Gurgaon",GD Goenka Public School,Chauma Road,Chirag Hospital,Sector-21 Metro Dwarka,AIPL Joy Street Mall,Radisson Hotel Sohna Road,iON Digital Zone (Gurugram),HUDA Mini Golf Course,IMT Road,Sohna Gurgaon Road,Spaze Itech Park,"Pallavan PreSchool, Sohna Road",Radisson Hotel Gurugram Sohna Road,Polaris Hospital,RBSM Public school,Health Care Pharmacy,Sector 54 Chowk,EuroKids Preschool Suncity,YES Bank ATM,Suncity School Gurgaon,Suncity Shopping Complex,Vallores Pre School,Umkal Hospital,Haryana City Gas,Marigold Secondary School,Alpine Hospital,Pushpanjali Hospital,Country Inn,Westin,The Millenium School,Rajiv Chowk - Sohna Highway,Central Park Resorts,Swastik Hospital Sec 66,Adarsh Senior Secondary School,Golf Course Extension,"International Tech Park Gurgaon,","Surajgarh Gurgaon, Golf Course Ext Rd",Ananta Hospital,Indus World School,Golf Corse Ext. Rd.,"Dwarka Expy, Dhanwapur Village",Shri Balaji’s Multispeciality Hospital,"Euro International School, Sector 37D","Delhi Public School, Sector 103","Park Inn, Gurgaon",DLF World Tech Park,Star Mall,The Hive Shopping Mall,"NH-8, IMT Manesar",Yaduvanshi Shiksha Niketan,Royal Institute Of Science and Mgt,Newtown Square Mall,NH 352W,Eros Corporate Park,Manesar Road,"Euro International School, Sec 84",Huda Metro Station (Gurugram),InfinityS Badminton Academy,Sanskar Bharti Public School,"Manipal Hospital, Gurugram","HUDA Market, Sector 14",Delhi Gurgaon Expressway,SCC Rooftop Drive-In,Gurugram Railway Station,Kings International School,HUDA Market,Basai Metro Station,CBR Cricket Ground,Rapid Metro Sector 55-56,Kunskapsskolan School,Omaxe Celebration Mall,"Gurgaon - Delhi Expy, Sector 75A",Shalom Presidency School,Sector 55-56 Rapid Metro,Jinga Lala Theme Park Gurgaon Delhi,"Pataudi Rd, Sector 95B",Aarvy Healthcare Super Speciality,Approved Sector 37 Mero Station,Signature Hospital,Xavier’s International,Alpine School,Esplanade Mall,Sector 10 Market,Blue Bells Public School,Galleria 108 Mall,Manipal Hospital,"Vivanta New Delhi, Dwarka",Bharat Ram Global School,Canara Bank ATM,Yes Bank,Arc Hospital,Canara Bank,Axis Bank ATM,City Square,Shishu Kalyan School,Rathore IMT Hospital,DSD College,Patil Station,Amity University,ICFAI University,Indira Gandhi Airport,Sapphire 83,Cambridge Montessori,Hyatt Regency,Rao Bharat Singh International School,Aarvy Healthcare,Aapno Ghar,Cambridge College Of Education,"Euro International School, Sector 84",Dharampeth Main Road,Old Delhi Gurgaon Road,Rotary Public School,Candor Techspace,"Manipal Hospital, Palam Vihar",Moulsari Avenue,"Adarsh public school,Garhi Harsaru",PHC Garhi Harsaru,Excellere World School,Aman Hospital & Surgical Centre,Neemrana Palace,K. R. Mangalam University,Vishwas Hospital,Ibis Hotel,Horizon 1 Mall,Ernst & Young,Paras Hospital,Gurgaon Faridabad Highway,"Mount Olympus School, Sec 79","Singhania University, Manesar",Capital Business Park,Old Sohna Dhani Road,GD Goenka Signature School,Vardaan Hospital & Trauma Centre,Public Bazar,GD Goenka School,Vatika Business Park,Bharat Petrol Pump,The Millennium School,IndusInd Bank,Artemis Hospital,Tau Devi Lal Sports Complex,Children Park,Medanta Dialysis Center,"Central Park, Sohna Rd","HDFC Bank ATM, Dhunela Ghamroj",Ashiana Anmol Kid Centric Homes,"Indianoil, Sohna - Gurgaon Rd",Taj Hotel & Family Restaurant,V-Square Sohna New Residential,G D Goenka World School,"The Phoenix Project, Sohna - Gurgaon Rd",Signature Global Park,Signum 36,"Kotak Mahindra Bank, MBS Tower","Pasco Automobiles, Alipur, Sohna",Sohna Bus Stand,Imperio School,Ektaa Hospitals,Vipul Trade Business Centre,Radisson Hotel Gurugram,Airia Mall Sector 68,Damdama More,Civil Hospital,Western Peripheral Expressway,Bhondsi Nature Park,Enkays Hospital,Ram Krishna Public School,Aravalli Hill View Point,Gurugram Global Heights School,Satya The Hive Mall,Gurugram Road,The Signature Super Speciality Hospital,Sunrise University,Country Inn & Suites By Radisson,Yonex Badminton Stadium,Grand Hyatt,Au Grand Air,Indira Gandhi Eye Hospital,Double Tree by Hilton,Swastik Hospital,Jinaglala Theme Park,Scottish International School,Ap Sports cricket ground,Nischay Cricket Academy,DLC Cricket Ground,Drona Sports Village,Ramada by Wyndham Gurgaon,Surajgarh Gurgaon,Apex Plus Hospital,ZEN Golf Range & Academy,The Banyan Tree Hiking Area,MG Road,Plaza Mall,MGF Metropolitan Mall,Lancers International School,Gurjar Samrat Jaipal Khatana Marg,Signature Global Infinity Mall Sohna,Vidya Niketan Sr Sec School,Sanjivani Hospital,Spectra Hospital,Golf Course Extn Road,"Tulip Violet Society, Sector 69","Spaze Palazo, Golf Course Ext Rd",Federal Bank Sector 71,Kunskapsskolan International,"Southern Peripheral Rd, Gurugram",Ektaa Hospitals Main Sohna Rd,Central Bank Of India Sohna Rd,Sanjeevani Hospital - Child Specialist,VATIKA BUSINESS PARK Sohna Rd,"IndianOil, Hasanpur","The Medicity, Spaze iTech Park","Axis Bank, Sohna Rd",Shambhu Dayal High School,Global City Centre Mall,Ascendas OneHub Gurgaon,Flying Wings Badminton Academy,Saraswati Model School,Orchid Business Park,Farrukh Nagar Railway Station,M3m 65th Avenue Mall,DPS International School,Rapid Metro Sector 56,Sneh Hospital,National Highway 8,Appu Ghar Water Park,Tennis Vidyalaya (Tennis Academy),Zooper India Trampoline Park,"Park Dr, DLF Phase 5",Paras Hospitals,Heritage Badminton Academy,Green Field Public School,Kadipur Industrial Area,Spazedge IT Park,JMD Megapolis,Sapphire Mall,"More Hypermart , Vipul business park",Basant Valley Global School,The Paras World School,Vipul Trade Centre,"WorldMark Gurgaon, Maidawas Rd",Artemis Hospital Gurgaon,"Western Peripheral Expy, Gurugram",Raghunath Bal Vidya Mandir School,ESIC Hospital,S N International School,Country Inn and Suites by Radisson,Sector 29 Gurgaon Pubs and Bars,Emaar Business Park,"Southern Peripheral Rd, Dhani",Omaxe City Centre Mall,"Badshahpur Sohna Rd Hwy, Malibu Town",Ektaa Hospital,St. Xavier's School,PVR Drive In Theater,American Express,IDFC FIRST Bank,Sector 42-43,Sector 53-54,MGF Megacity Mall,Fortis hospital,Double Infinity market,Bamroli Cricket Ground,Aman Hospital,Kidzee,Paras Trinity,AIPL Business Club,Narayana e-Techno School - Manesar,"HDFC Bank, Pataudi Rd","SS Omnia, Sector 86",Canara Bank - Nawada Fatehpur,"ICICI Bank ATM, Sector 86",Silver Streak Multi Speciality,RHM Public School,Minda Industries Nawada Fatehpur,"Numberdar market, IMT Manesar","Sodhi's Supermarket, Sector 82",M3M SCO Shop cum Office,Sector 42-43 Rapid Metro Station,Quality Inn Gurgaon,Minda Industries Limited,Central Park II Road,Omex City Centre Mall,Damdama Lake Rd,Sohna Hill Viewpoint,KR Mangalam University Sohna,Hero Honda Chowk,Jagdish Super Market,Gyaananda School,Bharat Petroleum Shree Shyam Filling,"The Club, International City",Conscient One,"ICICI BANK ATM, Annapurna MKT",ESIC Dispensary,Canara Bank New Palam Vihar,Dwarka,Radha Krishan Mandir,Daultabad Stadium,Gurgaon Gramin Bank,IGIA Airport,SCR Model School,Golden Tulip Suites Gurgaon,South point Mall,Pathways School Gurgaon,Kidzee Sec-93,Jhankar Group of Institutions,Dwarka Expy/Northern Peripheral Rd,Dwarka expressway Basai crossing,Sethi Hospital,HDFC Bank,The Sixth Element School,K.R.Mangalam World School,Sushil Park,Peer Baba Ki Mazar,Punjab National Bank,CoNexus.Life B35,Medhaam Pre School & Daycare,Moksh Wellness Pvt Ltd.,Marriott Courtyard,World Tech Park,Athena,Bharat Petroleum Petrol Pump,Sanskar Jyoti School,Arc Multi Speciality Hospital,Narayana e Techno School,"Medeor Hospital, Manesar",Guls' Kitchen,The Nook,Open Tap,Frescos,Subway,BOB ATM,PNB ATM,Citibank ATM,Gurugram Hospital,Govind Hospital,Manish Gallexie 91,Silver Streak Multi Speciality Hospital,Holiday Inn Gurugram,Airport,Vatika Sector Road,Gurugram University Sector 87,CNG Petrol Pump,Vivek Model School,Dwarka Expressway Link Road,McDonald's India 24 Hours,Garhi Budhera Road,Iris Broadway Gurugram,iGrow Montessori Play School,Matrikiran High School,Badsa AMS Hospital,GlobalHealthcare Multispeciality,Cricket Academy,V'Lante Mall,NH 48 Gurugram,Patli Railway Station,V Club,"Fitso Sector 48 Spuddy, Badminton",Lotus Valley International School,Badshapur Sohna Highway,Bharat Singh fuel company,Basai Enclave Park,Bank Of Baroda ATM,The Holy Kingdom Public School,Shiv Mandir,Open gym garden,KFG sports club Parking,Sector 37 Police Station,Alfaa Health Care Hospital,Euro Intl School Sec-51,Mall Fifty One,"NH 8, Sector 15 Part 2",K.D. Hospital,Gurgaon Road,Saint Paul's School,Indus valley Public School,MDS Public School,Signature Super Speciality Hospital,Harsaru Village Bus Stop,Jadon Pharmacy,JMS Crosswalk,Essar Petrol Pump,The Heritage Pride Modern School,SS Omnia Mall,Miracles Apollo Cradle / Spectra,Gurgaon Toll,Propose Metro Station,Rajiv Chowk,Lions Public School,M3M Cosmopolitan,M3M International Financial Center (IFC),"Badshahpur Sohna Rd Hwy, Haryana",Holiday Inn Express Gurugram Sec 50,"NH 48, Sector 78",ICICI ATM,Sai Sports Club cricket ground,Silver Streak Hospital,Gurukul Preschool,HP PETROL PUMP Unnamed Rd,INOX Cinema,Nawada Cricket Accadmy,Arc Multi Speciality,Sanjeevani Hospital,Baba Kanala Chowk,Dronacharya College of Engineering,Netaji Subhash Marg,"Euro International School, sector- 51",NH 248 A,NH 248,Faridabad,Delhi-Mumbai Expressway,IMT Sohna,Kundli Manesar Palwal Expressway,KR Mangalam,SCJ Academy,Taj,Damdama Lake,Ascendas OneHub Gurgaon Business Park,GD Goenka High School,"Badshahpur Sohna Rd Hwy, Rajoria Ngr","GD Goenka University, Gurugram",Jhankar Senior Secondary School,Entertainland Mall,Aravalli Hills,Delhi,Red Roses Public School,Delhi Jaipur Highway,Galleria Market,Fortis Memorial Research Institute,The Westin Hotel,BM College of Technology & Mgmt,NeoSquare Shopping Mall,Glorious World School,MG Road Metro Station,Lovely Public School,AIPL Business Centre,Signature Advanced Hospital,"iON Digital Zone, Gurgaon",Sapphire 93 Mall,RPS International School Sector 89,Signature tower,Jharsha Chowk,Umang Bhawaj Chawk,Basai Dhancourt Railway Station,AIIMS Jhajjar,Vedic Hospital,Balaji Hospital,SGT Medical College,Garima Public School,Tigra Market,Imperfecto Patio,ISKCON Temple,APJ Abdul Kalam Park,Ramprastha Police Post,Taxila cricket ground,St Pauls School,Edge towers tennis court,SGT UHTC Basai,Hanuman & Shani Mandir,KFG Sports Club,Metro Station Kankrola sec 87,Vatika City Centre Mall,Broadways International School,Sultanpur National Park,"Dwarka Expy, Block D, New Palam Vihar","Global Foyer Mall, Palam Vihar",Ocus Medley Mall,The Westin Gurgaon,Colonel's Central Academy,Trident Hotel Gurgaon,Signum 107,Nora Solomon Medicenter,Najafgarh Jheel Bird Sanctuary,ICICI Bank,INXT High Street,iGrow Montessori,Urusvati Museum Of Folklore,Prakash Hospital,Aravali Adventure Hill,"KDM Public School, Sohna","Badshahpur Sohna Rd Hwy, Raghav Vatika",Discount Department Store,Kinder Care Playschool,Kangaroo Kids Preschool,BigBazaar,SRS Cinemas,VIBGYOR High School,Gyan Bharti Public School,Keshav Pharmacy,Diamond Public School,Mother land public school,Kamal Hospital,Creative Tennis Academy,Shanti Tennis Academy,Lotus Sports Academy,ISBM College,Huda city center,Centrum Plaza,Shoppers Stop,Suncity Market,Govt. Model Sanskriti Primary School,Cyber ​​Park,IILM School of Management,Shree Deep Petrol Pump,Gurugram City Bus Depot,Starbucks,Khatu Shyam Mandir,Mps World School,Northern Peripheral Road,Tomar Hospital,Taj City Centre Hotel,DPS Sector 103,Cambridge Montessori Preschool,Shree Balaji College,New Water Pond,Sun's Spa,Cool Deck Coffee,Shivai Hospital,Solitaire Banquet Hall,Hud

In [85]:
location_df.columns.tolist()

['Bajghera Road',
 'Palam Vihar Halt',
 'DPSG Palam Vihar',
 'Park Hospital',
 'Gurgaon Railway Station',
 'The NorthCap University',
 'Dwarka Expressway',
 'Hyatt Place Gurgaon Udyog Vihar',
 'Dwarka Sector 21, Metro Station',
 'Pacific D21 Mall',
 'Indira Gandhi International Airport',
 'Hamoni Golf Camp',
 'Fun N Food Water Park',
 'Accenture DDC5',
 'DPSG Palam Vihar Gurugram',
 'Park Hospital, Palam Vihar',
 'Palam Vihar Halt Railway Station',
 'Tau DeviLal Sports Complex',
 'Hyatt Place',
 'Altrade Business Centre',
 'AIPL Business Club Sector 62',
 'Heritage Xperiential Learning School',
 'CK Birla Hospital',
 'Paras Trinity Mall Sector 63',
 'Rapid Metro Station Sector 56',
 'De Adventure Park',
 'Golf Course Ext Road',
 'DoubleTree by Hilton Hotel Gurgaon',
 'KIIT College of Engineering Sohna Road',
 'Mehrauli-Gurgaon Road',
 'Nirvana Rd',
 'TERI Golf Course',
 'The Shikshiyan School',
 'WTC Plaza',
 'Luxus Haritma Resort',
 'BSF Golf Course',
 'Rions Hospital',
 'Gurgaon',
 'Dwarka Sector 21',
 'Nehru Stadium',
 'IGI Airport',
 'Vasant Kunj',
 'Pranavananda International School',
 'DLF Site central office',
 'Holiday Inn Gurugram Sector 90',
 'Krishna Hospital',
 'Royal Institute Of Science',
 'Sapphire 83 Mall',
 'NH 48',
 'Garhi Harsaru Junction',
 'Manesar Golf Course',
 'AapnoGhar',
 'Vega Schools NH-8',
 'DLF Corporate Greens',
 'Miracles Apollo Cradle Hospital',
 'Hyatt Regency Gurugram',
 'Golden Greens Golf & Resorts Limited',
 'Mount Olympus Junior School',
 'Miracles Apollo Hospital',
 'NH -8',
 'Savoy Suites, Manesar',
 'Golden Greens Golf & Resorts',
 'IMT Manesar',
 'Amity University Gurugram',
 'Golf Course Extension Road',
 'Dwarka Expy, Sector 109',
 'Euro International School, Sector- 109.',
 'Jai Sai Ram Hospital',
 'Aryan Hospital',
 'Idea Cosmic Plaza',
 'Royal Institute Of Science & Management',
 'Pataudi Road',
 'Holiday Inn Sector 90',
 'RPS International School',
 'Aarvy Healthcare Hospital',
 'Iris Broadway Mall',
 'Imperia Mindspace',
 'AIPL Business Tower',
 'Heritage School',
 'Lotus Valley Intl School, Gurgaon',
 'Gurugram University',
 'Sector 55-56 Metro Station',
 'Omaxe Gurgaon Mall',
 'Sushant University',
 'Badshahpur Sohna Rd Hwy,Sector 48',
 'Naurangpur Cricket Stadium',
 'Naurangpur Road',
 'National Highway  48',
 'Vatika Town Square-INXT',
 'Ompee International School',
 'Manesar Bus Stand',
 'Yashlok Medical Centre',
 'Euro International School',
 'WorldMark Gurgaon',
 'Capital Cyberscape',
 'The Shriram Millennium School',
 'DoubleTree by Hilton Hotel',
 'Badshahpur Sohna Hwy',
 'Nakhrola Stadium',
 'Delhi - Jaipur Expressway',
 'Vatika Town Square-INXT Mall',
 'Savoy Suites',
 'Bal Bharati Public School',
 'Vatika Business Centre',
 "St. Xavier's High School",
 'Miracles Apollo Cradle',
 'Ambience Mall New',
 'Hyatt Regency Gurgaon',
 'Delhi Public School',
 'Elan Miracle Mall',
 'Miracles Apollo Cradle Spectra Hospital',
 'Agri Business Management Collage',
 'Grand Hyatt Gurgaon',
 'Duke Horse Riding Club',
 'PVR Drive In Cinema',
 'W Pratiksha Hospital',
 'Metro World Mall',
 'Unicosmos School',
 'Faridabad - Gurgaon Road',
 'Sohna Road',
 'Bestech Business Tower',
 'Appu Ghar',
 'SkyJumper Trampoline Park',
 'Axis Bank',
 'KMP Expressway',
 'Karma Lakelands',
 'Jungle Safari & Trails',
 'DPS Manesar',
 'Medanta Hospital',
 "Lingaya's Lalita Devi Institute",
 'ASF Insignia SEZ',
 'Banjara Market Gurugram',
 'Central Plaza Mall',
 'Paras Hospitals, Gurgaon',
 'Badshahpur Sohna Rd Hwy',
 'Vega School',
 'Indian School of Hospitality',
 'Vatika City Centre',
 'Aatish Hospital',
 'Info Technology Park Phase 2',
 'Huda Metro Station',
 'Southern Peripheral Road',
 'Global Ways School',
 'Radisson Hotel',
 'NH 248A',
 'Mavens Inn',
 'Sanar International Hospital',
 'Sector 53-54 Metro Station',
 'IILM University, Gurugram',
 'The Banyan Tree World School',
 'The Big Tree Cafe',
 'DLF Golf and Country Club',
 'Delhi Public School, Sector 84',
 'Aarvy Hospital',
 'DPG Degree College',
 'Shivani public school',
 'Baghera University',
 'Kutumbh Hospital',
 'Bijwasan Railway Station',
 'Global Foyer Mall',
 'Phase 2 Metro Station',
 'Gurgaon Dreamz Mall',
 'Metro Hospital, Palam Vihar',
 'Delhi Ajmer Expressway',
 'Infinity Business Park',
 "Rion's Hospital",
 'Heritage Xperiential Learning, CRPF Rd',
 'Sector 54 Chowk Metro Station',
 'Gurgaon - Delhi Expy',
 'Genesis Hospital Sector 84',
 'DPGITM Engineering College Sector 34',
 'Sapphire 83 Mall Sector 83',
 'Holiday Inn Hotel Sector 90',
 'SkyJumper Trampoline Park Gurgaon',
 'National Tennis Academy Sector 98',
 'NH-8 Delhi Jaipur Highway',
 'Nouveau Medics Multispeciality OPD',
 'Heritage Village Resort & Spa',
 'Sector 86 Road',
 'Genesis Hospital',
 'Delh-Ajmer Expy',
 'DPG Institute of Technology',
 'Medanta - The Medicity',
 'Airia Mall',
 'Amma Hospital',
 'DPS International Edge',
 'Eros City Square',
 'Splendor Trade Tower',
 'Narayana Junior College',
 'Sector 55 Metro Station',
 'Dharampur Main Road',
 "Oyster's Water Park",
 'Vivanta Dwarka New Delhi',
 'DLF Corporate Park',
 'GD Goenka World School',
 'KR Mangalam University',
 'Smart View Hotel and Resort',
 'Central Park Flower Valley',
 'Shopping complex',
 'Central Peripheral Road',
 'Nakhrola Stadium Sector 81A',
 'NH 08',
 'G D Goenka University',
 'Fly India Adventure Resort',
 'Vardaan Hospital',
 'IMT Office Sohna',
 'JMS Marine Square Mall',
 'Vibrant Hospital',
 'Prime Scholars International School',
 'Ramgarh Farms & Resort',
 'Basai Road',
 'Shree Krishna Hospital',
 'The Esplanade Mall',
 'GEMS International School',
 'Greenway Hospital',
 'National Tennis Academy',
 'Paras Trinity Mall',
 'Rajesh Pilot Road',
 'Scottish High International School',
 'KIIT College of Engineering',
 'The Vivekananda School',
 'Holiday Inn Express Gurugram Sector 50',
 'Early Basket Grocery shop',
 'Aradhya Cricket Club Gurgaon',
 'Imperial Heritage School',
 'Daultabad Village Park',
 'Skylark Cricket Academy',
 'Yashroop Hospital',
 'Gurgaon Old Railway Station',
 "Domino's Pizza",
 'Conscient One Mall',
 'Emerald Plaza Shopping Mall',
 'Pawlywoof - Dog Park',
 'SCC Drive-In Cinema',
 'Lemon Tree Hotel, Sohna Road',
 'Shiksha Bharti Public School',
 'Holiday Inn Express Gurugram',
 'Sahara Mall',
 'Dhanwapur Road',
 'Govt. PG College',
 'Basai Dhankot',
 'Park Inn',
 'IFFCO Chowk Metro Station',
 'The Executive Centre',
 'Dwarka Expy, Sector 88',
 'Euro Intl School, Sector 37D, Gurugram',
 'Reliance Trends Newtown Square Mall',
 'SGT University',
 'SGT Hospital 1',
 'Suncity School',
 'Green Field School',
 'Narayana E Techno',
 'Alpine Convent School',
 'Little E Step –Pre School',
 'Sheetla Mata Mandir',
 'Captain Chandan Lal Marg',
 'CD International School',
 'Raheja Mall',
 'Basai Dhankot Railway Station',
 'First Step Play School',
 'Sri Ma Montessori International',
 'Dwaraka Expressway',
 'Ansal Plaza',
 'Proposed Metro Station',
 'Delhi International Airport',
 'KMP Corridor',
 'Vega Schools Sector 48',
 'Cloudnine Hospital Sector 47',
 'PVR Drive In Theatre',
 'City Hospital',
 'NH 352W, Pataudi',
 'Pathfinder Global School, Pataudi',
 'Vistar Complex',
 'BML Munjal University (BMU)',
 'Bestech Central Square Mall',
 'ORCHIDS The International School',
 'Marengo Asia Hospitals',
 'Sector 42-43 Rapid Metro',
 'Sector 53-54 Rapid Metro',
 'Bank Of Baroda',
 'HDFC Bank ATM',
 'Muincipal Corporation of Gurugram',
 'One Horizon Center Bus Stop',
 'Shalom Hills International School',
 'Satyam Medicare Hospital',
 'Anand Preschool',
 'Choice pharmacy',
 'Qutub Plaza',
 'Sunset point',
 'EPF Regional Office',
 'IFFCO Chowk',
 'Kingdom of Dreams',
 'Gaytri Public School',
 'KIIT College',
 'SPM Hospital',
 'Sealdah Railway Station',
 'International Airport',
 'Lemon Tree Hotel,',
 'CK Birla Hospital, Gurgaon',
 'Golf Pavilion',
 'Golf Course Road',
 'Ardee Mall',
 'Shiv Nadar School',
 'NH 148A',
 'Ambience Public School',
 'Heritage Intl Xperiential School',
 'Summer Fields School',
 'Primamed Super Speciality Hospital',
 'Uma Sanjeevani Health Centre',
 'Anya Gurgaon',
 'Hotel Golf View Suites',
 'Apollo Pharmacy',
 'Rx Pharmacy',
 'Sector 42/43 Bus Stand',
 'Genpact Chowk Bus Stop',
 'Huda City Centre Metro Station',
 'Sector 53 Metro Station',
 'ICICI Bank ATM',
 'Bharat Petroleum Retail Outlet',
 'DLF Linear Park',
 'Le Meridien Gurgaon',
 'Sector 42-43 Metro Station',
 'Ambience Mall',
 'Fun N Food Village',
 'F9 Go Karting Gurgaon',
 'Proposed Metro corridor',
 'N.H-8',
 'Shiskshantar',
 'DPS',
 'Amity',
 'Pathways',
 'GD Goenka',
 'Medicity',
 'Artemis',
 'Max, Fortis',
 'Apollo',
 'Paras Trinity Shopping Mall',
 'Swastik Multispeciality Hospital',
 'AIPL Business Co Working Space',
 'Lemon Tree Hotel Sector 60',
 'MKD Hospital',
 'Sant Soordas Sihi Metro Station',
 'De Adventure Amusement Park',
 'Vatika Business Park Sector 49',
 'Suncity School, Sector 37D',
 'The Signature Advanced Super Speciality',
 'Gurugram University Kankrola',
 'Candor TechSpace, Sector 48',
 'IndusInd Bank ATM',
 "Cherub's Cradle",
 'Mavens Orange - Hotel',
 'Learning Stars School',
 'State Bank of India',
 'Deerika HyperMart',
 'Triangular Park',
 'Artimis hospital',
 'Sector 45 SO Post Office',
 'FUEL NATION',
 'HSBC',
 'Women Police Station',
 'Best IVF Centre',
 'Huda City Centre',
 'Gurugram Public School',
 'Shikshantar - Primary School',
 'Mamta Hospital',
 'IG International Airport',
 'Omaxe City Centre',
 'DLF Grand Mall',
 'Arvy Hospital',
 'Matrikiran School',
 'DLF Cyber City',
 'Vatika Town Square',
 'Global City Centre',
 'Sohna road dhunela',
 'GD Goenka University',
 'Vardaan Hospital and Trauma Centre',
 'Maharana pratap school',
 'Sector 55-56 Metro',
 'Garhi harsaru railway station Gurgaon',
 'HUB 66',
 'Sealdah',
 'Sector 55-56 Rapid Metro Station',
 'Hasanpur',
 'The Oberoi',
 'Najafgarh Kapashera Road',
 'Hong Kong Bazaar',
 'Bharti International Convent School',
 'Badshahpur Sohna Rd Hwy, Sector 68',
 'Ashoka International School',
 'The Oberoi, Gurgaon',
 'GD Goenka Public School',
 'Chauma Road',
 'Chirag Hospital',
 'Sector-21 Metro Dwarka',
 'AIPL Joy Street Mall',
 'Radisson Hotel Sohna Road',
 'iON Digital Zone (Gurugram)',
 'HUDA Mini Golf Course',
 'IMT Road',
 'Sohna Gurgaon Road',
 'Spaze Itech Park',
 'Pallavan PreSchool, Sohna Road',
 'Radisson Hotel Gurugram Sohna Road',
 'Polaris Hospital',
 'RBSM Public school',
 'Health Care Pharmacy',
 'Sector 54 Chowk',
 'EuroKids Preschool Suncity',
 'YES Bank ATM',
 'Suncity School Gurgaon',
 'Suncity Shopping Complex',
 'Vallores Pre School',
 'Umkal Hospital',
 'Haryana City Gas',
 'Marigold Secondary School',
 'Alpine Hospital',
 'Pushpanjali Hospital',
 'Country Inn',
 'Westin',
 'The Millenium School',
 'Rajiv Chowk - Sohna Highway',
 'Central Park Resorts',
 'Swastik Hospital Sec 66',
 'Adarsh Senior Secondary School',
 'Golf Course Extension',
 'International Tech Park Gurgaon,',
 'Surajgarh Gurgaon, Golf Course Ext Rd',
 'Ananta Hospital',
 'Indus World School',
 'Golf Corse Ext. Rd.',
 'Dwarka Expy, Dhanwapur Village',
 'Shri Balaji’s Multispeciality Hospital',
 'Euro International School, Sector 37D',
 'Delhi Public School, Sector 103',
 'Park Inn, Gurgaon',
 'DLF World Tech Park',
 'Star Mall',
 'The Hive Shopping Mall',
 'NH-8, IMT Manesar',
 'Yaduvanshi Shiksha Niketan',
 'Royal Institute Of Science and Mgt',
 'Newtown Square Mall',
 'NH 352W',
 'Eros Corporate Park',
 'Manesar Road',
 'Euro International School, Sec 84',
 'Huda Metro Station (Gurugram)',
 'InfinityS Badminton Academy',
 'Sanskar Bharti Public School',
 'Manipal Hospital, Gurugram',
 'HUDA Market, Sector 14',
 'Delhi Gurgaon Expressway',
 'SCC Rooftop Drive-In',
 'Gurugram Railway Station',
 'Kings International School',
 'HUDA Market',
 'Basai Metro Station',
 'CBR Cricket Ground',
 'Rapid Metro Sector 55-56',
 'Kunskapsskolan School',
 'Omaxe Celebration Mall',
 'Gurgaon - Delhi Expy, Sector 75A',
 'Shalom Presidency School',
 'Sector 55-56 Rapid Metro',
 'Jinga Lala Theme Park Gurgaon Delhi',
 'Pataudi Rd, Sector 95B',
 'Aarvy Healthcare Super Speciality',
 'Approved Sector 37 Mero Station',
 'Signature Hospital',
 'Xavier’s International',
 'Alpine School',
 'Esplanade Mall',
 'Sector 10 Market',
 'Blue Bells Public School',
 'Galleria 108 Mall',
 'Manipal Hospital',
 'Vivanta New Delhi, Dwarka',
 'Bharat Ram Global School',
 'Canara Bank ATM',
 'Yes Bank',
 'Arc Hospital',
 'Canara Bank',
 'Axis Bank ATM',
 'City Square',
 'Shishu Kalyan School',
 'Rathore IMT Hospital',
 'DSD College',
 'Patil Station',
 'Amity University',
 'ICFAI University',
 'Indira Gandhi Airport',
 'Sapphire 83',
 'Cambridge Montessori',
 'Hyatt Regency',
 'Rao Bharat Singh International School',
 'Aarvy Healthcare',
 'Aapno Ghar',
 'Cambridge College Of Education',
 'Euro International School, Sector 84',
 'Dharampeth Main Road',
 'Old Delhi Gurgaon Road',
 'Rotary Public School',
 'Candor Techspace',
 'Manipal Hospital, Palam Vihar',
 'Moulsari Avenue',
 'Adarsh public school,Garhi Harsaru',
 'PHC Garhi Harsaru',
 'Excellere World School',
 'Aman Hospital & Surgical Centre',
 'Neemrana Palace',
 'K. R. Mangalam University',
 'Vishwas Hospital',
 'Ibis Hotel',
 'Horizon 1 Mall',
 'Ernst & Young',
 'Paras Hospital',
 'Gurgaon Faridabad Highway',
 'Mount Olympus School, Sec 79',
 'Singhania University, Manesar',
 'Capital Business Park',
 'Old Sohna Dhani Road',
 'GD Goenka Signature School',
 'Vardaan Hospital & Trauma Centre',
 'Public Bazar',
 'GD Goenka School',
 'Vatika Business Park',
 'Bharat Petrol Pump',
 'The Millennium School',
 'IndusInd Bank',
 'Artemis Hospital',
 'Tau Devi Lal Sports Complex',
 'Children Park',
 'Medanta Dialysis Center',
 'Central Park, Sohna Rd',
 'HDFC Bank ATM, Dhunela Ghamroj',
 'Ashiana Anmol  Kid Centric Homes',
 'Indianoil, Sohna - Gurgaon Rd',
 'Taj Hotel & Family Restaurant',
 'V-Square Sohna New Residential',
 'G D Goenka World School',
 'The Phoenix Project, Sohna - Gurgaon Rd',
 'Signature Global Park',
 'Signum 36',
 'Kotak Mahindra Bank, MBS Tower',
 'Pasco Automobiles, Alipur, Sohna',
 'Sohna Bus Stand',
 'Imperio School',
 'Ektaa Hospitals',
 'Vipul Trade Business Centre',
 'Radisson Hotel Gurugram',
 'Airia Mall Sector 68',
 'Damdama More',
 'Civil Hospital',
 'Western Peripheral Expressway',
 'Bhondsi Nature Park',
 'Enkays Hospital',
 'Ram Krishna Public School',
 'Aravalli Hill View Point',
 'Gurugram Global Heights School',
 'Satya The Hive Mall',
 'Gurugram Road',
 'The Signature Super Speciality Hospital',
 'Sunrise University',
 'Country Inn & Suites By Radisson',
 'Yonex Badminton Stadium',
 'Grand Hyatt',
 'Au Grand Air',
 'Indira Gandhi Eye Hospital',
 'Double Tree by Hilton',
 'Swastik Hospital',
 'Jinaglala Theme Park',
 'Scottish International School',
 'Ap Sports cricket ground',
 'Nischay Cricket Academy',
 'DLC Cricket Ground',
 'Drona Sports Village',
 'Ramada by Wyndham Gurgaon',
 'Surajgarh Gurgaon',
 'Apex Plus Hospital',
 'ZEN Golf Range & Academy',
 'The Banyan Tree Hiking Area',
 'MG Road',
 'Plaza Mall',
 'MGF Metropolitan Mall',
 'Lancers International School',
 'Gurjar Samrat Jaipal Khatana Marg',
 'Signature Global Infinity Mall Sohna',
 'Vidya Niketan Sr Sec School',
 'Sanjivani Hospital',
 'Spectra Hospital',
 'Golf Course Extn Road',
 'Tulip Violet Society, Sector 69',
 'Spaze Palazo, Golf Course Ext Rd',
 'Federal Bank Sector 71',
 'Kunskapsskolan International',
 'Southern Peripheral Rd, Gurugram',
 'Ektaa Hospitals  Main Sohna Rd',
 'Central Bank Of India Sohna Rd',
 'Sanjeevani Hospital - Child Specialist',
 'VATIKA BUSINESS PARK Sohna Rd',
 'IndianOil, Hasanpur',
 'The Medicity, Spaze iTech Park',
 'Axis Bank, Sohna Rd',
 'Shambhu Dayal High School',
 'Global City Centre Mall',
 'Ascendas OneHub Gurgaon',
 'Flying Wings Badminton Academy',
 'Saraswati Model School',
 'Orchid Business Park',
 'Farrukh Nagar Railway Station',
 'M3m 65th Avenue Mall',
 'DPS International School',
 'Rapid Metro Sector 56',
 'Sneh Hospital',
 'National Highway 8',
 'Appu Ghar Water Park',
 'Tennis Vidyalaya (Tennis Academy)',
 'Zooper India Trampoline Park',
 'Park Dr, DLF Phase 5',
 'Paras Hospitals',
 'Heritage Badminton Academy',
 'Green Field Public School',
 'Kadipur Industrial Area',
 'Spazedge IT Park',
 'JMD Megapolis',
 'Sapphire Mall',
 'More Hypermart , Vipul business park',
 'Basant Valley Global School',
 'The Paras World School',
 'Vipul Trade Centre',
 'WorldMark Gurgaon, Maidawas Rd',
 'Artemis Hospital Gurgaon',
 'Western Peripheral Expy, Gurugram',
 'Raghunath Bal Vidya Mandir School',
 'ESIC Hospital',
 'S N International School',
 'Country Inn and Suites by Radisson',
 'Sector 29 Gurgaon Pubs and Bars',
 'Emaar Business Park',
 'Southern Peripheral Rd, Dhani',
 'Omaxe City Centre Mall',
 'Badshahpur Sohna Rd Hwy, Malibu Town',
 'Ektaa Hospital',
 "St. Xavier's School",
 'PVR Drive In Theater',
 'American Express',
 'IDFC FIRST Bank',
 'Sector 42-43',
 'Sector 53-54',
 'MGF Megacity Mall',
 'Fortis hospital',
 'Double Infinity market',
 'Bamroli Cricket Ground',
 'Aman Hospital',
 'Kidzee',
 'Paras Trinity',
 'AIPL Business Club',
 'Narayana e-Techno School - Manesar',
 'HDFC Bank, Pataudi Rd',
 'SS Omnia, Sector 86',
 'Canara Bank - Nawada Fatehpur',
 'ICICI Bank ATM, Sector 86',
 'Silver Streak Multi Speciality',
 'RHM Public School',
 'Minda Industries Nawada Fatehpur',
 'Numberdar market, IMT Manesar',
 "Sodhi's Supermarket, Sector 82",
 'M3M SCO Shop cum Office',
 'Sector 42-43 Rapid Metro Station',
 'Quality Inn Gurgaon',
 'Minda Industries Limited',
 'Central Park II Road',
 'Omex City Centre Mall',
 'Damdama Lake Rd',
 'Sohna Hill Viewpoint',
 'KR Mangalam University Sohna',
 'Hero Honda Chowk',
 'Jagdish Super Market',
 'Gyaananda School',
 'Bharat Petroleum Shree Shyam Filling',
 'The Club, International City',
 'Conscient One',
 'ICICI BANK ATM, Annapurna MKT',
 'ESIC Dispensary',
 'Canara Bank New Palam Vihar',
 'Dwarka',
 'Radha Krishan Mandir',
 'Daultabad Stadium',
 'Gurgaon Gramin Bank',
 'IGIA Airport',
 'SCR Model School',
 'Golden Tulip Suites Gurgaon',
 'South point Mall',
 'Pathways School Gurgaon',
 'Kidzee Sec-93',
 'Jhankar Group of Institutions',
 'Dwarka Expy/Northern Peripheral Rd',
 'Dwarka expressway Basai crossing',
 'Sethi Hospital',
 'HDFC Bank',
 'The Sixth Element School',
 'K.R.Mangalam World School',
 'Sushil Park',
 'Peer Baba Ki Mazar',
 'Punjab National Bank',
 'CoNexus.Life B35',
 'Medhaam Pre School & Daycare',
 'Moksh Wellness Pvt Ltd.',
 'Marriott Courtyard',
 'World Tech Park',
 'Athena',
 'Bharat Petroleum Petrol Pump',
 'Sanskar Jyoti School',
 'Arc Multi Speciality Hospital',
 'Narayana e Techno School',
 'Medeor Hospital, Manesar',
 "Guls' Kitchen",
 'The Nook',
 'Open Tap',
 'Frescos',
 'Subway',
 'BOB ATM',
 'PNB ATM',
 'Citibank ATM',
 'Gurugram Hospital',
 'Govind Hospital',
 'Manish Gallexie 91',
 'Silver Streak Multi Speciality Hospital',
 'Holiday Inn Gurugram',
 'Airport',
 'Vatika Sector Road',
 'Gurugram University Sector 87',
 'CNG Petrol Pump',
 'Vivek Model School',
 'Dwarka Expressway Link Road',
 "McDonald's India 24 Hours",
 'Garhi Budhera Road',
 'Iris Broadway Gurugram',
 'iGrow Montessori Play School',
 'Matrikiran High School',
 'Badsa AMS Hospital',
 'GlobalHealthcare Multispeciality',
 'Cricket Academy',
 "V'Lante Mall",
 'NH 48 Gurugram',
 'Patli Railway Station',
 'V Club',
 'Fitso Sector 48 Spuddy, Badminton',
 'Lotus Valley International School',
 'Badshapur Sohna Highway',
 'Bharat Singh fuel company',
 'Basai Enclave Park',
 'Bank Of Baroda ATM',
 'The Holy Kingdom Public School',
 'Shiv Mandir',
 'Open gym garden',
 'KFG sports club Parking',
 'Sector 37 Police Station',
 'Alfaa Health Care Hospital',
 'Euro Intl School Sec-51',
 'Mall Fifty One',
 'NH 8, Sector 15 Part 2',
 'K.D. Hospital',
 'Gurgaon Road',
 "Saint Paul's School",
 'Indus valley Public School',
 'MDS Public School',
 'Signature Super Speciality Hospital',
 'Harsaru Village Bus Stop',
 'Jadon Pharmacy',

In [55]:
cosine_sim_matrix = 0.5*cosine_sim1 + 0.8*cosine_sim2 + 1*cosine_sim3

In [56]:
import pickle
pickle.dump(cosine_sim_matrix, open('../data/cosine_sim_matrix.pkl', 'wb'))